=== Data types and values

// Added
${syntax: dataTypeIR dataValue}

// Added
Data types represent the types that aggregate other types, including lists,
tuples, header stacks, structs, headers, header unions, and enums.

==== List types and values

// 306
A list holds zero or more values, where every element must have the same type.
The type of a list where all elements have type `T` is written as

// 307
[source,p4]
----
list<T>
----

// 308 - Modified
${syntax: listType listTypeIR listValue}

===== Type checking

// Added
${rulegroup-source: Type_ok/listType}
${rulegroup-prose: Type_ok/listType}

===== Well-formedness

// Added
${rulegroup-source: Type_wf/listTypeIR}
${rulegroup-prose: Type_wf/listTypeIR}

==== Tuple types and values

// 301
A tuple is similar to a `struct`, in that it holds multiple values. The type of
tuples with `n` component types `T1`, ..., `Tn` is written as

// 302
[source,p4]
----
tuple<T1, /* more fields omitted */, Tn>
----

// 305
The type `tuple<>` is a tuple type with no components.

// 303 - Modified
${syntax: tupleType tupleTypeIR tupleValue}

===== Type checking

// Added
${rulegroup-source: Type_ok/tupleType}
${rulegroup-prose: Type_ok/tupleType}

===== Well-formedness

// Added
${rulegroup-source: Type_wf/tupleTypeIR}
${rulegroup-prose: Type_wf/tupleTypeIR}

[#sec-header-stack]
==== Header stack types and values

// 282
A header stack represents an array of headers or header unions. A header stack
type is defined as:

// 283 - Modified
${syntax: headerStackType headerStackTypeIR}

// 284 - Modified
where `namedType` refers to a header or header union type. For a header stack
`hs[n]`, the term `n` is the maximum defined size, and must be a local
compile-time known value that is a positive integer. Nested header stacks are
not supported.

// Added
${syntax: headerStackValue}

// 284 - Modified
At runtime a stack contains `n` values with type `namedType`, only some of
which may be valid.

// 285
For example, the following declarations,

// 286
[source,p4]
----
header Mpls_h {
    bit<20> label;
    bit<3>  tc;
    bit     bos;
    bit<8>  ttl;
}
Mpls_h[10] mpls;
----

// 287
introduce a header stack called `mpls` containing ten entries, each of type
`Mpls_h`.

===== Type checking

// Added
${rulegroup-source: Type_ok/headerStackType}
${rulegroup-prose: Type_ok/headerStackType}

===== Well-formedness

// Added
${rulegroup-source: Type_wf/headerStackTypeIR}
${rulegroup-prose: Type_wf/headerStackTypeIR}

[#sec-array]
==== Array types and values

NOTE: This feature will be added to P4 v1.2.5.6. It is not modeled in P4-SpecTec yet.

[#sec-struct]
==== Struct types and values

// 297
P4 `struct` types are defined with the following syntax:

// 298 - Modified
${syntax: typeField structTypeDeclaration}

// 299 - Modified
This declaration introduces a new struct type definition with the specified
name in the current scope. Field names have to be distinct. An empty struct
(with no fields) is legal.

// Added
${syntax: structTypeDefIR}

// 299 - Modified
For example, the structure `Parsed_headers` below contains the headers
recognized by a simple parser:

// 300
[source,p4]
----
header Tcp_h { /* fields omitted */ }
header Udp_h { /* fields omitted */ }
struct Parsed_headers {
    Ethernet_h ethernet;
    Ip_h       ip;
    Tcp_h      tcp;
    Udp_h      udp;
}
----

// Added
Struct types can be used by referring to their names. Generic struct types can
be used by specializing their type parameters with type arguments. Internally,
struct types and values are represented as follows:

// Added
${syntax: fieldTypeIR structTypeIR fieldValue structValue}

===== Type checking

// Added
Struct types are introduced by `struct` declarations. Its typing rule is
explained in <<sec-struct-type-declaration>>. Struct types are then used by
referencing their names. Thus struct types can be obtained from named types,
as illustrated in <<sec-named-type>>.

===== Well-formedness

// Added
${rulegroup-source: Type_wf/structTypeIR}
${rulegroup-prose: Type_wf/structTypeIR}

[#sec-header]
==== Header types and values

// 262
The declaration of a `header` type is given by the following syntax:

// 263 - Modified
${syntax: typeField headerTypeDeclaration}

// 264
where each `type` is restricted to a bit-string type (fixed or variable), a
fixed-width signed integer type, a boolean type, or a struct that itself
contains other struct fields, nested arbitrarily, as long as all of the "leaf"
types are `bit<W>`, `int<W>`, a serializable `enum`, or a `bool`. If a `bool`
is used inside a P4 header, all implementations encode the `bool` as a one bit
long field, with the value `1` representing `true` and `0` representing
`false`. Field names have to be distinct.

// 265 - Modified
A header declaration introduces a new identifier in the current scope; the type
definition can be referred to using this identifier.

// Added
${syntax: headerTypeDefIR}

// 265 - Modified
A header is similar to a `struct` in C, containing all the specified fields.
However, in addition, a header also contains a hidden Boolean "validity" field.
When the "validity" bit is `true` we say that the "header is valid". When a
local variable with a header type is declared, its "validity" bit is
automatically set to `false`. The "validity" bit can be manipulated by using
the header methods `isValid()`, `setValid()`, and `setInvalid()`.

// 267
Header types may be empty:

// 268
[source,p4]
----
header Empty_h { }
----

// 269
Note that an empty header still contains a validity bit.

// 270
When a struct is inside of a header, the order of the fields for the purposes
of `extract` and `emit` calls is the order of the fields as defined in the
source code. An example of a header including a struct is included below.

// 271
[source,p4]
----
struct ipv6_addr {
    bit<32> Addr0;
    bit<32> Addr1;
    bit<32> Addr2;
    bit<32> Addr3;
}

header ipv6_t {
    bit<4>    version;
    bit<8>    trafficClass;
    bit<20>   flowLabel;
    bit<16>   payloadLen;
    bit<8>    nextHdr;
    bit<8>    hopLimit;
    ipv6_addr src;
    ipv6_addr dst;
}
----

// 272
Headers that do not contain any `varbit` field are _fixed size_. Headers
containing `varbit` fields have _variable size_. The size (in bits) of a
fixed-size header is simply the sum of the sizes of all component fields
(without counting the validity bit). There is no padding or alignment of the
header fields. Targets may impose additional constraints on header
types--e.g., restricting headers to sizes that are an integer number of bytes.

// 273
For example, the following declaration describes a typical Ethernet header:

// 274
[source,p4]
----
header Ethernet_h {
   bit<48> dstAddr;
   bit<48> srcAddr;
   bit<16> etherType;
}
----

// 275
The following variable declaration uses the newly introduced type `Ethernet_h`:

// 276
[source,p4]
----
Ethernet_h ethernetHeader;
----

// 277
P4's parser language provides an `extract` method that can be used to "fill in"
the fields of a header from a network packet, as described in
<<sec-packet-data-extraction>>. The successful execution of an `extract`
operation also sets the validity bit of the extracted header to `true`.

// 278
Here is an example of an IPv4 header with variable-sized options:

// 279
[source,p4]
----
header IPv4_h {
   bit<4>       version;
   bit<4>       ihl;
   bit<8>       diffserv;
   bit<16>      totalLen;
   bit<16>      identification;
   bit<3>       flags;
   bit<13>      fragOffset;
   bit<8>       ttl;
   bit<8>       protocol;
   bit<16>      hdrChecksum;
   bit<32>      srcAddr;
   bit<32>      dstAddr;
   varbit<320>  options;
}
----

// 280
As demonstrated by a code example in <<sec-packet-extract-two>>, another way to
support headers that contain variable-length fields is to define two headers --
one fixed length, one containing a `varbit` field -- and extract each part in
separate parsing steps.

// 281
Notice that the names `isValid`, `setValid`, `minSizeInBits`, etc. are all
valid header field names.

// Added
Internally, header types and values are represented as follows:

// Added
${syntax: headerTypeIR headerValue}

===== Type checking

// Added
Header types are introduced by `header` declarations. Its typing rule is
explained in <<sec-header-type-declaration>>. Header types are then used by
referencing their names. Thus header types can be obtained from named types,
as illustrated in <<sec-named-type>>.

===== Well-formedness

// Added
${rulegroup-source: Type_wf/headerTypeIR}
${rulegroup-prose: Type_wf/headerTypeIR}

[#sec-header-union]
==== Header union types and values

// 289
A header union represents an alternative containing at most one of several
different headers. Header unions can be used to represent "options" in
protocols like TCP and IP. They also provide hints to P4 compilers that only
one alternative will be present, allowing them to conserve storage resources.

// 290
A header union is defined as:

// 291 - Modified
${syntax: typeField headerUnionTypeDeclaration}

// 292 - Modified
This declaration introduces a new type definition with the specified name in
the current scope.

// Added
${syntax: headerUnionTypeDefIR}

// 292 - Modified
Each element of the list of fields used to declare a header union must be of
header type. An empty list of fields is legal. Field names have to be distinct.

// 293
As an example, the type `Ip_h` below represents the union of an IPv4 and IPv6
headers:

// 294
[source,p4]
----
header_union IP_h {
  IPv4_h v4;
  IPv6_h v6;
}
----

// 295
A header union is not considered a type with fixed length.

// 296
Internally, header union types and values are represented as follows:

// Added
${syntax: headerUnionTypeIR headerUnionValue}

===== Type checking

// Added
Header union types are introduced by `header_union` declarations. Its typing
rule is explained in <<sec-header-union-type-declaration>>. Header union types
are then used by referencing their names. Thus header union types can be
obtained from named types, as illustrated in <<sec-named-type>>.

===== Well-formedness

// Added
${rulegroup-source: Type_wf/headerUnionTypeIR}
${rulegroup-prose: Type_wf/headerUnionTypeIR}

[#sec-enum]
==== Enum types and values

// 246
An enumeration type is defined using the following syntax:

// 247 - Modified
${syntax: namedExpression
          namedExpressionList
          enumTypeDeclaration}

// Added
An `enum` declaration introduces a new enum type definition:

// Added
${syntax: enumTypeDefIR}

// Added
Enums cannot be parameterized over type parameters, thus is always monomorphic.

// Added
Enums can be declared in two different ways, depending on whether or not an
underlying representation type is provided. The two forms are described below.

// Added
Internally, enum types and values are represented as follows:

// Added
${syntax: valueFieldIR enumTypeIR enumValue}

[#sec-enum-non-serializable]
===== Enum type declaration without an underlying type

// 248
For example, the declaration

// 249
[source,p4]
----
enum Suits { Clubs, Diamonds, Hearths, Spades }
----

// 250
introduces a new enumeration type, which contains four elements--e.g.,
`Suits.Clubs`. An `enum` declaration introduces a new identifier in the current
scope for naming the created type along with its distinct elements. The
underlying representation of the `Suits` enum is not specified, so their "size"
in bits is not specified (it is target-specific).

[#sec-enum-serializable]
===== Enum type declaration with an underlying type

// 251
It is also possible to specify an `enum` with an underlying representation.
These are sometimes called serializable ``enum``s, because headers are allowed
to have fields with such `enum` types. This requires the programmer provide
both the fixed-width unsigned (or signed) integer type and an associated
integer value for each symbolic entry in the enumeration.

// 1274
For example, the declaration

// 253
[source,p4]
----
enum bit<16> EtherType {
  VLAN      = 0x8100,
  QINQ      = 0x9100,
  MPLS      = 0x8847,
  IPV4      = 0x0800,
  IPV6      = 0x86dd
}
----

// 254
introduces a new enumeration type, which contains five elements--e.g.,
`EtherType.IPV4`.  This `enum` declaration specifies the fixed-width unsigned
integer representation for each entry in the `enum` and provides an underlying
type: `bit<16>`. This kind of `enum` declaration can be thought of as declaring
a new `bit<16>` type, where variables or fields of this type are expected to be
unsigned 16-bit integer values, and the mapping of symbolic to numeric values
defined by the `enum` are also defined as a part of this declaration.  In this
way, an `enum` with an underlying type can be thought of as being a type
derived from the underlying type carrying equality, assignment, and casts
to/from the underlying type.

// 255
Compiler implementations are expected to raise an error if the fixed-width
integer representation for an enumeration entry falls outside the
representation range of the underlying type.

// 256
For example, the declaration

// 257
[source,p4]
----
enum bit<8> FailingExample {
  first           = 1,
  second          = 2,
  third           = 3,
  unrepresentable = 300
}
----

// 258
would raise an error because `300`, the value associated with
`FailingExample.unrepresentable` cannot be represented as a `bit<8>` value.

// 259
The initializer `expression` must be a local compile-time known value.

// 260
Annotations, represented by the non-terminal `annotationList`, are described in
<<sec-annotations>>.

===== Type checking

// Added
Enum types are introduced by `enum` declarations. Its typing rule is explained
in <<sec-enum-type-declaration>>. Enum types are then used by referencing their
names. Thus enum types can be obtained from named types, as illustrated in
<<sec-named-type>>.

===== Well-formedness

// Added
${rulegroup-source: Type_wf/enumTypeIR}
${rulegroup-prose: Type_wf/enumTypeIR}
