=== Object types and values

// Added
[[objectTypeIR]]
[[objectReferenceValue]]
${syntax: objectTypeIR objectReferenceValue}

Stateful objects are represented using `objectTypeIR`. At runtime, these
objects are passed along directionless parameters as references
(`objectReferenceValue`).

==== Extern object types

// Section 7.2.11.2 of the P4-16 Language Specification
An extern object declaration declares an object and all methods that can be
invoked to perform computations and to alter the state of the object. Extern
object declarations can also optionally declare constructor methods; these must
have the same name as the enclosing `extern` type, no type parameters, and no
return type. Extern declarations may only appear as allowed by the architecture
model and may be specific to a target.

${syntax: externConstructorPrototype externMethodPrototype
          externConstructorOrMethodPrototype externObjectDeclaration}

For example, the P4 core library introduces two extern objects `packet_in` and
`packet_out` used for manipulating packets (see <<sec-packet-data-extraction>>
and <<sec-deparse>>). Here is an example showing how the methods of these
objects can be invoked on a packet:

[source,p4]
----
extern packet_out {
    void emit<T>(in T hdr);
}
control d(packet_out b, in Hdr h) {
    apply {
        b.emit(h.ipv4);       // write ipv4 header into output packet
    }                         // by calling emit method
}
----

// Added
Extern object types can be referred to using their name. Internally, extern
object types are represented as:

[[externObjectTypeIR]]
${syntax: externObjectTypeIR}

===== Type checking

// Added
Extern object types are introduced by `extern` declarations. Its typing rule is
explained in <<sec-sem-Decl_ok-externObjectDeclaration>>.

Extern object types are then used by referencing their names. Thus extern
object types can be obtained from named types, as illustrated in
<<sec-def-namedType>>.

===== Well-formedness

// Added
${rulegroup: Type_wf/externObjectTypeIR}
${ruleprose: Type_wf/externObjectTypeIR}

==== Parser object types

// Section 7.2.13.1 of the P4-16 Language Specification
A parser type declaration describes the signature of a parser. A parser should
have at least one argument of type `packet_in`, representing the received
packet that is processed.

${syntax: parserTypeDeclaration}

For example, the following is a type declaration of a parser type named `P`
that is parameterized on a type variable `H`. That parser receives as input a
`packet_in` value `b` and produces two values:

* A value with a user-defined type `H`
* A value with a predefined type `Counters`

[source,p4]
----
struct Counters { /* Fields omitted */ }
parser P<H>(packet_in b,
            out H packetHeaders,
            out Counters counters);
----

// Added
Parser types can be referred to using their name and type arguments.
Internally, parser types are represented as:

[[parserObjectTypeIR]]
${syntax: parserObjectTypeIR}

===== Type checking

// Added
Parser object types are introduced by `parser` declarations. Its typing rule is
explained in <<sec-sem-Decl_ok-parserTypeDeclaration>>.

Parser object types are then used by referencing their names. Thus parser
object types can be obtained from named types, as illustrated in
<<sec-def-namedType>>.

===== Well-formedness

// Added
${rulegroup: Type_wf/parserObjectTypeIR}
${ruleprose: Type_wf/parserObjectTypeIR}

==== Control object types

// Section 7.2.13.2 of the P4-16 Language Specification
A control type declaration describes the signature of a control block.

${syntax: controlTypeDeclaration}

Control type declarations are similar to parser type declarations.

// Added
Control types can be referred to using their name and type arguments.
Internally, control types are represented as:

[[controlObjectTypeIR]]
${syntax: controlObjectTypeIR}

===== Type checking

// Added
Control object types are introduced by `control` declarations. Its typing rule is
explained in <<sec-sem-Decl_ok-controlTypeDeclaration>>.

Control object types are then used by referencing their names. Thus control
object types can be obtained from named types, as illustrated in
<<sec-def-namedType>>.

===== Well-formedness

// Added
${rulegroup: Type_wf/controlObjectTypeIR}
${ruleprose: Type_wf/controlObjectTypeIR}

==== Package object types

// Section 7.2.14 of the P4-16 Language Specification
A package type describes the signature of a package.

${syntax: packageTypeDeclaration}

// Added
Package types can be referred to using their name and type arguments.
Internally, package types are represented as:

[[packageObjectTypeIR]]
${syntax: packageObjectTypeIR}

===== Type checking

// Added
Package object types are introduced by `package` declarations. Its typing rule is
explained in <<sec-sem-Decl_ok-packageTypeDeclaration>>.

Package object types are then used by referencing their names. Thus package
object types can be obtained from named types, as illustrated in
<<sec-def-namedType>>.

===== Well-formedness

// Added
${rulegroup: Type_wf/packageObjectTypeIR}
${ruleprose: Type_wf/packageObjectTypeIR}

==== Table object types

// Section 14.2 of the P4-16 Language Specification
A `table` declaration introduces a table instance.

${syntax: tableDeclaration}

// Added
Internally, table types are represented as:

[[tableObjectTypeIR]]
${syntax: tableObjectTypeIR}

===== Well-formedness

// Added
${rulegroup: Type_wf/tableObjectTypeIR}
${ruleprose: Type_wf/tableObjectTypeIR}

==== Object reference values

P4 objects are stateful, thus their values are references to the actual objects
allocated in the global store.

[[objectReferenceValue]]
${syntax: oid objectReferenceValue}

Objects are referred to by their fully-qualified names from the top-level scope.
