[#sec-def-synthesizedTypeIR]
[#sec-def-synthesizedValue]
=== Synthesized types and values

For the purposes of type-checking the P4 compiler can synthesize some type
representations which cannot be directly expressed by users.

[#sec-def-defaultExpression]
[#sec-def-defaultTypeIR]
[#sec-def-defaultValue]
==== Default types and values

${syntax: defaultExpression}

A left-value can be initialized automatically with a default value of the
suitable type using the syntax `+...+` (see <<sec-default-values>>).

[source,p4]
----
struct S {
     bit<32> b32;
     bool b;
}

enum int<8> N0 {
   one = 1,
   zero = 0,
   two = 2
}

enum N1 {
     A, B, C, F
}

S s0 = ...;  // initialize s0 with the default value { 0, false }
N0 n0 = ...;  // initialize n0 with the default value 0
N1 n1 = ...;  // initialize n1 with the default value N1.A
----

Internally, the type and value of `+...+` itself is represented as:

${syntax: defaultTypeIR
          defaultValue}

[#sec-sem-Type_wf-defaultTypeIR]
===== Well-formnedness

${rulegroup: Type_wf/defaultTypeIR}
${ruleprose: Type_wf/defaultTypeIR}

[#sec-def-dataExpression]
[#sec-def-invalidHeaderTypeIR]
[#sec-def-invalidHeaderValue]
==== Invalid header types and values

${syntax: dataExpression}

The expression `+{#}+` represents an invalid header of some type, but it can be
any header or header union type. A P4 compiler may require an explicit cast on
this expression in cases where it cannot determine the particular header or
header union type from the context.

For example:

[source,p4]
----
header H { bit<32> x; bit<32> y; }
H h;
h = {#};   // This make the header h become invalid
----

Note that the `+#+` character cannot be misinterpreted as a preprocessor
directive, since it cannot be the first character on a line when it
occurs in the single lexical token `+{#}+`, which may not have
whitespace or any other characters between those shown.

Internally, the type and value of `+{#}+` itself is represented as:

${syntax: invalidHeaderTypeIR
          invalidHeaderValue}

[#sec-sem-Type_wf-invalidHeaderTypeIR]
===== Well-formnedness

${rulegroup: Type_wf/invalidHeaderTypeIR}
${ruleprose: Type_wf/invalidHeaderTypeIR}

[#sec-def-sequenceElementExpression]
[#sec-def-sequenceTypeIR]
[#sec-def-sequenceValue]
==== Sequence types and values

Sequences can be assigned to other tuples with the same type.

[source,p4]
----
tuple<bit<32>, bool> x = { 10, false };
----

A sequence expression is written using curly braces, with each element
separated by a comma:

${syntax: sequenceElementExpression
          dataElementExpression
          dataExpression}

Sequence expressions can be assigned to expressions of type `tuple`, `struct`
or `header`, and can also be passed as arguments to methods. Sequences may be
nested.

For example, the following program fragment uses a sequence expression to pass
several header fields simultaneously to a learning provider:

[source,p4]
----
extern LearningProvider<T> {
    LearningProvider();
    void learn(in T data);
}

LearningProvider<tuple<bit<48>, bit<32>>>() lp;

lp.learn( { hdr.ethernet.srcAddr, hdr.ipv4.src } );
----

A sequence may be used to initialize a structure if the tuple has the same
number of elements as fields in the structure. The effect of such an
initializer is to assign the n^th^ element of the tuple to the n^th^ field in
the structure:

[source,p4]
----
struct S {
    bit<32> a;
    bit<32> b;
}
const S x = { 10, 20 }; // a = 10, b = 20
----

Sequence expressions that have `+...+` as their last element are allowed to
give values to only a subset of the fields of the struct or header type to
which it evaluates. Any field names not given a value explicitly will be given
their default value (see <<sec-initializing-with-default-values>>).

The type of a sequence expression is a sequence type.

${syntax: sequenceTypeIR
          sequenceValue}

[#sec-sem-Type_wf-sequenceTypeIR]
===== Well-formnedness

${rulegroup: Type_wf/sequenceTypeIR}
${ruleprose: Type_wf/sequenceTypeIR}

[#sec-def-recordElementExpression]
[#sec-def-recordTypeIR]
[#sec-def-recordValue]
==== Record types and values

One can write record expressions that evaluate to a structure or header. The
syntax of these expressions is given by:

${syntax: recordElementExpression
          dataElementExpression
          dataExpression}

The following example shows a structure-valued expression used in an
equality comparison expression:

[source,p4]
----
struct S {
    bit<32> a;
    bit<32> b;
}

void f() {
  S s;

  // Compare s with a record expression
  bool b = s == (S) { a = 1, b = 2 };
}
----

Record expressions can be used in the right-hand side of assignments, in
comparisons, in field selection expressions, and as arguments to functions,
method or actions. Record expressions are not left values.

Record expressions that do not have `+...+` as their last element must provide
a value for every member of the struct or header type to which it evaluates, by
mentioning each field name exactly once.

Record expressions that have `+...+` as their last element are
allowed to give values to only a subset of the fields of the struct or
header type to which it evaluates. Any field names not given a value
explicitly will be given their default value (see <<sec-initializing-with-default-values>>).

The order of the fields of the `struct` or `header` type does not need to match
the order of the values of the structure-valued expression.

It is a compile-time error if a field name appears more than once in the same
structure-valued expression.

Internally, the type and value of a record expression is represented as:

${syntax: recordTypeIR
          recordValue}

[#sec-sem-Type_wf-recordTypeIR]
===== Well-formnedness

${rulegroup: Type_wf/recordTypeIR}
${ruleprose: Type_wf/recordTypeIR}

[#sec-def-setTypeIR]
[#sec-def-setValue]
==== Set types and values

${syntax: setTypeIR}

The set type describes _sets_ of values of some type `T`. Set types can only
appear in restricted contexts in P4 programs. For example, the range expression
`8w5 .. 8w8` describes a set containing the 8-bit numbers 5, 6, 7, and 8, so
its type is `set<bit<8>>;`. This expression can be used as a label in a
`select` expression (see <<sec-select>>), matching any value in this range. Set
types cannot be named or declared by P4 programmers, they are only synthesized
by the compiler internally and used for type-checking.

Set values are represented internally as:

${syntax: setValue}

===== Type nesting

${funcprose: nestable_set}
${table: nestable'_set}

${funcprose: nestable_tuple_in_set}
${table: nestable'_tuple_in_set}

${funcprose: nestable_sequence_in_set}
${table: nestable'_sequence_in_set}

[#sec-sem-Type_wf-setTypeIR]
===== Well-formnedness

${rulegroup: Type_wf/setTypeIR}
${ruleprose: Type_wf/setTypeIR}

[#sec-def-tableMetadataTypeIR]
[#sec-def-tableMetadataValue]
==== Table metadata types and values

Calling an apply method on a table instance returns a value with a table
metadata `struct` type with three fields. This structure is synthesized by the
compiler automatically. For each `table T`, the compiler synthesizes a table
metadata `enum` and a `struct`, shown in pseudo-P4:

[source,p4pseudo]
----
enum action_list(T) {
   // one field for each action in the actions list of table T
}
struct apply_result(T) {
    bool hit;
    bool miss;
    action_list(T) action_run;
}
----

The evaluation of the `apply` method sets the `hit` field to `true` and the
field `miss` to `false` if a match is found in the lookup-table; if a match is
not found `hit` is set to `false` and `miss` to `true`. These bits can be used
to drive the execution of the control-flow in the control block that invoked
the table:

[source,p4]
----
if (ipv4_match.apply().hit) {
    // there was a hit
} else {
    // there was a miss
}

if (ipv4_host.apply().miss) {
    ipv4_lpm.apply(); // Look up the route only if host table missed
}
----

The `action_run` field indicates which kind of action was executed
(irrespective of whether it was a hit or a miss). It can be used in a switch
statement:

[source,p4]
----
switch (dmac.apply().action_run) {
    Drop_action: { return; }
}
----

Internally, the type and value of table metadata is represented as:

${syntax: tableMetadataTypeIR
          tableMetadataValue}

[#sec-sem-Type_wf-tableMetadataTypeIR]
===== Well-formnedness

${rulegroup: Type_wf/tableMetadataTypeIR}
${ruleprose: Type_wf/tableMetadataTypeIR}
