(* Stub Dispatch for the [spec_parts_il] library — copied into [compiled/] by
   `make restore-stub`. Every entry point fails, telling the user to generate
   the real interpreter. Overwritten by `make gen-ocaml-il`. *)

[@@@warning "-8-11-26-27-30-32-33-39"]

open Util.Source
open Ctx

let eval_func (_name : string) (_typs : Typ.t list) (_args : Value.t list) :
    Run.func_result =
  Fail (no_region, "ML interpreter: run `make gen-ocaml-il` to generate it")

let eval_rel (_name : string) (_args : Value.t list) : Run.rel_result =
  Fail (no_region, "ML interpreter: run `make gen-ocaml-il` to generate it")

let eval_program (_relname : string) (_includes : string list) (_path : string)
    : Run.program_result =
  Fail
    (`Runtime
       (no_region, "ML interpreter: run `make gen-ocaml-il` to generate it"))

let unmarshal_program (_value : Value.t) : Value.t =
  failwith "ML interpreter: run `make gen-ocaml-il` to generate it"

(* Typed mixop bridges — re-exported by the real Dispatch from the generated
   parts. Stubbed here so the [spec_parts_il] surface stays stable when the
   stub is in place (`make build`). *)

let make_case_typed (_mixop : Domain.Mixfix.mixop) (_args : Obj.t list)
    (_typ : Typ.t) : Obj.t =
  failwith "ML interpreter: run `make gen-ocaml-il` to generate it"

let case_of_typed (_x : Obj.t) (_typ : Typ.t) : Obj.t Domain.Mixfix.t =
  failwith "ML interpreter: run `make gen-ocaml-il` to generate it"

(* Typename-indexed state-persist bridge — stubbed for the [build] surface;
   the real dispatch is generated by `make gen-ocaml-il`. *)

let marshal_typed (_typ : Typ.t) (_x : Obj.t) : Value.t =
  failwith "ML interpreter: run `make gen-ocaml-il` to generate it"

let unmarshal_typed (_typ : Typ.t) (_v : Value.t) : Obj.t =
  failwith "ML interpreter: run `make gen-ocaml-il` to generate it"
