[#sec-instantiation-declaration]
=== Instantiations

// Section 11.3 of the P4-16 Language Specification
Instantiations are similar to variable declarations, but are reserved for the
types with constructors (``extern`` objects, ``control`` blocks, ``parser``s,
and ``package``s):

// Added
${syntax: instantiation}

// Modified section 11.3 of the P4-16 Language Specification
An instantiation is written as a constructor invocation followed by a name. In
P4~IR~, instantiations have the syntax:

// Added
${syntax: instantiationIR}

// Modified section 11.3 of the P4-16 Language Specification
Instantiations are always executed at compilation time (Section
<<#sec-instantiation>>). The effect is to allocate an object with the specified
name, and to bind it to the result of the constructor invocation. Note that
instantiation arguments can be specified by name.

For example, a hypothetical bank of counter objects can be instantiated as
follows:

[source,p4]
----
// from target library
enum CounterType {
   Packets,
   Bytes,
   Both
}
extern Counter {
    Counter(bit<32> size, CounterType type);
    void increment(in bit<32> index);
}
// user program
control c(/* parameters omitted */) {
    Counter(32w1024, CounterType.Both) ctr;  // instantiation
    apply { /* body omitted */ }
}
----

// Modified section 11.3 of the P4-16 Language Specification
A P4 program may not instantiate controls and parsers at the top-level. This
restriction is designed to ensure that most state resides in the architecture
itself, or is local to a ``parser`` or ``control``. For example, the following
program is not valid:

[source,p4]
----
// Program
control c(/* parameters omitted */) { /* body omitted */ }
c() c1;  // illegal top-level instantiation
----

because control `c1` is instantiated at the top-level. Note that top-level
declarations of constants and instantiations of extern objects are permitted.

[#sec-instantiation-abstract-methods]
==== Instantiating objects with abstract methods

// Section 11.3.1 of the P4-16 Language Specification
When instantiating an extern type that has ``abstract`` methods users have to
supply implementations for all such methods. This is done using object
initializers:

// Added
${syntax: objectDeclaration
          objectDeclarationList
          objectInitializer}

// Added
In P4~IR~, object initializers have the syntax:

// Added
${syntax: objectInitializerIR}

// Section 11.3.1 of the P4-16 Language Specification
Abstract method implementations must use the same number of parameters, and the
same parameter directions as those declared in the extern object declaration.
Note that overloading of abstract methods is not allowed, thus an
implementation could be matched to a declaration only with the method name.

// Modified section 11.3.1 of the P4-16 Language Specification
Abstract method implementations can only use the supplied arguments or refer to
values that are in the same initializer block or the top-level scope. When
calling another method of the same instance the `this` keyword is used to
indicate the current object instance:

// Section 11.3.1 of the P4-16 Language Specification
[source,p4]
----
// Instantiate a balancer
Balancer() b = {  // provide an implementation for the abstract methods
    bit<4> on_new_flow(in bit<32> address) {
        // uses the address and the number of flows to balance the load
        bit<32> count = this.getFlowCount();  // call method of the same instance
        return (address + count)[3:0];
    }
}
----

// Section 11.3.1 of the P4-16 Language Specification
Abstract methods may be invoked by users explicitly, or they may be invoked by
the target architecture. The architectural description has to specify when the
abstract methods are invoked and what the meaning of their arguments and return
values is; target architectures may impose additional constraints on abstract
methods.

[discrete]
====== Type checking instantiations

Instantiations are type checked with the relation:

${relation-title-source: InstDecl_ok}
${relation-title-prose: InstDecl_ok}

${rulegroup-source: InstDecl_ok}
${rulegroup-prose: InstDecl_ok}

There are two sub-relations, depending on whether object initializers were
provided or not.

* **When object initializers are absent:**

${relation-title-source: InstDecl_non_objectInitializer_ok}
${relation-title-prose: InstDecl_non_objectInitializer_ok}

${rulegroup-source: InstDecl_non_objectInitializer_ok}
${rulegroup-prose: InstDecl_non_objectInitializer_ok}

* **When object initializers are present:**

${relation-title-source: InstDecl_objectInitializer_ok}
${relation-title-prose: InstDecl_objectInitializer_ok}

${rulegroup-source: InstDecl_objectInitializer_ok}
${rulegroup-prose: InstDecl_objectInitializer_ok}

When used as a top-level declaration, instantiations are typed with:

${rulegroup-source: Decl_ok/instantiation}
${rulegroup-prose: Decl_ok/instantiation}

[discrete]
====== Compile-time evaluation of instantiations

Instantiations are evaluated at compile-time with the relation:

${relation-title-source: InstDecl_inst}
${relation-title-prose: InstDecl_inst}

${rulegroup-source: InstDecl_inst}
${rulegroup-prose: InstDecl_inst}

When used as a top-level declaration, instantiations are evaluated with:

${rulegroup-source: Decl_inst/instantiationIR}
${rulegroup-prose: Decl_inst/instantiationIR}
