[#sec-errorDeclaration]
=== Error declaration

The error type contains opaque distinct values that can be used to signal
errors. It is written as `error`. New elements of the error type are defined
with the syntax:

${syntax: errorDeclaration
          errorDeclarationIR}

All elements of the `error` type are inserted into the `error` namespace,
irrespective of the place where an error is defined. `error` is similar to an
enumeration (`enum`) type in other languages. A program can contain multiple
`error` declarations, which the compiler will merge together. It is an error to
declare the same identifier multiple times. Expressions of type `error` are
described in <<sec-error-exprs>>.

For example, the following declaration creates two elements of the `error` type
(these errors are declared in the P4 core library):

[source,p4]
----
error { ParseError, PacketTooShort }
----

The underlying representation of errors is target-dependent.

[discrete]
==== Type checking

${rulegroup-source: Decl_ok/errorDeclaration}
${rulegroup-prose: Decl_ok/errorDeclaration}

[discrete]
==== Compile-time evaluation

${rulegroup-source: Decl_inst/errorDeclarationIR}
${rulegroup-prose: Decl_inst/errorDeclarationIR}
