[#sec-externDeclaration]
=== Extern declaration

${syntax: externDeclaration
          externDeclarationIR}

[#sec-externFunctionDeclaration]
==== Extern function declaration

${syntax: externFunctionDeclaration
          externFunctionDeclarationIR}

[#sec-sem-Decl_ok-externFunctionDeclaration]
[discrete]
===== Type checking

${rulegroup: Decl_ok/externFunctionDeclaration}
${ruleprose: Decl_ok/externFunctionDeclaration}

[#sec-sem-Decl_inst-externFunctionDeclarationIR]
[discrete]
===== Compile-time evaluation

${rulegroup: Decl_inst/externFunctionDeclarationIR}
${ruleprose: Decl_inst/externFunctionDeclarationIR}

[#sec-externObjectDeclaration]
==== Extern object declaration

${syntax: externObjectDeclaration
          externObjectDeclarationIR}

[#sec-sem-Decl_ok-externObjectDeclaration]
[discrete]
===== Type checking

${rulegroup: Decl_ok/externObjectDeclaration}
${ruleprose: Decl_ok/externObjectDeclaration}

[#sec-sem-Decl_inst-externObjectDeclarationIR]
[discrete]
===== Compile-time evaluation

${rulegroup: Decl_inst/externObjectDeclarationIR}
${ruleprose: Decl_inst/externObjectDeclarationIR}
