[#sec-extern-declaration]
=== Extern declarations

// Section 7.2.11 of the P4-16 Language Specification
P4 supports extern object declarations and extern function declarations using
the following syntax.

// Added
${syntax: externDeclaration}

[#sec-extern-function-declaration]
==== Extern function declarations

// Added
An extern function declaration introduces an extern function.

// Added
${syntax: externFunctionDeclaration}

// Added
After type checking, an extern function declaration is represented in P4~IR~
as:

// Added
${syntax: externFunctionDeclarationIR}

// Added
See <<sec-extern-function>> for how extern functions are internally
represented.

// Added
[discrete]
====== § Type checking extern function declarations

// Added
${rulegroup-source: Decl_ok/externFunctionDeclaration}
${rulegroup-prose: Decl_ok/externFunctionDeclaration}

// Added
[discrete]
====== § Compile-time evaluation of extern function declarations

// Added
At comile-time, extern function declarations are loaded into the context by:

// Added
${rulegroup-source: Decl_inst/externFunctionDeclarationIR}
${rulegroup-prose: Decl_inst/externFunctionDeclarationIR}

[#sec-extern-object-declaration]
==== Extern object declarations

// Added
An extern object declaration introduces an extern object.

// Added
${syntax: externObjectDeclaration}

// Added
After type checking, an extern object declaration is represented in P4~IR~
as:

// Added
${syntax: externObjectDeclarationIR}

// Added
See <<sec-extern-object>> for how extern objects are internally
represented.

// Added
[discrete]
====== § Type checking extern object declarations

// Added
${rulegroup-source: Decl_ok/externObjectDeclaration}
${rulegroup-prose: Decl_ok/externObjectDeclaration}

// Added
[discrete]
====== § Compile-time evaluation of extern object declarations

// Added
At comile-time, extern function declarations are loaded into the context by:

// Added
${rulegroup-source: Decl_inst/externObjectDeclarationIR}
${rulegroup-prose: Decl_inst/externObjectDeclarationIR}
