[#sec-externDeclaration]
=== Extern declaration

${syntax: externDeclaration
          externDeclarationIR}

[#sec-externFunctionDeclaration]
==== Extern function declaration

${syntax: externFunctionDeclaration
          externFunctionDeclarationIR}

[#sec-sem-Decl_ok-externFunctionDeclaration]
[discrete]
===== Type checking

${rulegroup-source: Decl_ok/externFunctionDeclaration}
${rulegroup-prose: Decl_ok/externFunctionDeclaration}

[#sec-sem-Decl_inst-externFunctionDeclarationIR]
[discrete]
===== Compile-time evaluation

${rulegroup-source: Decl_inst/externFunctionDeclarationIR}
${rulegroup-prose: Decl_inst/externFunctionDeclarationIR}

[#sec-extern-object-declaration]
==== Extern object declaration

${syntax: externObjectDeclaration
          externObjectDeclarationIR}

[#sec-sem-Decl_ok-externObjectDeclaration]
[discrete]
===== Type checking

${rulegroup-source: Decl_ok/externObjectDeclaration}
${rulegroup-prose: Decl_ok/externObjectDeclaration}

[#sec-sem-Decl_inst-externObjectDeclarationIR]
[discrete]
===== Compile-time evaluation

${rulegroup-source: Decl_inst/externObjectDeclarationIR}
${rulegroup-prose: Decl_inst/externObjectDeclarationIR}
