[#sec-parserDeclaration]
=== Parser declaration

A parser declaration comprises a name, a list of parameters, an optional list
of constructor parameters, local elements, and parser states (as well as
optional annotations).

${syntax: parserDeclaration
          parserDeclarationIR}

Unlike parser type declarations, parser declarations may not be
generic---e.g., the following declaration is illegal:

[source,p4]
----
parser P<H>(inout H data) { /* body omitted */ }
----

At least one state, named `start`, must be present in any `parser`. A parser
may not define two states with the same name. It is also illegal for a parser
to give explicit definitions for the `accept` and `reject` states---those
states are logically distinct from the states defined by the programmer.

State declarations are described below. Preceding the parser states, a `parser`
may also contain a list of local elements. These can be constants, variables,
or instantiations of objects that may be used within the parser. Such objects
may be instantiations of `extern` objects, or other ``parser``s that may be
invoked as subroutines. However, it is illegal to instantiate a `control` block
within a `parser`.

The states and local elements are all in the same namespace, thus the following
example will produce an error:

[source,p4]
----
// erroneous example
parser p() {
    bit<4> t;
    state start {
       t = 1;
       transition t;
    }
    state t {  // error: name t is duplicated
       transition accept;
    }
}
----

[#sec-sem-Decl_ok-parserDeclaration]
==== Type checking

${rulegroup: Decl_ok/parserDeclaration}
${ruleprose: Decl_ok/parserDeclaration}

[#sec-sem-Decl_inst-parserDeclarationIR]
==== Compile-time evaluation

${rulegroup: Decl_inst/parserDeclarationIR}
${ruleprose: Decl_inst/parserDeclarationIR}
