[#sec-enum-type-declaration]
=== Enum type declaration

An enumeration type is defined using the following syntax:

${syntax: enumTypeDeclaration}

After type checking, enum type declarations are represented as follows:

${syntax: enumTypeDeclarationIR}

See <<sec-enum>> for more details on enums.

[#sec-enum-type-declaration-serializable]
==== Enum type declarations without an underyling type

===== Type checking

${rulegroup-source: Decl_ok/enumTypeDeclaration-non-serializable}
${rulegroup-prose: Decl_ok/enumTypeDeclaration-non-serializable}

===== Compile-time evaluation

At compile-time, enum type declarations are loaded into the context by:

${rulegroup-source: Decl_inst/enumTypeDeclarationIR-non-serializable}
${rulegroup-prose: Decl_inst/enumTypeDeclarationIR-non-serializable}

[#sec-enum-type-declaration-non-serializable]
==== Enum type declarations with an underlying type

===== Type checking

${rulegroup-source: Decl_ok/enumTypeDeclaration-serializable}
${rulegroup-prose: Decl_ok/enumTypeDeclaration-serializable}

An enum field is type-checked as follows:

${relation-title-source: Enum_serializable_field_ok}
${relation-title-prose: Enum_serializable_field_ok}

${rulegroup-source: Enum_serializable_field_ok}
${rulegroup-prose: Enum_serializable_field_ok}

A list of enum fields is type-checked with the following relation:

${relation-title-source: Enum_serializable_fieldList_ok}
${relation-title-prose: Enum_serializable_fieldList_ok}

===== Compile-time evaluation

At compile-time, enum type declarations are loaded into the context by:

${rulegroup-source: Decl_inst/enumTypeDeclarationIR-serializable}
${rulegroup-prose: Decl_inst/enumTypeDeclarationIR-serializable}

An enum field is loaded as follows:

${relation-title-source: Enum_serializable_field_inst}
${relation-title-prose: Enum_serializable_field_inst}

${rulegroup-source: Enum_serializable_field_inst}
${rulegroup-prose: Enum_serializable_field_inst}

A list of enum fields is loaded with the following relation:

${relation-title-source: Enum_serializable_fields_inst}
${relation-title-prose: Enum_serializable_fields_inst}
