[#sec-typeDeclaration]
=== Type declaration

${syntax: derivedTypeDeclaration
          typedefDeclaration
          typeDeclaration
          derivedTypeDeclarationIR
          typedefDeclarationIR
          typeDeclarationIR}

[#sec-enum-type-declaration]
==== Enum type declaration

An enumeration type is defined using the following syntax:

${syntax: enumTypeDeclaration
          enumTypeDeclarationIR}

[#sec-enumTypeDeclaration-non-serializable]
===== Simple enum type declarations

====== Type checking

${rulegroup-source: Decl_ok/enumTypeDeclaration-non-serializable}
${rulegroup-prose: Decl_ok/enumTypeDeclaration-non-serializable}

====== Compile-time evaluation

${rulegroup-source: Decl_inst/enumTypeDeclarationIR-non-serializable}
${rulegroup-prose: Decl_inst/enumTypeDeclarationIR-non-serializable}

[#sec-enumTypeDeclaration-serializable]
===== Serializable enum type declarations

====== Type checking

${rulegroup-source: Enum_serializable_field_ok}
${rulegroup-prose: Enum_serializable_field_ok}

${rulegroup-source: Decl_ok/enumTypeDeclaration-serializable}
${rulegroup-prose: Decl_ok/enumTypeDeclaration-serializable}

====== Compile-time evaluation

${rulegroup-source: Decl_inst/enumTypeDeclarationIR-serializable}
${rulegroup-prose: Decl_inst/enumTypeDeclarationIR-serializable}

[#sec-struct-type-declaration]
==== Struct type declaration

===== Type checking

${rulegroup-source: Decl_ok/structTypeDeclaration}
${rulegroup-prose: Decl_ok/structTypeDeclaration}

===== Compile-time evaluation

${rulegroup-source: Decl_inst/structTypeDeclarationIR}
${rulegroup-prose: Decl_inst/structTypeDeclarationIR}

[#sec-header-type-declaration]
==== Header type declaration

===== Type checking

${rulegroup-source: Decl_ok/headerTypeDeclaration}
${rulegroup-prose: Decl_ok/headerTypeDeclaration}

===== Compile-time evaluation

${rulegroup-source: Decl_inst/headerTypeDeclarationIR}
${rulegroup-prose: Decl_inst/headerTypeDeclarationIR}

[#sec-header-union-type-declaration]
==== Header union type declaration

===== Type checking

${rulegroup-source: Decl_ok/headerUnionTypeDeclaration}
${rulegroup-prose: Decl_ok/headerUnionTypeDeclaration}

===== Compile-time evaluation

${rulegroup-source: Decl_inst/headerUnionTypeDeclarationIR}
${rulegroup-prose: Decl_inst/headerUnionTypeDeclarationIR}

==== Typedef declaration

${syntax: typedef
          typedefDeclaration
          typedefIR
          typedefDeclarationIR}

[#sec-typdef-declaration]
===== `typedef` declaration

====== Type checking

${rulegroup-source: Decl_ok/typedefDeclaration-typedef}
${rulegroup-prose: Decl_ok/typedefDeclaration-typedef}

====== Compile-time evaluation

${rulegroup-source: Decl_inst/typedefDeclarationIR-typedef}
${rulegroup-prose: Decl_inst/typedefDeclarationIR-typedef}

[#sec-newtype-declaration]
===== New type declaration

====== Type checking

${rulegroup-source: Decl_ok/typedefDeclaration-newtype}
${rulegroup-prose: Decl_ok/typedefDeclaration-newtype}

====== Compile-time evaluation

${rulegroup-source: Decl_inst/typedefDeclarationIR-newtype}
${rulegroup-prose: Decl_inst/typedefDeclarationIR-newtype}

[#sec-parser-type-declaration]
==== Parser type declaration

===== Type checking

${rulegroup-source: Decl_ok/parserTypeDeclaration}
${rulegroup-prose: Decl_ok/parserTypeDeclaration}

===== Compile-time evaluation

${rulegroup-source: Decl_inst/parserTypeDeclarationIR}
${rulegroup-prose: Decl_inst/parserTypeDeclarationIR}

[#sec-control-type-declaration]
==== Control type declaration

===== Type checking

${rulegroup-source: Decl_ok/controlTypeDeclaration}
${rulegroup-prose: Decl_ok/controlTypeDeclaration}

===== Compile-time evaluation

${rulegroup-source: Decl_inst/controlTypeDeclarationIR}
${rulegroup-prose: Decl_inst/controlTypeDeclarationIR}

[#sec-package-type-declaration]
==== Package type declaration

===== Type checking

${rulegroup-source: Decl_ok/packageTypeDeclaration}
${rulegroup-prose: Decl_ok/packageTypeDeclaration}

===== Compile-time evaluation

${rulegroup-source: Decl_inst/packageTypeDeclarationIR}
${rulegroup-prose: Decl_inst/packageTypeDeclarationIR}
