=== Typedef declaration

A `typedef` or `type` declaration introduces an alias for an existing type.

${syntax: typedef typedefDeclaration}

In P4~IR~, `typedef` and `type` declarations are represented as:

${syntax: typedefIR typedefDeclarationIR}

[#sec-typedef-declaration]
==== `typedef` declaration

See <<sec-typedef>> for more details about `typedef` aliases.

===== Type checking

${rulegroup-source: Decl_ok/typedefDeclaration-typedef}
${rulegroup-prose: Decl_ok/typedefDeclaration-typedef}

===== Compile-time evaluation

At compile-time, ``typedef``s are loaded into the context with:

${rulegroup-source: Decl_inst/typedefDeclarationIR-typedef}
${rulegroup-prose: Decl_inst/typedefDeclarationIR-typedef}

[#sec-newtype-declaration]
==== New type declaration

See <<sec-newtype>> for more details about new type aliases.

===== Type checking

${rulegroup-source: Decl_ok/typedefDeclaration-newtype}
${rulegroup-prose: Decl_ok/typedefDeclaration-newtype}

===== Compile-time evaluation

At compile-time, ``type``s are loaded into the context with:

${rulegroup-source: Decl_inst/typedefDeclarationIR-newtype}
${rulegroup-prose: Decl_inst/typedefDeclarationIR-newtype}
