[#sec-parser-local-declaration]
=== Parser local declarations

Parser local declarations are defined as follows:

${syntax: parserLocalDeclaration parserLocalDeclarationList}

==== Semantics of parser local declarations

===== Type checking

// Added
${relation-title-latex: ParserLocalDecl_ok}
${relation-title-prose: ParserLocalDecl_ok}
${rulegroup-dispatch-prose: ParserLocalDecl_ok}

// Added
After type checking, parser local declarations are represented in P4~IR~ as
follows:

// Added
${syntax: parserLocalDeclarationIR}

// Added
A list of parser local declarations is type checked by:

// Added
${relation-title-latex: ParserLocalDeclList_ok}
${relation-title-prose: ParserLocalDeclList_ok}

// Added
${rulegroup-latex: ParserLocalDeclList_ok}
${rulegroup-prose: ParserLocalDeclList_ok}

// Added
${relation-title-latex: ParserLocalDecls_ok}
${relation-title-prose: ParserLocalDecls_ok}

// Added
${rulegroup-latex: ParserLocalDecls_ok}
${rulegroup-prose: ParserLocalDecls_ok}

===== Compile-time evaluation

// Added
${relation-title-latex: ParserLocalDecl_inst}
${relation-title-prose: ParserLocalDecl_inst}
${rulegroup-dispatch-prose: ParserLocalDecl_inst}

// Added
A list of parser local declarations is compile-time evaluated by:

// Added
${relation-title-latex: ParserLocalDecls_inst}
${relation-title-prose: ParserLocalDecls_inst}

// Added
${rulegroup-latex: ParserLocalDecls_inst}
${rulegroup-prose: ParserLocalDecls_inst}

===== Runtime evaluation

// Added
${relation-title-latex: ParserLocalDecl_eval}
${relation-title-prose: ParserLocalDecl_eval}
${rulegroup-dispatch-prose: ParserLocalDecl_eval}

// Added
Evaluation of a parser local declaration yields:

${syntax: parserDeclarationResult parserStatementResult
          continueEmptyResult rejectTransitionResult}

// Added
A list of parser local declarations is runtime evaluated by:

// Added
${relation-title-latex: ParserLocalDecls_eval}
${relation-title-prose: ParserLocalDecls_eval}

// Added
${rulegroup-latex: ParserLocalDecls_eval}
${rulegroup-prose: ParserLocalDecls_eval}

// Added
The subsequent sections describe each kind of declaration in detail.

==== Constant declarations

// Added
See <<sec-constant-declaration>> for general information about constant
declarations.

===== Type checking

// Added
${rulegroup-latex: ParserLocalDecl_ok/constantDeclaration}
${rulegroup-prose: ParserLocalDecl_ok/constantDeclaration}

===== Compile-time evaluation

// Added
${rulegroup-latex: ParserLocalDecl_inst/constantDeclarationIR}
${rulegroup-prose: ParserLocalDecl_inst/constantDeclarationIR}

===== Runtime evaluation

// Added
${rulegroup-latex: ParserLocalDecl_eval/constantDeclarationIR}
${rulegroup-prose: ParserLocalDecl_eval/constantDeclarationIR}

==== Instantiations

// Added
See <<sec-instantiation-declaration>> for general information about instantiations.

===== Type checking

// Added
${rulegroup-latex: ParserLocalDecl_ok/instantiation}
${rulegroup-prose: ParserLocalDecl_ok/instantiation}

===== Compile-time evaluation

// Added
${rulegroup-latex: ParserLocalDecl_inst/instantiationIR}
${rulegroup-prose: ParserLocalDecl_inst/instantiationIR}

==== Variable declarations

// Added
See <<sec-variable-declaration>> for general information about variable
declarations.

===== Type checking

// Added
${rulegroup-latex: ParserLocalDecl_ok/variableDeclaration}
${rulegroup-prose: ParserLocalDecl_ok/variableDeclaration}

===== Compile-time evaluation

// Added
${rulegroup-latex: ParserLocalDecl_inst/variableDeclarationIR}
${rulegroup-prose: ParserLocalDecl_inst/variableDeclarationIR}

===== Runtime evaluation

// Added
${rulegroup-latex: ParserLocalDecl_eval/variableDeclarationIR}
${rulegroup-prose: ParserLocalDecl_eval/variableDeclarationIR}

[#sec-value-set-declaration]
==== Parser value set declarations

// Added
Parser value sets are declared with the syntax:

// Added
${syntax: valueSetDeclaration valueSetType}

// Added
See <<sec-value-set-object>> for general information about value sets.

===== Type checking

// Added
${rulegroup-latex: ParserLocalDecl_ok/valueSetDeclaration}
${rulegroup-prose: ParserLocalDecl_ok/valueSetDeclaration}

===== Compile-time evaluation

// Added
${rulegroup-latex: ParserLocalDecl_inst/valueSetDeclarationIR}
${rulegroup-prose: ParserLocalDecl_inst/valueSetDeclarationIR}

After compile-time evaluation, parser value set declarations are represented
in P4~IR~ as follows:

${syntax: valueSetDeclarationIR}
