[#sec-callee-resolution]
=== Callee resolution

// Added
Given a call target, type arguments, and arguments, the callee should be
resolved. This is done both during type checking and runtime evaluation.

==== Resolving constructors

// Added
When type checking, constructors are resolved by:

// Added
${relation-title-latex: ConstructorType_ok}
${relation-title-prose: ConstructorType_ok}

// Added
${rulegroup-latex: ConstructorType_ok}
${rulegroup-prose: ConstructorType_ok}

// Added
During compile-time evaluation, constructors are resolved by:

// Added
${relation-title-latex: Constructor_inst}
${relation-title-prose: Constructor_inst}

// Added
${rulegroup-latex: Constructor_inst}
${rulegroup-prose: Constructor_inst}

==== Resolving callables

// Added
When type checking, callables are resolved by:

// Added
${relation-title-latex: CallableType_ok}
${relation-title-prose: CallableType_ok}
${rulegroup-dispatch-prose: CallableType_ok}

// Added
At runtime, callables are resolved to callees by:

// Added
${relation-title-latex: Callee_eval}
${relation-title-prose: Callee_eval}
${rulegroup-dispatch-prose: Callee_eval}

// Added
While resolving callees, `exit;` statements may be encountered. Thus, the
result of callee resolution is:

// Added
${syntax: calleeResult callee actionCallee functionCallee methodCallee}

// Added
The following subsections describe the two phases, for each kind of callable.

===== Actions

// Added
During type checking, actions are resolved by:

// Added
${syntax: actionTypeIR}

// Added
${rulegroup-latex: CallableType_ok/actionTypeIR}
${rulegroup-prose: CallableType_ok/actionTypeIR}

// Added
During runtime evaluation, actions are resolved by:

// Added
${syntax: actionCallee}

// Added
${rulegroup-latex: Callee_eval/actionCallee}
${rulegroup-prose: Callee_eval/actionCallee}

===== Functions

// Added
During type checking, functions are resolved by:

// Added
${syntax: functionTypeIR definedFunctionTypeIR externFunctionTypeIR}

// Added
${rulegroup-latex: CallableType_ok/functionTypeIR}
${rulegroup-prose: CallableType_ok/functionTypeIR}

// Added
During runtime evaluation, functions are resolved by:

// Added
${syntax: functionCallee definedFunctionCallee externFunctionCallee}

// Added
For extern functions,

// Added
${rulegroup-latex: Callee_eval/externFunctionCallee}
${rulegroup-prose: Callee_eval/externFunctionCallee}

// Added
For user-defined functions,

// Added
${rulegroup-latex: Callee_eval/definedFunctionCallee}
${rulegroup-prose: Callee_eval/definedFunctionCallee}

===== Built-in methods

// Added
During type checking, built-in methods are resolved as:

// Added
${syntax: builtinMethodTypeIR}

// Added
And during runtime evaluation, built-in methods are resolved as:

// Added
${syntax: builtinMethodCallee}

====== `minSizeInBits`, `maxSizeInBits`, `minSizeInBytes`, and `maxSizeInBytes`

// Added
During type checking,

// Added
${rulegroup-latex: CallableType_ok/builtinMethodTypeIR-size}
${rulegroup-prose: CallableType_ok/builtinMethodTypeIR-size}

// Added
During runtime evaluation,

// Added
${rulegroup-latex: Callee_eval/builtinSizeMethodCallee}
${rulegroup-prose: Callee_eval/builtinSizeMethodCallee}

====== `push_front` and `pop_front` on header stacks

// Added
During type checking,

// Added
${rulegroup-latex: CallableType_ok/builtinMethodTypeIR-header-stack-push-front}
${rulegroup-prose: CallableType_ok/builtinMethodTypeIR-header-stack-push-front}

// Added
${rulegroup-latex: CallableType_ok/builtinMethodTypeIR-header-stack-pop-front}
${rulegroup-prose: CallableType_ok/builtinMethodTypeIR-header-stack-pop-front}

// Added
During runtime evaluation,

// Added
${rulegroup-latex: Callee_eval/builtinPushFrontMethodCallee}
${rulegroup-prose: Callee_eval/builtinPushFrontMethodCallee}

// Added
${rulegroup-latex: Callee_eval/builtinPopFrontMethodCallee}
${rulegroup-prose: Callee_eval/builtinPopFrontMethodCallee}

====== `isValid`, `setValid`, and `setInvalid` on headers and header unions

// Added
During type checking,

// Added
${rulegroup-latex: CallableType_ok/builtinMethodTypeIR-header}
${rulegroup-prose: CallableType_ok/builtinMethodTypeIR-header}

// Added
${rulegroup-latex: CallableType_ok/builtinMethodTypeIR-header-union}
${rulegroup-prose: CallableType_ok/builtinMethodTypeIR-header-union}

// Added
During runtime evaluation,

// Added
${rulegroup-latex: Callee_eval/builtinIsValidMethodCallee}
${rulegroup-prose: Callee_eval/builtinIsValidMethodCallee}

// Added
${rulegroup-latex: Callee_eval/builtinSetValidMethodCallee}
${rulegroup-prose: Callee_eval/builtinSetValidMethodCallee}

// Added
${rulegroup-latex: Callee_eval/builtinSetInvalidMethodCallee}
${rulegroup-prose: Callee_eval/builtinSetInvalidMethodCallee}

===== Extern methods

// Added
During type checking, extern methods are resolved by:

// Added
${syntax: externMethodTypeIR}

// Added
${rulegroup-latex: CallableType_ok/externMethodTypeIR}
${rulegroup-prose: CallableType_ok/externMethodTypeIR}

// Added
During runtime evaluation, extern methods are resolved by:

// Added
${syntax: externMethodCallee}

// Added
${rulegroup-latex: Callee_eval/externMethodCallee}
${rulegroup-prose: Callee_eval/externMethodCallee}

===== Parser apply methods

// Added
During type checking, parser apply methods are resolved by:

// Added
${syntax: parserApplyMethodTypeIR}

// Added
${rulegroup-latex: CallableType_ok/parserApplyMethodTypeIR}
${rulegroup-prose: CallableType_ok/parserApplyMethodTypeIR}

// Added
During runtime evaluation, parser apply methods are resolved by:

// Added
${syntax: parserApplyMethodCallee}

// Added
${rulegroup-latex: Callee_eval/parserApplyMethodCallee}
${rulegroup-prose: Callee_eval/parserApplyMethodCallee}

===== Control apply methods

// Added
During type checking, control apply methods are resolved by:

// Added
${syntax: controlApplyMethodTypeIR}

// Added
${rulegroup-latex: CallableType_ok/controlApplyMethodTypeIR}
${rulegroup-prose: CallableType_ok/controlApplyMethodTypeIR}

// Added
During runtime evaluation, control apply methods are resolved by:

// Added
${syntax: controlApplyMethodCallee}

// Added
${rulegroup-latex: Callee_eval/controlApplyMethodCallee}
${rulegroup-prose: Callee_eval/controlApplyMethodCallee}

===== Table apply methods

// Added
During type checking, table apply methods are resolved by:

// Added
${syntax: tableApplyMethodTypeIR}

// Added
${rulegroup-latex: CallableType_ok/tableApplyMethodTypeIR}
${rulegroup-prose: CallableType_ok/tableApplyMethodTypeIR}

// Added
During runtime evaluation, table apply methods are resolved by:

// Added
${syntax: tableApplyMethodCallee}

// Added
${rulegroup-latex: Callee_eval/tableApplyMethodCallee}
${rulegroup-prose: Callee_eval/tableApplyMethodCallee}

===== Parenthesized callables

// Added
During type checking, parenthesized callables are resolved by:

// Added
${rulegroup-latex: CallableType_ok/parenthesized}
${rulegroup-prose: CallableType_ok/parenthesized}

// Added
During runtime evaluation, parenthesized callables are resolved by:

// Added
${rulegroup-latex: Callee_eval/parenthesized}
${rulegroup-prose: Callee_eval/parenthesized}
