=== Constructor calls

// Added
Constructor calls are type checked as follows:

// Added
${relation-title-latex: Inst_ok}
${relation-title-prose: Inst_ok}

// Added
${rulegroup-latex: Inst_ok}
${rulegroup-prose: Inst_ok}

// Added
At compile-time, constructor calls are evaluated as follows:

// Added
${relation-title-latex: Constructor_call}
${relation-title-prose: Constructor_call}
${rulegroup-dispatch-prose: Constructor_call}

==== Extern objects

// Added
${rulegroup-latex: Constructor_call/externConstructorDef}
${rulegroup-prose: Constructor_call/externConstructorDef}

==== Parser objects

// Added
${rulegroup-latex: Constructor_call/parserConstructorDef}
${rulegroup-prose: Constructor_call/parserConstructorDef}

==== Control objects

// Added
${rulegroup-latex: Constructor_call/controlConstructorDef}
${rulegroup-prose: Constructor_call/controlConstructorDef}

==== Package objects

// Added
${rulegroup-latex: Constructor_call/packageConstructorDef}
${rulegroup-prose: Constructor_call/packageConstructorDef}
