=== Callable calls

// Added
Callable calls are type checked as follows:

// Added
${relation-title-latex: Call_ok}
${relation-title-prose: Call_ok}
${rulegroup-dispatch-prose: Call_ok}

// Added
At runtime, callable callees are evaluated as follows:

// Added
${relation-title-latex: Call_eval}
${relation-title-prose: Call_eval}
${rulegroup-dispatch-prose: Call_eval}

// Added
The following subsections describe the type checking and evaluation of callable
calls for different types of callees.

[#sec-call-action]
==== Actions

===== Type checking

// Added
A call to an action is type checked as follows:

// Added
${rulegroup-latex: Call_ok/actionTypeIR}
${rulegroup-prose: Call_ok/actionTypeIR}

===== Runtime evaluation

// Added
An action call is evaluated as follows:

// Added
${rulegroup-latex: Call_eval/actionCallee}
${rulegroup-prose: Call_eval/actionCallee}

// Added
An action body is evaluated as follows:

// Added
${relation-title-latex: ActionBody_eval}
${relation-title-prose: ActionBody_eval}

// Added
The result of evaluating an action body is either an `exit` or a `return`.

// Added
${syntax: actionResult}

// Added
${rulegroup-latex: ActionBody_eval}
${rulegroup-prose: ActionBody_eval}

[#sec-call-function]
==== Functions

===== Type checking

// Added
A call to a function is type checked as follows:

// Added
${rulegroup-latex: Call_ok/definedFunctionTypeIR}
${rulegroup-prose: Call_ok/definedFunctionTypeIR}

===== Runtime evaluation

// Added
A function call is evaluated as follows:

// Added
${rulegroup-latex: Call_eval/definedFunctionCallee}
${rulegroup-prose: Call_eval/definedFunctionCallee}

// Added
A function body is evaluated as follows:

// Added
${relation-title-latex: DefinedFunctionBody_eval}
${relation-title-prose: DefinedFunctionBody_eval}

// Added
The result of evaluating an function body is either an `exit` or a `return`.

// Added
${sytnax: definedFunctionResult}

// Added
${rulegroup-latex: DefinedFunctionBody_eval}
${rulegroup-prose: DefinedFunctionBody_eval}

[#sec-call-extern-function]
==== Extern functions

===== Type checking

// Added
A call to an extern function is type checked as follows:

// Added
${rulegroup-latex: Call_ok/externFunctionTypeIR}
${rulegroup-prose: Call_ok/externFunctionTypeIR}

===== Runtime evaluation

// Added
An extern function call is evaluated as follows:

// Added
${rulegroup-latex: Call_eval/externFunctionCallee}
${rulegroup-prose: Call_eval/externFunctionCallee}

[#sec-call-builtin]
==== Built-in methods

===== Type checking

// Added
A call to a built-in method is type checked as follows:

// Added
${rulegroup-latex: Call_ok/builtinMethodTypeIR}
${rulegroup-prose: Call_ok/builtinMethodTypeIR}

===== Runtime evaluation

// Added
A built-in method call is evaluated as follows:

====== `minSizeInBits`, `maxSizeInBits`, `minSizeInBytes`, and `maxSizeInBytes`

// Added
${rulegroup-latex: Call_eval/builtinSizeMethodCallee}
${rulegroup-prose: Call_eval/builtinSizeMethodCallee}

====== `push_front` and `pop_front` on header stacks

// Added
${rulegroup-latex: Call_eval/builtinPushFrontMethodCallee}
${rulegroup-prose: Call_eval/builtinPushFrontMethodCallee}

// Added
${rulegroup-latex: Call_eval/builtinPopFrontMethodCallee}
${rulegroup-prose: Call_eval/builtinPopFrontMethodCallee}

====== `isValid`, `setValid`, and `setInvalid` on headers

// Added
${rulegroup-latex: Call_eval/builtinIsValidMethodCallee-header}
${rulegroup-prose: Call_eval/builtinIsValidMethodCallee-header}

// Added
${rulegroup-latex: Call_eval/builtinSetValidMethodCallee}
${rulegroup-prose: Call_eval/builtinSetValidMethodCallee}

// Added
${rulegroup-latex: Call_eval/builtinSetInvalidMethodCallee}
${rulegroup-prose: Call_eval/builtinSetInvalidMethodCallee}

====== `isValid` on header unions

// Added
${rulegroup-latex: Call_eval/builtinIsValidMethodCallee-header-union}
${rulegroup-prose: Call_eval/builtinIsValidMethodCallee-header-union}

[#sec-call-extern-method]
==== Extern methods

===== Type checking

// Added
A call to an extern method is type checked as follows:

// Added
${rulegroup-latex: Call_ok/externMethodTypeIR}
${rulegroup-prose: Call_ok/externMethodTypeIR}

===== Runtime evaluation

// Added
An extern method call is evaluated as follows:

// Added
${rulegroup-latex: Call_eval/externMethodCallee}
${rulegroup-prose: Call_eval/externMethodCallee}

[#sec-call-parser-apply-method]
==== Parser apply methods

===== Type checking

// Added
A call to a parser apply method is type checked as follows:

// Added
${rulegroup-latex: Call_ok/parserApplyMethodTypeIR}
${rulegroup-prose: Call_ok/parserApplyMethodTypeIR}

===== Runtime evaluation

// Added
A parser apply method call is evaluated as follows:

// Added
${rulegroup-latex: Call_eval/parserApplyMethodCallee}
${rulegroup-prose: Call_eval/parserApplyMethodCallee}

[#sec-call-control-apply]
==== Control apply  methods

===== Type checking

// Added
A call to a control apply method is type checked as follows:

// Added
${rulegroup-latex: Call_ok/controlApplyMethodTypeIR}
${rulegroup-prose: Call_ok/controlApplyMethodTypeIR}

===== Runtime evaluation

// Added
A control apply method call is evaluated as follows:

// Added
${rulegroup-latex: Call_eval/controlApplyMethodCallee}
${rulegroup-prose: Call_eval/controlApplyMethodCallee}

// Added
A control apply method body is evaluated as follows:

// Added
${relation-title-latex: ControlBody_eval}
${relation-title-prose: ControlBody_eval}

// Added
${rulegroup-latex: ControlBody_eval}
${rulegroup-prose: ControlBody_eval}

// Added
The result of evaluating a control body is either an `exit` or a `return`.

// Added
${syntax: controlBodyResult}

[#sec-call-table-apply]
==== Table apply methods

===== Type checking

// Added
A call to a table apply method is type checked as follows:

// Added
${rulegroup-latex: Call_ok/tableApplyMethodTypeIR}
${rulegroup-prose: Call_ok/tableApplyMethodTypeIR}

===== Runtime evaluation

// Added
A table apply method call is evaluated as follows:

// Added
${rulegroup-latex: Call_eval/tableApplyMethodCallee}
${rulegroup-prose: Call_eval/tableApplyMethodCallee}
