=== Constructor calls

// Added
Constructor calls are type checked as follows:

// Added
${relation-title-source: Inst_ok}
${relation-title-prose: Inst_ok}

// Added
${rulegroup-source: Inst_ok}
${rulegroup-prose: Inst_ok}

// Added
At compile-time, constructor calls are evaluated as follows:

// Added
${relation-title-source: Constructor_call}
${relation-title-prose: Constructor_call}
${rulegroup-dispatch-prose: Constructor_call}

// Added
The contexts in which each type may be instantiated are collected in
<<sec-calling-restrictions>>.

==== Extern objects

// Added
${rulegroup-source: Constructor_call/externConstructorDef}
${rulegroup-prose: Constructor_call/externConstructorDef}

==== Parser objects

// Added
${rulegroup-source: Constructor_call/parserConstructorDef}
${rulegroup-prose: Constructor_call/parserConstructorDef}

==== Control objects

// Added
${rulegroup-source: Constructor_call/controlConstructorDef}
${rulegroup-prose: Constructor_call/controlConstructorDef}

==== Package objects

// Added
${rulegroup-source: Constructor_call/packageConstructorDef}
${rulegroup-prose: Constructor_call/packageConstructorDef}
