[#sec-assignmentStatement]
=== Assignment statements

${syntax: assignop
          assignmentStatement
          assignmentStatementIR}

An assignment, written with the `=` sign, first evaluates its left
sub-expression to an l-value, then evaluates its right sub-expression
to a value, and finally copies the value into the l-value. Derived
types (e.g. ``struct``s) are copied recursively, and all components
of ``header``s are copied, including "validity" bits. Assignment is
not defined for `extern` values.

An assignment may also be written with a binary arithmetic or bit manipulation
operator immediately before the `=` sign.  This performs the binary operator on
the old value of the left sub-expression and the right sub-expression and assigns
the result to the l-value.  Thus an assignment like `A += B` is equivalent
to `A = A + B`, except that `A` is only evaluated once.  This means that
any side-effects within this operand (eg, a function call inside an array index
or slice expression) only occur once.  This is not valid
for comparison operators, logical operators, concat, range, or mask operators.

[[sem-type-check-assignmentStatement]]
[discrete]
==== Type checking

${rulegroup: Stmt_ok/assignmentStatement}
${ruleprose: Stmt_ok/assignmentStatement}

[#sec-assignmentStatement-lvalue]
===== L-values

${syntax: lvalue}

${relation: Lvalue_ok}

${rulegroup: Lvalue_ok/referenceExpression-prefixedNonTypeName}
${ruleprose: Lvalue_ok/referenceExpression-prefixedNonTypeName}

${rulegroup: Lvalue_ok/memberAccess}
${ruleprose: Lvalue_ok/memberAccess}

${rulegroup: Lvalue_ok/indexAccess}
${ruleprose: Lvalue_ok/indexAccess}

${rulegroup: Lvalue_ok/sliceAccess}
${ruleprose: Lvalue_ok/sliceAccess}

${rulegroup: Lvalue_ok/parenthesized}
${ruleprose: Lvalue_ok/parenthesized}

[[sem-compile-time-eval-assignmentStatement]]
[discrete]
==== Compile-time evaluation

${rulegroup: Stmt_inst/assignmentStatementIR}
${ruleprose: Stmt_inst/assignmentStatementIR}
