[#sec-blockStatement]
=== Block statements

${syntax: blockElementStatement
          blockStatement
          blockElementStatementIR
          blockStatementIR}

A block statement is denoted by curly braces. It contains a sequence
of statements and declarations, which are executed sequentially. The
declarations (e.g., variables and constants) within a block statement
are only visible within the block.

[discrete]
==== Type checking

${rulegroup-source: Stmt_ok/blockStatement}
${rulegroup-prose: Stmt_ok/blockStatement}

${relation-title-prose: BlockElementStmt_ok}

${rulegroup-source: BlockElementStmt_ok/constantDeclaration}
${rulegroup-prose: BlockElementStmt_ok/constantDeclaration}

${rulegroup-source: BlockElementStmt_ok/variableDeclaration}
${rulegroup-prose: BlockElementStmt_ok/variableDeclaration}

${rulegroup-source: BlockElementStmt_ok/statement}
${rulegroup-prose: BlockElementStmt_ok/statement}

[discrete]
==== Compile-time evaluation

${rulegroup-source: Stmt_inst/blockStatementIR}
${rulegroup-prose: Stmt_inst/blockStatementIR}

${relation-title-prose: BlockElementStmt_inst}

${rulegroup-source: BlockElementStmt_inst/constantDeclarationIR}
${rulegroup-prose: BlockElementStmt_inst/constantDeclarationIR}

${rulegroup-source: BlockElementStmt_inst/variableDeclarationIR}
${rulegroup-prose: BlockElementStmt_inst/variableDeclarationIR}

${rulegroup-source: BlockElementStmt_inst/statementIR}
${rulegroup-prose: BlockElementStmt_inst/statementIR}
