[#sec-conditionalStatement]
=== Conditional statements

${syntax: conditionalStatement
          conditionalStatementIR}

The conditional statement uses standard syntax and semantics familiar from many programming languages.

However, the condition expression in P4 is required to be a Boolean
(and not an integer).

When several `if` statements are nested, the `else` applies to the
innermost `if` statement that does not have an `else` statement.

[#sec-sem-Stmt_ok-conditionalStatement]
[discrete]
==== Type checking

${rulegroup-source: Stmt_ok/conditionalStatement}
${rulegroup-prose: Stmt_ok/conditionalStatement}

[#sec-sem-Stmt_inst-conditionalStatementIR]
[discrete]
==== Compile-time evaluation

${rulegroup-source: Stmt_inst/conditionalStatementIR}
${rulegroup-prose: Stmt_inst/conditionalStatementIR}

[#sec-sem-Stmt_eval-conditionalStatementIR]
[discrete]
==== Dynamic evaluation

${rulegroup-source: Stmt_eval/conditionalStatementIR}
${rulegroup-prose: Stmt_eval/conditionalStatementIR}
