[#sec-def-type]
[#sec-def-typeOrVoid]
[#sec-def-typeIR]
[#sec-def-value]
[#sec-def-Type_ok]
[#sec-def-Type_wf]
== P4 types and values

P4~16~ supports a variety of types and values. This section describes the basic
types and values, as well as the more complex types and values that can be
constructed from them.

The syntax for P4 types is as follows:

${syntax: type
          typeOrVoid}

These types are represented internally in P4~IR~ as follows:

${syntax: typeIR}

`typeIR` is constructed from type checking the surface syntax of P4 types
(`type`) with the following relation:

${relation: Type_ok}

The P4 type system also imposes well-formedness constraints on types, which
enforce additional restrictions on the structure of types, such as type
nesting.

${relation: Type_wf}

The types represent the kinds of values that can be used in P4 programs. The
runtime representation of P4 values is as follows:

${syntax: value}

include::01-base-type-and-value.adoc[]

include::02-named-type.adoc[]

include::03-data-type-and-value.adoc[]

include::04-object-type-and-value.adoc[]

include::05-alias-type.adoc[]

include::06-synthesized-type-and-value.adoc[]

include::07-canonicalization.adoc[]
