[#sec-binary-operation]
=== Binary operations

Binary operations are evaluated with:

${func-latex: bin_op}
${func-prose: bin_op}

[discrete]
====== Addition

${func-latex: bin_plus}
${func-prose: bin_plus}

[discrete]
====== Saturated addition

${func-latex: bin_satplus}
${func-prose: bin_satplus}

[discrete]
====== Subtraction

${func-latex: bin_minus}
${func-prose: bin_minus}

[discrete]
====== Saturated subtraction

${func-latex: bin_satminus}
${func-prose: bin_satminus}

[discrete]
====== Multiplication

${func-latex: bin_mul}
${func-prose: bin_mul}

[discrete]
====== Division

${func-latex: bin_div}
${func-prose: bin_div}

[discrete]
====== Modulus

${func-latex: bin_mod}
${func-prose: bin_mod}

[discrete]
====== Shift left

${func-latex: bin_shl}
${func-prose: bin_shl}

[discrete]
====== Shift right

${func-latex: bin_shr}
${func-prose: bin_shr}

[discrete]
====== Equality and inequality

${func-latex: bin_eq}
${func-prose: bin_eq}

${func-latex: bin_ne}
${func-prose: bin_ne}

[discrete]
====== Comparisons

${func-latex: bin_lt}
${func-prose: bin_lt}

${func-latex: bin_le}
${func-prose: bin_le}

${func-latex: bin_gt}
${func-prose: bin_gt}

${func-latex: bin_ge}
${func-prose: bin_ge}

[discrete]
====== Bitwise

${func-latex: bin_band}
${func-prose: bin_band}

${func-latex: bin_bor}
${func-prose: bin_bor}

${func-latex: bin_bxor}
${func-prose: bin_bxor}
