[#sec-literal-expression]
=== Literal expressions

${syntax: literalExpression
          literalExpressionIR}

[#sec-Boolean-literal-expressions]
==== Boolean literal expressions

${syntax: booleanLiteral}

[discrete]
[[sem-type-check-literalExpression-boolean]]
===== Type checking

${rulegroup: Expr_ok/literalExpression-boolean}
${ruleprose: Expr_ok/literalExpression-boolean}

[discrete]
[[sem-local-compile-time-eval-literalExpression-boolean]]
===== Local compile-time evaluation

${rulegroup: Eval_static/literalExpressionIR-boolean}
${ruleprose: Eval_static/literalExpressionIR-boolean}

[discrete]
[[sem-compile-time-eval-literalExpression-boolean]]
===== Compile-time evaluation

${rulegroup: Expr_inst/literalExpressionIR-boolean}
${ruleprose: Expr_inst/literalExpressionIR-boolean}

[#sec-numeric-literal-expressions]
==== Numeric literal expressions

${syntax: numberLiteral}

[discrete]
[[sem-type-check-literalExpression-number]]
===== Type checking

${rulegroup: Expr_ok/literalExpression-number}
${ruleprose: Expr_ok/literalExpression-number}

[discrete]
[[sem-local-compile-time-eval-literalExpression-number]]
===== Local compile-time evaluation

${rulegroup: Eval_static/literalExpressionIR-number}
${ruleprose: Eval_static/literalExpressionIR-number}

[discrete]
[[sem-compile-time-eval-literalExpression-number]]
===== Compile-time evaluation

${rulegroup: Expr_inst/literalExpressionIR-number}
${ruleprose: Expr_inst/literalExpressionIR-number}

[#sec-string-literal-expressions]
==== String literal expressions

${syntax: stringLiteral}

[discrete]
[[sem-type-check-literalExpression-stringLiteral]]
===== Type checking

${rulegroup: Expr_ok/literalExpression-stringLiteral}
${ruleprose: Expr_ok/literalExpression-stringLiteral}

[discrete]
[[sem-local-compile-time-eval-literalExpression-stringLiteral]]
===== Local compile-time evaluation

${rulegroup: Eval_static/literalExpressionIR-stringLiteral}
${ruleprose: Eval_static/literalExpressionIR-stringLiteral}

[discrete]
[[sem-compile-time-eval-literalExpression-stringLiteral]]
===== Compile-time evaluation

${rulegroup: Expr_inst/literalExpressionIR-stringLiteral}
${ruleprose: Expr_inst/literalExpressionIR-stringLiteral}
