[#sec-dataExpression]
=== Data expressions

${syntax: dataElementExpression
          dataExpression
          dataExpressionIR}

[#sec-invalid-header-dataExpression]
==== Invalid header expressions

[discrete]
[[sem-type-check-dataExpression-invalid]]
===== Type checking

${rulegroup: Expr_ok/dataExpression-invalid}
${ruleprose: Expr_ok/dataExpression-invalid}

[discrete]
[[sem-local-compile-time-eval-dataExpressionIR-invalid]]
===== Local compile-time evaluation

${rulegroup: Eval_static/dataExpressionIR-invalid}
${ruleprose: Eval_static/dataExpressionIR-invalid}

[discrete]
[[sem-compile-time-eval-dataExpressionIR-invalid]]
===== Compile-time evaluation

${rulegroup: Expr_inst/dataExpressionIR-invalid}
${ruleprose: Expr_inst/dataExpressionIR-invalid}

[#sec-sequence-data-expression]
==== Sequence expressions

${syntax: sequenceElementExpression}

[discrete]
[[sem-type-check-dataExpression-sequence]]
===== Type checking

${rulegroup: Expr_ok/dataExpression-sequence}
${ruleprose: Expr_ok/dataExpression-sequence}

[discrete]
[[sem-local-compile-time-eval-dataExpressionIR-sequence]]
===== Local compile-time evaluation

${rulegroup: Eval_static/dataExpressionIR-sequence}
${ruleprose: Eval_static/dataExpressionIR-sequence}

[discrete]
[[sem-compile-time-eval-dataExpressionIR-sequence]]
===== Compile-time evaluation

${rulegroup: Expr_inst/dataExpressionIR-sequence}
${ruleprose: Expr_inst/dataExpressionIR-sequence}

[#sec-record-data-expression]
==== Record expressions

${syntax: recordElementExpression}

[discrete]
[[sem-type-check-dataExpression-record]]
===== Type checking

${rulegroup: Expr_ok/dataExpression-record}
${ruleprose: Expr_ok/dataExpression-record}

[discrete]
[[sem-local-compile-time-eval-dataExpressionIR-record]]
===== Local compile-time evaluation

${rulegroup: Eval_static/dataExpressionIR-record}
${ruleprose: Eval_static/dataExpressionIR-record}

[discrete]
[[sem-compile-time-eval-dataExpressionIR-record]]
===== Compile-time evaluation

${rulegroup: Expr_inst/dataExpressionIR-record}
${ruleprose: Expr_inst/dataExpressionIR-record}
