[#sec-accessExpression]
=== Access expressions

${syntax: accessExpression
          accessExpressionIR}

[#sec-errorAccessExpression]
==== Error access expressions

${syntax: errorAccessExpression
          errorAccessExpressionIR}

[discrete]
[[sem-type-check-errorAccessExpression]]
===== Type checking

${rulegroup: Expr_ok/errorAccessExpression}
${ruleprose: Expr_ok/errorAccessExpression}

[discrete]
[[sem-local-compile-time-eval-errorAccessExpression]]
===== Local compile-time evaluation

${rulegroup: Eval_static/errorAccessExpressionIR}
${ruleprose: Eval_static/errorAccessExpressionIR}

[discrete]
[[sem-compile-time-eval-errorAccessExpression]]
===== Compile-time evaluation

${rulegroup: Expr_inst/errorAccessExpressionIR}
${ruleprose: Expr_inst/errorAccessExpressionIR}

[#sec-memberAccessExpression]
==== Member access expressions

${syntax: memberAccessBase
          memberAccessExpression
          memberAccessBaseIR
          memberAccessExpressionIR}

[#sec-memberAccessExpression-type]
===== Type accesses

[discrete]
[[sem-type-check-memberAccessExpression-type]]
===== Type checking

${rulegroup: Expr_ok/memberAccessExpression-type}
${ruleprose: Expr_ok/memberAccessExpression-type}

[discrete]
[[sem-local-compile-time-eval-memberAccessExpression-type]]
===== Local compile-time evaluation

${rulegroup: Eval_static/memberAccessExpressionIR-type}
${ruleprose: Eval_static/memberAccessExpressionIR-type}

[discrete]
[[sem-compile-time-eval-memberAccessExpression-type]]
===== Compile-time evaluation

${rulegroup: Expr_inst/memberAccessExpressionIR-type}
${ruleprose: Expr_inst/memberAccessExpressionIR-type}

[#sec-memberAccessExpression-expression]
===== Field accesses

[discrete]
[[sem-expression-check-memberAccessExpression-expression]]
===== expression checking

${rulegroup: Expr_ok/memberAccessExpression-expression}
${ruleprose: Expr_ok/memberAccessExpression-expression}

[discrete]
[[sem-local-compile-time-eval-memberAccessExpression-expression]]
===== Local compile-time evaluation

${rulegroup: Eval_static/memberAccessExpressionIR-expression-stack-size}
${ruleprose: Eval_static/memberAccessExpressionIR-expression-stack-size}

[discrete]
[[sem-compile-time-eval-memberAccessExpression-expression]]
===== Compile-time evaluation

${rulegroup: Expr_inst/memberAccessExpressionIR-expression-stack-size}
${ruleprose: Expr_inst/memberAccessExpressionIR-expression-stack-size}

[#sec-indexAccessExpression]
==== Index access expressions

${syntax: indexAccessExpression
          indexAccessExpressionIR}

[discrete]
[[sem-type-check-indexAccessExpression]]
===== Type checking

${rulegroup: Expr_ok/indexAccessExpression}
${ruleprose: Expr_ok/indexAccessExpression}

[#sec-sliceAccessExpression]
==== Bitslice access expressions

${syntax: sliceAccessExpression
          sliceAccessExpressionIR}

[discrete]
[[sem-type-check-sliceAccessExpression]]
===== Type checking

${rulegroup: Expr_ok/sliceAccessExpression}
${ruleprose: Expr_ok/sliceAccessExpression}

[discrete]
[[sem-local-compile-time-eval-sliceAccessExpression]]
===== Local compile-time evaluation

${rulegroup: Eval_static/sliceAccessExpressionIR}
${ruleprose: Eval_static/sliceAccessExpressionIR}

[discrete]
[[sem-compile-time-eval-sliceAccessExpression]]
===== Compile-time evaluation

${rulegroup: Expr_inst/sliceAccessExpressionIR}
${ruleprose: Expr_inst/sliceAccessExpressionIR}
