[#sec-accessExpression]
=== Access expressions

${syntax: accessExpression
          accessExpressionIR}

[#sec-accessExpression-error]
==== Error access expressions

${syntax: errorAccessExpression
          errorAccessExpressionIR}

[discrete]
[[sem-type-check-accessExpression-error]]
===== Type checking

${rulegroup: Expr_ok/accessExpression-error}
${ruleprose: Expr_ok/accessExpression-error}

[discrete]
[[sem-local-compile-time-eval-accessExpression-error]]
===== Local compile-time evaluation

${rulegroup: Eval_static/accessExpressionIR-error}
${ruleprose: Eval_static/accessExpressionIR-error}

[discrete]
[[sem-compile-time-eval-accessExpression-error]]
===== Compile-time evaluation

${rulegroup: Expr_inst/accessExpressionIR-error}
${ruleprose: Expr_inst/accessExpressionIR-error}

[#sec-accessExpression-member]
==== Member access expressions

${syntax: memberAccessBase
          memberAccessExpression
          memberAccessBaseIR
          memberAccessExpressionIR}

[#sec-accessExpression-member-type]
===== Type accesses

[discrete]
[[sem-type-check-accessExpression-member-type]]
===== Type checking

${rulegroup: Expr_ok/accessExpression-member-type}
${ruleprose: Expr_ok/accessExpression-member-type}

[discrete]
[[sem-local-compile-time-eval-accessExpression-member-type]]
===== Local compile-time evaluation

${rulegroup: Eval_static/accessExpressionIR-member-type}
${ruleprose: Eval_static/accessExpressionIR-member-type}

[discrete]
[[sem-compile-time-eval-accessExpression-member-type]]
===== Compile-time evaluation

${rulegroup: Expr_inst/accessExpressionIR-member-type}
${ruleprose: Expr_inst/accessExpressionIR-member-type}

[#sec-accessExpression-member-expression]
===== Field accesses

[discrete]
[[sem-expression-check-accessExpression-member-expression]]
===== expression checking

${rulegroup: Expr_ok/accessExpression-member-expression}
${ruleprose: Expr_ok/accessExpression-member-expression}

[discrete]
[[sem-local-compile-time-eval-accessExpression-member-expression]]
===== Local compile-time evaluation

${rulegroup: Eval_static/accessExpressionIR-member-expression-stack-size}
${ruleprose: Eval_static/accessExpressionIR-member-expression-stack-size}

[discrete]
[[sem-compile-time-eval-accessExpression-member-expression]]
===== Compile-time evaluation

${rulegroup: Expr_inst/accessExpressionIR-member-expression-stack-size}
${ruleprose: Expr_inst/accessExpressionIR-member-expression-stack-size}

[#sec-index-access-expression]
==== Index access expressions

${syntax: indexAccessExpression
          indexAccessExpressionIR}

[#sec-bitslice-access-expression]
==== Bitslice access expressions
