[#sec-callExpression]
=== Call expressions

${syntax: routineTarget
          constructorTarget
          callTarget
          callExpression
          routineTargetIR
          constructorTargetIR
          callExpressionIR}

[#sec-callExpression-routine]
==== Routine call expressions

[discrete]
[[sem-type-check-callExpression-routine]]
===== Type checking

${rulegroup: Expr_ok/callExpression-routine}
${ruleprose: Expr_ok/callExpression-routine}

[discrete]
[[sem-local-compile-time-eval-callExpressionIR-routine]]
===== Local compile-time evaluation

${rulegroup: Eval_static/callExpressionIR-builtin-size}
${ruleprose: Eval_static/callExpressionIR-builtin-size}

[discrete]
[[sem-compile-time-eval-callExpressionIR-routine]]
===== Compile-time evaluation

${rulegroup: Expr_inst/callExpressionIR-builtin-size}
${ruleprose: Expr_inst/callExpressionIR-builtin-size}

[#sec-constructor-call-expressions]
==== Constructor call expressions

[discrete]
[[sem-type-check-callExpression-constructor]]
===== Type checking

${rulegroup: Expr_ok/callExpression-constructor}
${ruleprose: Expr_ok/callExpression-constructor}

[discrete]
[[sem-compile-time-eval-callExpressionIR-constructor]]
===== Compile-time evaluation

${rulegroup: Expr_ok/callExpression-constructor}
${ruleprose: Expr_ok/callExpression-constructor}

[[sem-compile-time-eval-callExpression-parenthesized]]
==== Parenthesized calls

[discrete]
[[sem-local-compile-time-eval-callExpressionIR-parenthesized]]
===== Local compile-time evaluation

${rulegroup: Eval_static/callExpressionIR-parenthesized}
${ruleprose: Eval_static/callExpressionIR-parenthesized}

[discrete]
[[sem-compile-time-eval-callExpressionIR-parenthesized]]
===== Compile-time evaluation

${rulegroup: Expr_inst/callExpressionIR-parenthesized}
${ruleprose: Expr_inst/callExpressionIR-parenthesized}
