(library
 (name interface)
 (libraries core_unix menhirLib util domain xl il sl runtime_dynamic)
 (modules
  source
  context
  extract
  flatten
  wrap
  unwrap
  pack
  unpack
  preprocessor
  lexer
  parse
  parser
  hint
  unparse
  parser_debug
  debug_config))

(ocamllex
 (modules lexer))

(menhir
 (modules parser)
 (flags --explain --table --inspection))
