;; Test configuration for P4-SpecTec

(test
 (name test)
 (preprocess
  (pps ppx_let))
 (modules test)
 (libraries p4spectec core core_kernel core_unix core_unix.command_unix)
 (action
  (progn
   (ignore-outputs
    (diff elab.expected elab.actual))
   (ignore-outputs
    (diff struct.expected struct.actual))
   (ignore-outputs
    (diff prose.expected prose.actual))
   (ignore-outputs
    (diff p4_static_pos_il.expected p4_static_pos_il.actual))
   (ignore-outputs
    (diff p4_static_neg_il.expected p4_static_neg_il.actual))
   (ignore-outputs
    (diff p4_static_pos_sl.expected p4_static_pos_sl.actual))
   (ignore-outputs
    (diff p4_static_neg_sl.expected p4_static_neg_sl.actual))
   (ignore-outputs
    (diff p4_dynamic_v1model_sl.expected p4_dynamic_v1model_sl.actual))
   (ignore-outputs
    (diff p4_dynamic_ebpf_sl.expected p4_dynamic_ebpf_sl.actual))
   (ignore-outputs
    (diff parser_pos.expected parser_pos.actual))
   (ignore-outputs
    (diff parser_neg.expected parser_neg.actual)))))

;; Elaboration and structuring tests for specification language

(rule
 (alias speclang)
 (action
  (progn
   (ignore-outputs
    (diff elab.expected elab.actual))
   (ignore-outputs
    (diff struct.expected struct.actual))
   (ignore-outputs
    (diff prose.expected prose.actual)))))

;; P4 static semantics tests

(rule
 (alias p4static)
 (action
  (progn
   (ignore-outputs
    (diff p4_static_pos_il.expected p4_static_pos_il.actual))
   (ignore-outputs
    (diff p4_static_neg_il.expected p4_static_neg_il.actual))
   (ignore-outputs
    (diff p4_static_pos_sl.expected p4_static_pos_sl.actual))
   (ignore-outputs
    (diff p4_static_pos_sl.expected p4_static_pos_sl.actual)))))

(rule
 (alias p4static-il)
 (action
  (progn
   (ignore-outputs
    (diff p4_static_pos_il.expected p4_static_pos_il.actual))
   (ignore-outputs
    (diff p4_static_neg_il.expected p4_static_neg_il.actual)))))

(rule
 (alias p4static-sl)
 (action
  (progn
   (ignore-outputs
    (diff p4_static_pos_sl.expected p4_static_pos_sl.actual))
   (ignore-outputs
    (diff p4_static_pos_sl.expected p4_static_pos_sl.actual)))))

;; P4 simulation tests

(rule
 (alias p4dynamic)
 (action
  (progn
   (ignore-outputs
    (diff p4_dynamic_v1model_sl.expected p4_dynamic_v1model_sl.actual))
   (ignore-outputs
    (diff p4_dynamic_ebpf_sl.expected p4_dynamic_ebpf_sl.actual)))))

(rule
 (alias p4dynamic-v1model)
 (action
  (progn
   (ignore-outputs
    (diff p4_dynamic_v1model_sl.expected p4_dynamic_v1model_sl.actual)))))

(rule
 (alias p4dynamic-ebpf)
 (action
  (progn
   (ignore-outputs
    (diff p4_dynamic_ebpf_sl.expected p4_dynamic_ebpf_sl.actual)))))

;; P4 parsing tests

(rule
 (alias p4parse)
 (action
  (progn
   (ignore-outputs
    (diff parser_pos.expected parser_pos.actual))
   (ignore-outputs
    (diff parser_neg.expected parser_neg.actual)))))

;; Rules to generate outputs

(rule
 (target elab.actual)
 (action
  (with-stdout-to
   elab.actual
   (with-stderr-to
    elab.err
    (run ./test.exe elab -s ../../../../spec-concrete)))))

(rule
 (target struct.actual)
 (action
  (with-stdout-to
   struct.actual
   (with-stderr-to
    struct.err
    (run ./test.exe struct -s ../../../../spec-concrete)))))

(rule
 (target prose.actual)
 (action
  (with-stdout-to
   prose.actual
   (with-stderr-to
    prose.err
    (run ./test.exe prose -s ../../../../spec-concrete)))))

(rule
 (target p4_static_pos_il.actual)
 (action
  (with-stdout-to
   p4_static_pos_il.actual
   (with-stderr-to
    p4_static_pos_il.err
    (run
     ./test.exe
     run
     -il
     -s
     ../../../../spec-concrete
     -rel
     Program_inst
     -i
     ../../../../p4c/p4include
     -e
     ../../../../excludes/static
     -p4-dir
     ../../../../p4c/testdata/p4_16_samples
     -p4-dir
     ../../../../testdata/custom)))))

(rule
 (target p4_static_neg_il.actual)
 (action
  (with-stdout-to
   p4_static_neg_il.actual
   (with-stderr-to
    p4_static_neg_il.err
    (run
     ./test.exe
     run
     -il
     -s
     ../../../../spec-concrete
     -rel
     Program_ok
     -i
     ../../../../p4c/p4include
     -e
     ../../../../excludes/static
     -p4-dir
     ../../../../p4c/testdata/p4_16_errors
     -neg)))))

(rule
 (target p4_static_pos_sl.actual)
 (action
  (with-stdout-to
   p4_static_pos_sl.actual
   (with-stderr-to
    p4_static_pos_sl.err
    (run
     ./test.exe
     run
     -sl
     -s
     ../../../../spec-concrete
     -rel
     Program_inst
     -i
     ../../../../p4c/p4include
     -e
     ../../../../excludes/static
     -p4-dir
     ../../../../p4c/testdata/p4_16_samples
     -p4-dir
     ../../../../testdata/custom)))))

(rule
 (target p4_static_neg_sl.actual)
 (action
  (with-stdout-to
   p4_static_neg_sl.actual
   (with-stderr-to
    p4_static_neg_sl.err
    (run
     ./test.exe
     run
     -sl
     -s
     ../../../../spec-concrete
     -rel
     Program_ok
     -i
     ../../../../p4c/p4include
     -e
     ../../../../excludes/static
     -p4-dir
     ../../../../p4c/testdata/p4_16_errors
     -neg)))))

(rule
 (target p4_dynamic_v1model_sl.actual)
 (action
  (with-stdout-to
   p4_dynamic_v1model_sl.actual
   (with-stderr-to
    p4_dynamic_v1model_sl.err
    (run
     ./test.exe
     sim
     -sl
     -arch
     v1model
     -s
     ../../../../spec-concrete
     -i
     ../../../../p4c/p4include
     -e
     ../../../../excludes/static
     -e
     ../../../../excludes/dynamic
     -p4-dir
     ../../../../p4c/testdata/p4_16_samples
     -p4-dir
     ../../../../testdata/custom
     -stf-dir
     ../../../../p4c/testdata/p4_16_samples
     -stf-dir
     ../../../../testdata/p4testgen
     -stf-dir
     ../../../../testdata/custom
     -p
     ../../../../patches/v1model)))))

(rule
 (target p4_dynamic_ebpf_sl.actual)
 (action
  (with-stdout-to
   p4_dynamic_ebpf_sl.actual
   (with-stderr-to
    p4_dynamic_ebpf_sl.err
    (run
     ./test.exe
     sim
     -sl
     -arch
     ebpf
     -s
     ../../../../spec-concrete
     -i
     ../../../../p4c/p4include
     -e
     ../../../../excludes/static
     -e
     ../../../../excludes/dynamic
     -p4-dir
     ../../../../p4c/testdata/p4_16_samples
     -p4-dir
     ../../../../testdata/custom
     -stf-dir
     ../../../../p4c/testdata/p4_16_samples
     -stf-dir
     ../../../../testdata/p4testgen
     -stf-dir
     ../../../../testdata/custom
     -p
     ../../../../patches/ebpf)))))

(rule
 (target parser_pos.actual)
 (action
  (with-stdout-to
   parser_pos.actual
   (with-stderr-to
    parser_pos.err
    (run
     ./test.exe
     parser
     -s
     ../../../../spec-concrete
     -i
     ../../../../p4c/p4include
     -p4-dir
     ../../../../p4c/testdata/p4_16_samples
     -p4-dir
     ../../../../testdata/custom)))))

(rule
 (target parser_neg.actual)
 (action
  (with-stdout-to
   parser_neg.actual
   (with-stderr-to
    parser_neg.err
    (run
     ./test.exe
     parser
     -i
     ../../../../p4c/p4include
     -p4-dir
     ../../../../p4c/testdata/p4_16_errors
     -s
     ../../../../spec-concrete)))))
