(* Thin functor shell + top-level program-dispatch entry for generated OCaml.

   The heavy logic lives at module top-level, reading the per-instance
   trampoline [trampoline_cur__]. [Make] builds its own [trampoline__] from
   the [Interface]/[Extern] functor arguments and switches [trampoline_cur__]
   to it across the three dispatch entry points via [with_trampoline]. Towers
   nest correctly because control crosses levels only through [eval_rel] /
   [eval_func] / [eval_program]. *)

(* Top-level program dispatch — reads the current instance's parser. *)
let eval_program =
  {|
let eval_program (relname__ : string) (includes__ : string list)
    (path__ : string) : Run.program_result =
  match (!trampoline_cur__).interface.parse_program includes__ [path__] with
  | Run.Pass value_program -> (
      match eval_rel relname__ [ value_program ] with
      | Run.Pass values_output -> Run.Pass values_output
      | Run.Fail (at, msg) -> Run.Fail (`Runtime (at, msg)))
  | Run.Fail (`Syntax (at, msg)) -> Run.Fail (`Syntax (at, msg))
|}

(* The public functor contract, preserved structurally.

   This is the full content of the thin [interp_ml.ml] shell. The heavy code
   lives in the separate [spec_parts] library ([Spec_parts.Trampoline] /
   [Spec_parts.Dispatch] / [Spec_parts.Part_NNN]); the shell only builds its
   per-instance [trampoline__] and routes the three dispatch entry points
   through [with_trampoline]. [name] selects which compiled part-library to
   reference, so multiple compiled specs can coexist ([Spec_parts] for P4's
   default empty name, [Spec_parts_il]/[Spec_parts_sl] etc. otherwise). *)
let make (name : string) : string =
  let module_name = Split.name_module name in
  Printf.sprintf
    {|(* Generated by p4spectec ocaml — do not edit manually *)
module Run = Runtime.Dynamic_Runner.Signature
open %s.Trampoline

module Make
    (Interface : Run.INTERFACE)
    (Extern : Run.EXTERN)
    () : Run.INTERP_ML = struct

  let trampoline : trampoline__ = {
    interface = {
      call_builtin = Interface.call_builtin;
      parse_program = Interface.parse_program;
    };
    extern = {
      eval_extern_rel = Extern.eval_extern_rel;
      eval_extern_func = Extern.eval_extern_func;
    };
  }

  (* The compiled backend never memoizes; [Cache] satisfies [INTERP_ML] with
     no-ops. *)
  module Cache = struct
    let cache_on () = ()
    let cache_off () = ()
  end

  let init ~cache:_ ~det:_ ~guard:_ () = ()

  let clear () = ()

  let eval_func name__ typs__ args__ =
    with_trampoline trampoline (fun () -> %s.Dispatch.eval_func name__ typs__ args__)
  let eval_rel name__ args__ =
    with_trampoline trampoline (fun () -> %s.Dispatch.eval_rel name__ args__)
  let eval_program relname__ includes__ path__ =
    with_trampoline trampoline (fun () -> %s.Dispatch.eval_program relname__ includes__ path__)
end
|}
    module_name module_name module_name module_name
