(* Thin functor shell + top-level program-dispatch entry for generated OCaml.

   The heavy logic lives at module top-level, reading the per-instance context
   [cur__]. [Make] builds its own [ctx__] from the [Interface]/[Extern] functor
   arguments and switches [cur__] to it across the three dispatch entry points
   via [with_ctx]. Towers nest correctly because control crosses levels only
   through [eval_rel] / [eval_func] / [eval_program]. *)

(* Top-level program dispatch — reads the current instance's parser.
   [tid_program] is the spec's entry syntax type ([p4program] for the P4
   spec, [script] for spec-meta/il and spec-meta/sl), supplied by the caller
   so this template stays agnostic of which spec it is generated for. *)
let eval_program (tid_program : string) =
  Printf.sprintf
    {|
let eval_program (relname__ : string) (includes__ : string list)
    (path__ : string) : Run.program_result =
  match (!cur__).iface.parse_program includes__ [path__] with
  | Run.Pass value_program -> (
      (* The parsed program is a real [Value.t] from the parser, but [eval_rel]
         [Obj.magic]-casts its inputs. So unmarshal it once here into the typed
         [%s], then [Obj.repr] it. *)
      let value_program : Value.t =
        Obj.magic (unmarshal_%s value_program)
      in
      match eval_rel relname__ [ value_program ] with
      | Run.Pass values_output -> Run.Pass values_output
      | Run.Fail (at, msg) -> Run.Fail (`Runtime (at, msg)))
  | Run.Fail (`Syntax (at, msg)) -> Run.Fail (`Syntax (at, msg))
|}
    tid_program tid_program

(* Same conversion [eval_program] does inline for a freshly-parsed program,
   exposed standalone for callers (e.g. [backend-boot/patch.ml]) that already
   hold a [Value.t] built some other way (not via [iface.parse_program]) and
   need it [eval_rel]-ready. *)
let unmarshal_program (tid_program : string) : string =
  Printf.sprintf
    {|
let unmarshal_program (value : Value.t) : Value.t =
  Obj.magic (unmarshal_%s value)
|}
    tid_program

(* The public functor contract, preserved structurally.

   This is the full content of the thin [interp_ml.ml] shell. The heavy code
   lives in the separate [spec_parts_<name>] library ([Spec_parts_<name>.Ctx]
   / [.Dispatch] / [.Part_NNN]); the shell only builds its per-instance
   [ctx__] and routes the four dispatch entry points through [with_ctx].
   [name] selects which compiled part-library to reference, so multiple
   compiled specs can coexist ([Spec_parts_p4], [Spec_parts_il],
   [Spec_parts_sl], ...). *)
let make (name : string) : string =
  let module_name = Split.module_name name in
  Printf.sprintf
    {|(* Generated by p4spectec ocaml — do not edit manually *)
module Run = Runtime.Dynamic_Runner.Signature
open %s.Ctx

module Make
    (Interface : Run.INTERFACE)
    (Extern : Run.EXTERN)
    () : Run.INTERP_ML = struct

  let my_ctx : ctx__ = {
    iface = {
      parse_program = Interface.parse_program;
      call_builtin = Interface.call_builtin;
    };
    extern = {
      eval_extern_rel = Extern.eval_extern_rel;
      eval_extern_func = Extern.eval_extern_func;
    };
  }

  (* The compiled backend never memoizes; [Cache] satisfies [INTERP_ML] with
     no-ops. *)
  module Cache = struct
    let cache_on () = ()
    let cache_off () = ()
  end

  let init ~cache:_ ~det:_ ~guard:_ () = ()

  let clear () = ()

  let eval_func name__ typs__ args__ =
    with_ctx my_ctx (fun () -> %s.Dispatch.eval_func name__ typs__ args__)
  let eval_rel name__ args__ =
    with_ctx my_ctx (fun () -> %s.Dispatch.eval_rel name__ args__)
  let eval_program relname__ includes__ path__ =
    with_ctx my_ctx (fun () -> %s.Dispatch.eval_program relname__ includes__ path__)
  let unmarshal_program value =
    with_ctx my_ctx (fun () -> %s.Dispatch.unmarshal_program value)
end
|}
    module_name module_name module_name module_name module_name
