[#sec-call-convention]
=== Call convention

// Added
Calls in P4 are executed using copy-in/copy-out semantics. For a high-level
description of copy-in/copy-out semantics, see
<<sec-call-convention-overview>>.

==== Type checking

// Added
Calling conventions are checked by the type system with:

// Added
${relation-title-source: Call_convention_ok}
${relation-title-prose: Call_convention_ok}

// Added
${rulegroup-source: Call_convention_ok}
${rulegroup-prose: Call_convention_ok}

// Added
Each argument-parameter pair is checked by:

// Added
${relation-title-source: Call_convention_argument_ok}
${relation-title-prose: Call_convention_argument_ok}

// Added
${rulegroup-source: Call_convention_argument_ok/typedExpression}
${rulegroup-prose: Call_convention_argument_ok/typedExpression}

// Added
${rulegroup-source: Call_convention_argument_ok/nameIR-typedExpression}
${rulegroup-prose: Call_convention_argument_ok/nameIR-typedExpression}

// Added
${rulegroup-source: Call_convention_argument_ok/nameIR-dontcare}
${rulegroup-prose: Call_convention_argument_ok/nameIR-dontcare}

// Added
${rulegroup-source: Call_convention_argument_ok/dontcare}
${rulegroup-prose: Call_convention_argument_ok/dontcare}

// Added
Expression arguments are checked, depending on the parameter's direction:

// Added
${relation-title-source: Call_convention_expr_ok}
${relation-title-prose: Call_convention_expr_ok}

===== `in`

// Added
${rulegroup-source: Call_convention_expr_ok/in}
${rulegroup-prose: Call_convention_expr_ok/in}

===== `out` and `inout`

// Added
${rulegroup-source: Call_convention_expr_ok/out-inout}
${rulegroup-prose: Call_convention_expr_ok/out-inout}

===== Directionless

// Added
${rulegroup-source: Call_convention_expr_ok/empty}
${rulegroup-prose: Call_convention_expr_ok/empty}

==== Runtime evaluation of copy-in

// Added
The copy-in phase of a call is evaluated by:

// Added
${relation-title-source: Copy_in}
${relation-title-prose: Copy_in}

// Added
The result of copy-in evaluation is:

// Added
${syntax: copyInResult}

// Added
${rulegroup-source: Copy_in}
${rulegroup-prose: Copy_in}

// Added
Default arguments are copied in by:

// Added
${relation-title-source: Copy_in_default}
${relation-title-prose: Copy_in_default}

// Added
${rulegroup-source: Copy_in_default}
${rulegroup-prose: Copy_in_default}

// Added
Otherwise, each argument-parameter pair is evaluated by:

// Added
${relation-title-source: Copy_in_argument}
${relation-title-prose: Copy_in_argument}

// Added
Its result is:

// Added
${syntax: copyInArgumentResult}

===== `in` and directionless

// Added
${rulegroup-source: Copy_in_argument/directionless-in}
${rulegroup-prose: Copy_in_argument/directionless-in}

===== `inout`

// Added
${rulegroup-source: Copy_in_argument/inout}
${rulegroup-prose: Copy_in_argument/inout}

===== `out`

// Added
${rulegroup-source: Copy_in_argument/out}
${rulegroup-prose: Copy_in_argument/out}

==== Compile-time evaluation of copy-in

// Added
The copy-in phase of a call is evaluated at compile time by:

// Added
${relation-title-source: Copy_in_inst}
${relation-title-prose: Copy_in_inst}

// Added
${rulegroup-source: Copy_in_inst}
${rulegroup-prose: Copy_in_inst}

// Added
Each argument-parameter pair is evaluated by:

// Added
${relation-title-source: Copy_in_argument_inst}
${relation-title-prose: Copy_in_argument_inst}

// Added
${rulegroup-source: Copy_in_argument_inst}
${rulegroup-prose: Copy_in_argument_inst}

// Added
For default arguments, the argument is copied in by:

// Added
${relation-title-source: Copy_in_inst_default}
${relation-title-prose: Copy_in_inst_default}

// Added
${rulegroup-source: Copy_in_inst_default}
${rulegroup-prose: Copy_in_inst_default}

// Added
${relation-title-source: Copy_in_argument_inst_default}
${relation-title-prose: Copy_in_argument_inst_default}

// Added
${rulegroup-source: Copy_in_argument_inst_default}
${rulegroup-prose: Copy_in_argument_inst_default}

// Added
Copy-out is unnecessary at compile time, because constructors do not have `out`
or `inout` parameters.

==== Runtime evaluation of copy-out

// Added
The copy-out phase of a call is evaluated by:

// Added
${relation-title-source: Copy_out}
${relation-title-prose: Copy_out}

// Added
${rulegroup-source: Copy_out}
${rulegroup-prose: Copy_out}

// Added
It internally invokes:

// Added
${relation-title-source: Copy_out_inner}
${relation-title-prose: Copy_out_inner}

// Added
${rulegroup-source: Copy_out_inner}
${rulegroup-prose: Copy_out_inner}

// Added
Where for each argument-parameter pair:

// Added
${relation-title-source: Copy_out_argument}
${relation-title-prose: Copy_out_argument}

===== `in` and directionless

// Added
${rulegroup-source: Copy_out_argument/in-directionless}
${rulegroup-prose: Copy_out_argument/in-directionless}

===== `out` and `inout`

// Added
${rulegroup-source: Copy_out_argument/out-inout}
${rulegroup-prose: Copy_out_argument/out-inout}
