[#sec-conditional-statement]
=== Conditional statements

// Section 12.6 of the P4-16 Language Specification ----
The conditional statement uses standard syntax and semantics familiar from many
programming languages.

However, the condition expression in P4 is required to be a Boolean
(and not an integer).
// ----

// Added ----
${syntax: conditionalStatement}
// ----

// Section 12.6 of the P4-16 Language Specification ----
When several `if` statements are nested, the `else` applies to the innermost
`if` statement that does not have an `else` statement.
// ----

// Added ----
==== Type checking

After type checking, a conditional statement has the form:

${syntax: conditionalStatementIR}

${rulegroup-source: Stmt_ok/conditionalStatement}
${rulegroup-prose: Stmt_ok/conditionalStatement}

==== Compile-time evaluation

${rulegroup-source: Stmt_inst/conditionalStatementIR}
${rulegroup-prose: Stmt_inst/conditionalStatementIR}

==== Runtime evaluation

${rulegroup-source: Stmt_eval/conditionalStatementIR}
${rulegroup-prose: Stmt_eval/conditionalStatementIR}
// ----
