[#sec-statement]
== Statements

The syntax of statements is defined as follows:

${syntax: statement}

=== Semantics of statements

==== Type checking

${relation-title-source: Stmt_ok}
${relation-title-prose: Stmt_ok}

After type checking, statements are represented in P4~IR~ as follows:

${syntax: statementIR}

In order to statically determine the control flow of a P4 program (e.g.,
whether a function body always returns), the following indicator for abstract
control flow is used:

${syntax: flow}

As a marker of whether a statement is nested inside a loop, the following
indicator is used:

${syntax: loopctxt}

==== Compile-time evaluation

${relation-title-source: Stmt_inst}
${relation-title-prose: Stmt_inst}

Instantiations nested within statements are processed according to the above
relation.

==== Runtime evaluation

${relation-title-source: Stmt_eval}
${relation-title-prose: Stmt_eval}

The result of evaluating a statement is represented as follows:

${syntax: statementResult
          continueEmptyResult
          callResult
          forResult
          abortResult
          returnResult
          exitResult
          rejectTransitionResult}

The subsequent sections describe each kind of statement in detail.

include::01-empty-statement.adoc[]
include::02-assignment-statement.adoc[]
include::03-call-statement.adoc[]
include::04-direct-application-statement.adoc[]
include::05-return-statement.adoc[]
include::06-exit-statement.adoc[]
include::07-block-statement.adoc[]
include::08-conditional-statement.adoc[]
include::09-for-statement.adoc[]
include::10-break-statement.adoc[]
include::11-continue-statement.adoc[]
include::12-switch-statement.adoc[]
