=== Expresssions

An expression is evaluated with the following relation:

${relation-title-prose: Eval_exp}

If no rule was successfully applied, the evaluation fails:

${rulegroup-prose: Eval_exp/fail}

==== Boolean, number, and string literals

${rulegroup-prose: Eval_exp/literal}

==== Variable references

${rulegroup-prose: Eval_exp/variable}

==== Operations

===== Unary expressions

${rulegroup-prose: Eval_exp/unary}

===== Binary expressions

${rulegroup-prose: Eval_exp/binary}

===== Comparison expressions

${rulegroup-prose: Eval_exp/compare}

==== Casts

===== Upcast expressions

${rulegroup-prose: Eval_exp/upcast}

Upcasting is defined as follows:

${func-prose: upcast}

===== Downcast expressions

${func-prose: downcast}

Downcasting is defined as follows:

${rulegroup-prose: Eval_exp/downcast}

==== Runtime type tests

${rulegroup-prose: Eval_exp/subtype}

Runtime type tests are defined as follows:

${func-prose: subtyp}
${func-prose: subtyp'}
${func-prose: subtyps}

==== Match expressions

${rulegroup-prose: Eval_exp/match}

==== Tuple expressions

${rulegroup-prose: Eval_exp/tuple}

==== Case expressions

${rulegroup-prose: Eval_exp/case}

==== Struct expressions

${rulegroup-prose: Eval_exp/struct}

==== Option expressions

${rulegroup-prose: Eval_exp/opt}

==== List expressions

${rulegroup-prose: Eval_exp/list}

==== Concatenation expressions

${rulegroup-prose: Eval_exp/concat}

==== Membership expressions

${rulegroup-prose: Eval_exp/mem}

==== Length expressions

${rulegroup-prose: Eval_exp/len}

==== Accesses

${relation-title-prose: Eval_path}

${rulegroup-prose: Eval_path/root}
${rulegroup-prose: Eval_path/dot}
${rulegroup-prose: Eval_path/idx}
${rulegroup-prose: Eval_path/slice}
${rulegroup-prose: Eval_path/fail}

===== Dot access expressions

${rulegroup-prose: Eval_exp/dot}

===== Index access expressions

${rulegroup-prose: Eval_exp/idx}

===== Slice access expressions

${rulegroup-prose: Eval_exp/slice}

==== Update expressions

${relation-title-prose: Eval_path_upd}

${rulegroup-prose: Eval_path_upd/root}
${rulegroup-prose: Eval_path_upd/dot}
${rulegroup-prose: Eval_path_upd/idx}
${rulegroup-prose: Eval_path_upd/slice}
${rulegroup-prose: Eval_path_upd/fail}

${rulegroup-prose: Eval_exp/upd}

==== Function call expressions

${rulegroup-prose: Eval_exp/call}

==== Iterator expressions

${rulegroup-prose: Eval_exp/iter}
