=== Assignments

This section describes the semantics of assignments in the language. An
assignment occurs when evaluating a let instruction, and when invoking a
function or relation.

==== Assigning a value to an expression

On a let instruction and relation invocation, a value is assigned to an
expression.

${relation-title-prose: Assign_exp}

A sequence of assignments is defined as follows:

${relation-title-prose: Assign_exps}
${rulegroup-prose: Assign_exps}

Only a subset of expressions can be assigned to.

===== Variable references

${rulegroup-prose: Assign_exp/variable}

===== Tuple expressions

${rulegroup-prose: Assign_exp/tuple}

===== Case expressions

${rulegroup-prose: Assign_exp/inj}

===== Struct expressions

${rulegroup-prose: Assign_exp/str}

===== Option expressions

${rulegroup-prose: Assign_exp/opt}

===== List expressions

${rulegroup-prose: Assign_exp/list}

===== Cons expressions

${rulegroup-prose: Assign_exp/cons}

===== Iterator expressions

${rulegroup-prose: Assign_exp/iter}

==== Assigning a value to a function parameter

When invoking a function, the arguments are assigned to the parameters of the
function. This is defined as follows:

${relation-title-prose: Assign_param}

A sequence of parameter assignments is defined as follows:

${relation-title-prose: Assign_params}
${rulegroup-prose: Assign_params}

===== Expression parameters

${rulegroup-prose: Assign_param/exp}

===== Function parameters

${rulegroup-prose: Assign_param/fun}
