=== Functions

An entry point for function calls is the following relation:

${relation-title-prose: Call_func}
${rulegroup-prose: Call_func}

A meta-cache is used for performance reasons.

${relation-title-prose: Call_func_cache}
${rulegroup-prose: Call_func_cache}

The actual function call is performed by the following relation, dispatching
according to the function type:

${relation-title-prose: Call_func_dispatch}
${rulegroup-prose: Call_func_dispatch}

==== Extern functions

${relation-title-prose: Call_extern_func}

==== Built-in functions

${relation-title-prose: Call_builtin_func}

==== Table functions

${relation-title-prose: Call_table_func}
${rulegroup-prose: Call_table_func}

Table rows are evaluated as follows:

${relation-title-prose: Eval_tblrows}
${rulegroup-prose: Eval_tblrows}

${relation-title-prose: Eval_tblrow}
${rulegroup-prose: Eval_tblrow/succ}
${rulegroup-prose: Eval_tblrow/fail}

==== User-defined functions

${relation-title-prose: Call_defined_func}
${rulegroup-prose: Call_defined_func/ret}
${rulegroup-prose: Call_defined_func/fail}
