[#sec-constructor]
=== Constructors

// Modified Seection 8.23 of the P4-16 Language Specification
Objects can be instantiated in three ways:

* Using instantiations, described in <<sec-instantiation-declaration>>.
* Using constructor call expressions, described in <<sec-constructor-call-expression>>.
* Using direct application statements, described in <<sec-direct-application-statement>>.

Instantiations and constructor call expressions invoke constructors, which
creates an object as a result. Direct application statements are syntactic
sugar for instantiations of ``parser`` and ``control`` objects.

Constructor invocation is similar to callable invocation; constructors can
also be overloaded, and called using named arguments.

[#sec-constructor-parameter]
==== Constructor parameters

// Modified Section 15 of the P4-16 Language Specification
In order to support libraries of useful P4 components, ``extern``s, ``parser``s,
``control``s, and ``package``s can additionally be parameterized through the
use of constructor parameters.

Consider the parser declaration syntax:

// Added
${syntax: constructorParameterListOpt
          parserDeclaration}

// Modified Section 15 of the P4-16 Language Specification
From this grammar fragment we infer that a ``parser`` declaration may have two
sets of parameters:

-	The runtime parser parameters (``parameterList``)
-	Optional parser constructor parameters (``constructorParameterListOpt``)

Because constructors are evaluated entirely at compilation time, all
constructor arguments must be expressions that can be evaluated at compilation
time. In consequence, constructor parameters must be directionless 
(i.e., they cannot be ``in``, ``out``, or ``inout``).

Consider the following example:

[source,p4]
----
parser GenericParser(packet_in b, out Packet_header p)
                    (bool udpSupport) {   // constructor parameters
    state start {
        b.extract(p.ethernet);
        transition select(p.ethernet.etherType) {
            16w0x0800: ipv4;
        }
    }
    state ipv4 {
        b.extract(p.ipv4);
        transition select(p.ipv4.protocol) {
           6: tcp;
           17: tryudp;
        }
    }
    state tryudp {
        transition select(udpSupport) {
            false: accept;
            true : udp;
        }
    }
    state udp {
         // body omitted
    }
}
----

When instantiating the `GenericParser` it is necessary to supply a value for
the `udpSupport` parameter, as in the following example:

[source,p4]
----
// topParser is a GenericParser where udpSupport = false
GenericParser(false) topParser;
----

Internally, constructor parameters are represented as:

${syntax: parameterIR
          constructorParameterIR}

[discrete]
====== § Well-formedness of constructor parameters

// Added
${relation-title-prose: ConstructorParameterType_wf}

// Added
${rulegroup-source: ConstructorParameterType_wf}
${rulegroup-prose: ConstructorParameterType_wf}

[#sec-constructor-definitions]
==== Constructor definitions

// Added
Similar to how type declarations introduce type definitions and callable
declarations introduce callable definitions (see <<sec-callable-definitions>>),
constructor declarations introduce constructor definitions. These are
parameterized by type parameters, and produces a constructor type when
specialized with specific type arguments.

The runtime representation of constructors is defined as follows:

${syntax: constructorDef}

// Added
When type arguments and constructor arguments are supplied to a constructor
definition, an object of the constructed type is created.

[#sec-constructor-types]
==== Constructor and constructor definition types

// Added
Similar to how callable types are internally used during type checking to
represent callables, constructor types internally represent the types of
constructors.

${syntax: constructorTypeIR
          constructorTypeDefIR}

[discrete]
====== § Well-formedness of constructor definition types

// Added
${relation-title-prose: ConstructorTypeDef_wf}

// Added
${rulegroup-source: ConstructorTypeDef_wf}
${rulegroup-prose: ConstructorTypeDef_wf}
