[#sec-control-object]
=== Control objects

// Section 14 of the P4-16 Language Specification
P4 parsers are responsible for extracting bits from a packet into headers.
These headers (and other metadata) can be manipulated and transformed within
`control` blocks. The body of a control block resembles a traditional
imperative program. Within the body of a control block, match-action units can
be invoked to perform data transformations. Match-action units are represented
in P4 by constructs called `tables`.

Syntactically, a `control` block is declared with a name, parameters, optional
type parameters, and a sequence of declarations of constants, variables,
``action``s, ``table``s, and other instantiations:

// Added
${syntax: controlLocalDeclaration
          controlBody
          controlDeclaration}

// Section 14 of the P4-16 Language Specification
It is illegal to instantiate a `parser` within a `control` block. Similar to
parser declarations, control declarations may not be generic--e.g., the
following declaration is illegal:

[source,p4]
----
control C<H>(inout H data); // generic control type declaration is legal
control C<H>(inout H data) { /* body omitted */ } // generic control declaration is illegal
----

P4 does not support exceptional control-flow within a `control` block. The only
statement which has a non-local effect on control flow is `exit`, which causes
execution of the enclosing control block to immediately terminate. That is,
there is no equivalent of the `verify` statement or the `reject` state from
parsers. Hence, all error handling must be performed explicitly by the
programmer.

// Added
A `control` declaration introduces a control object constructor, represented
as:

[[controlObjectConstructorDef]]
${syntax: controlObjectConstructorDef}

Control objects are then instantiated by constructor invocations to yield:

[[controlObject]]
${syntax: controlObject}

[discrete]
==== Well-formedness of control object constructor types

// Added
${rulegroup-source: ConstructorType_wf/controlObjectTypeIR}
${rulegroup-prose: ConstructorType_wf/controlObjectTypeIR}
