[#sec-cast-operation]
=== Performing casts

// Added
Cast operations are evaluated with:

// Added
${func-title-source: cast_op}
${func-title-prose: cast_op}

// Added
${func-source: cast_op}
${func-prose: cast_op}

==== From a Boolean value

// Added
${func-source: cast_bool}
${func-prose: cast_bool}

==== From an integer value

// Added
${func-source: cast_int}
${func-prose: cast_int}

==== From an error value

// Added
${func-source: cast_error}
${func-prose: cast_error}

==== From a list value

// Added
${func-source: cast_list}
${func-prose: cast_list}

==== From a header stack value

// Added
${func-source: cast_header_stack}
${func-prose: cast_header_stack}

==== From a struct value

// Added
${func-source: cast_struct}
${func-prose: cast_struct}

==== From a header value

// Added
${func-source: cast_header}
${func-prose: cast_header}

==== From an enum value

// Added
${func-source: cast_enum}
${func-prose: cast_enum}

==== From a default value

// Added
${func-source: cast_default}
${func-prose: cast_default}

==== From an invalid header value

// Added
${func-source: cast_invalid_header}
${func-prose: cast_invalid_header}

==== From a sequence value

// Added
${func-source: cast_sequence}
${func-prose: cast_sequence}

==== From a record value

// Added
${func-source: cast_record}
${func-prose: cast_record}

==== From a set value

// Added
${func-source: cast_set}
${func-prose: cast_set}
