(library
 (name p4spectec)
 (modules)
 (libraries
  (re_export util)
  (re_export frontend)
  (re_export runtime)
  (re_export elaborate)
  (re_export structure)
  (re_export builtin)
  (re_export interp_il)
  (re_export interp_sl)
  (re_export testgen)
  (re_export prose)
  (re_export splice)
  (re_export interface)
  (re_export stf)
  (re_export arch)))
