//! Diagnostics for partial operations in otherwise bodies
//!
//! Callers locate the first forbidden premise or nested function call.

use crate::lang::{
    common::{Id, source::Span},
    traits::at::At,
};

use crate::lang::il::ast::Otherwise;

use crate::diagnostic::Label;

use crate::pass::algo::binding::partial::Origin;

use super::{AlgoError, cause};

const OTHERWISE_CONDITION_INVALID: &str = "algo/otherwise-condition-invalid";
const OTHERWISE_MULTIBIND_INVALID: &str = "algo/otherwise-multibind-invalid";
const OTHERWISE_PARTIALBIND_INVALID: &str = "algo/otherwise-partialbind-invalid";

/// Reports a conditional premise in an otherwise body.
pub(crate) fn otherwise_condition_invalid(span: &Span, otherwise: &Otherwise) -> AlgoError {
    cause(
        OTHERWISE_CONDITION_INVALID,
        "an `otherwise` body cannot test a condition",
        vec![
            Label::primary(span, ""),
            Label::secondary(&otherwise.at(), "`otherwise` body starts here"),
        ],
        vec![],
    )
}

/// Explains the equality generated by multibind in an otherwise pattern.
pub(crate) fn otherwise_multibind_invalid(
    id_bound: &Id,
    id_repeated: &Id,
    otherwise: &Otherwise,
) -> AlgoError {
    cause(
        OTHERWISE_MULTIBIND_INVALID,
        format!(
            "repeating `{}` requires an equality check, which is not allowed in an `otherwise` clause",
            id_repeated.node
        ),
        vec![
            Label::primary(&id_repeated.span, format!("repeated `{}`", id_repeated.node)),
            Label::secondary(&id_bound.span, "first bound here"),
            Label::secondary(&otherwise.at(), "`otherwise` clause starts here"),
        ],
        vec![],
    )
}

/// Explains a condition introduced by partialbind in an otherwise pattern.
pub(crate) fn otherwise_partialbind_invalid(origin: &Origin, otherwise: &Otherwise) -> AlgoError {
    let (span, message) = match origin {
        // Compare a bound sub-pattern with its source value
        Origin::Equality(span) => (span, "this pattern requires an equality check".to_owned()),
        // Match an injected or non-singleton shape
        Origin::Match(span, construct) => {
            (span, format!("matching this {construct} requires a check"))
        }
        // Check that the source belongs to the subtype
        Origin::Subtype(span) => (span, "this pattern requires a subtype check".to_owned()),
    };
    cause(
        OTHERWISE_PARTIALBIND_INVALID,
        format!("{message}, which is not allowed in an `otherwise` clause"),
        vec![
            Label::primary(span, "pattern requiring a condition"),
            Label::secondary(&otherwise.at(), "`otherwise` clause starts here"),
        ],
        vec![],
    )
}

const OTHERWISE_FUNCTION_CALL_INVALID: &str = "algo/otherwise-function-call-invalid";

/// Reports the nested function call in an otherwise body.
pub(crate) fn otherwise_function_call_invalid(span: &Span, otherwise: &Otherwise) -> AlgoError {
    cause(
        OTHERWISE_FUNCTION_CALL_INVALID,
        "an `otherwise` body cannot call a function",
        vec![
            Label::primary(span, ""),
            Label::secondary(&otherwise.at(), "`otherwise` body starts here"),
        ],
        vec![],
    )
}

const OTHERWISE_RELATION_CALL_INVALID: &str = "algo/otherwise-relation-call-invalid";

/// Reports a relation call in an otherwise body.
pub(crate) fn otherwise_relation_call_invalid(span: &Span, otherwise: &Otherwise) -> AlgoError {
    cause(
        OTHERWISE_RELATION_CALL_INVALID,
        "an `otherwise` body cannot call a relation",
        vec![
            Label::primary(span, ""),
            Label::secondary(&otherwise.at(), "`otherwise` body starts here"),
        ],
        vec![],
    )
}
