[appendix]
[#sec-lift-meta-functions]
== Lifting P4IR to surface syntax

// Added
Each P4~IR~ node is lifted back into the corresponding surface syntax by the
following functions, grouped by construct category.

[discrete]
==== Names

// Added
${func-source: lift_nameIR_as_identifier}
${func-latex: lift_nameIR_as_identifier}
${func-prose: lift_nameIR_as_identifier}

// Added
${func-source: lift_nameIR_as_typeIdentifier}
${func-latex: lift_nameIR_as_typeIdentifier}
${func-prose: lift_nameIR_as_typeIdentifier}

// Added
${func-source: lift_nameIR_as_nonTypeName}
${func-latex: lift_nameIR_as_nonTypeName}
${func-prose: lift_nameIR_as_nonTypeName}

// Added
${func-source: lift_prefixedNameIR_as_prefixedNonTypeName}
${func-latex: lift_prefixedNameIR_as_prefixedNonTypeName}
${func-prose: lift_prefixedNameIR_as_prefixedNonTypeName}

// Added
${func-source: lift_nameIR_as_typeName}
${func-latex: lift_nameIR_as_typeName}
${func-prose: lift_nameIR_as_typeName}

// Added
${func-source: lift_prefixedNameIR_as_prefixedTypeName}
${func-latex: lift_prefixedNameIR_as_prefixedTypeName}
${func-prose: lift_prefixedNameIR_as_prefixedTypeName}

// Added
${func-source: lift_nameIR_as_tableCustomName}
${func-latex: lift_nameIR_as_tableCustomName}
${func-prose: lift_nameIR_as_tableCustomName}

// Added
${func-source: lift_nameListIR_as_nonTypeNameList}
${func-latex: lift_nameListIR_as_nonTypeNameList}
${func-prose: lift_nameListIR_as_nonTypeNameList}

// Added
${func-source: lift_nameIR_as_member}
${func-latex: lift_nameIR_as_member}
${func-prose: lift_nameIR_as_member}

[discrete]
==== Values

// Added
${func-source: lift_value}
${func-latex: lift_value}
${func-prose: lift_value}

[discrete]
==== Types

// Added
${func-source: lift_baseTypeIR}
${func-latex: lift_baseTypeIR}
${func-prose: lift_baseTypeIR}

// Added
${func-source: lift_nameTypeIR}
${func-latex: lift_nameTypeIR}
${func-prose: lift_nameTypeIR}

// Added
${func-source: lift_aliasTypeIR}
${func-latex: lift_aliasTypeIR}
${func-prose: lift_aliasTypeIR}

// Added
${func-source: lift_dataTypeIR}
${func-latex: lift_dataTypeIR}
${func-prose: lift_dataTypeIR}

// Added
${func-source: lift_typeIR}
${func-latex: lift_typeIR}
${func-prose: lift_typeIR}

// Added
${func-source: lift_typeIR_as_typeOrVoid}
${func-latex: lift_typeIR_as_typeOrVoid}
${func-prose: lift_typeIR_as_typeOrVoid}

[discrete]
==== Type definitions

// Added
${func-source: lift_typeDefIR_as_typeName}
${func-latex: lift_typeDefIR_as_typeName}
${func-prose: lift_typeDefIR_as_typeName}

[discrete]
==== Type parameters

// Added
${func-source: lift_typeParameterIR}
${func-latex: lift_typeParameterIR}
${func-prose: lift_typeParameterIR}

// Added
${func-source: lift_typeParameterListIR}
${func-latex: lift_typeParameterListIR}
${func-prose: lift_typeParameterListIR}

[discrete]
==== Parameters

// Added
${func-source: lift_parameterIR}
${func-latex: lift_parameterIR}
${func-prose: lift_parameterIR}

// Added
${func-source: lift_parameterListIR}
${func-latex: lift_parameterListIR}
${func-prose: lift_parameterListIR}

[discrete]
==== Constructor parameters

// Added
${func-source: lift_constructorParameterIR}
${func-latex: lift_constructorParameterIR}
${func-prose: lift_constructorParameterIR}

// Added
${func-source: lift_constructorParameterListIR}
${func-latex: lift_constructorParameterListIR}
${func-prose: lift_constructorParameterListIR}

[discrete]
==== Initializers

// Added
${func-source: lift_initializerIR}
${func-latex: lift_initializerIR}
${func-prose: lift_initializerIR}

// Added
${func-source: lift_initializerOptIR}
${func-latex: lift_initializerOptIR}
${func-prose: lift_initializerOptIR}

// Added
${func-source: lift_constantInitializerIR_as_initializer}
${func-latex: lift_constantInitializerIR_as_initializer}
${func-prose: lift_constantInitializerIR_as_initializer}

// Added
${func-source: lift_constantInitializerOptIR_as_initializerOpt}
${func-latex: lift_constantInitializerOptIR_as_initializerOpt}
${func-prose: lift_constantInitializerOptIR_as_initializerOpt}

[discrete]
==== Expression key-value pairs

// Added
${func-source: lift_namedExpressionIR}
${func-latex: lift_namedExpressionIR}
${func-prose: lift_namedExpressionIR}

// Added
${func-source: lift_namedExpressionListIR}
${func-latex: lift_namedExpressionListIR}
${func-prose: lift_namedExpressionListIR}

// Added
${func-source: lift_namedValueIR}
${func-latex: lift_namedValueIR}
${func-prose: lift_namedValueIR}

// Added
${func-source: lift_namedValueListIR}
${func-latex: lift_namedValueListIR}
${func-prose: lift_namedValueListIR}

[discrete]
==== Expressions

// Added
${func-source: lift_literalExpressionIR}
${func-latex: lift_literalExpressionIR}
${func-prose: lift_literalExpressionIR}

// Added
${func-source: lift_referenceExpressionIR}
${func-latex: lift_referenceExpressionIR}
${func-prose: lift_referenceExpressionIR}

// Added
${func-source: lift_defaultExpressionIR}
${func-latex: lift_defaultExpressionIR}
${func-prose: lift_defaultExpressionIR}

// Added
${func-source: lift_unaryExpressionIR}
${func-latex: lift_unaryExpressionIR}
${func-prose: lift_unaryExpressionIR}

// Added
${func-source: lift_binaryExpressionIR}
${func-latex: lift_binaryExpressionIR}
${func-prose: lift_binaryExpressionIR}

// Added
${func-source: lift_ternaryExpressionIR}
${func-latex: lift_ternaryExpressionIR}
${func-prose: lift_ternaryExpressionIR}

// Added
${func-source: lift_castExpressionIR}
${func-latex: lift_castExpressionIR}
${func-prose: lift_castExpressionIR}

// Added
${func-source: lift_dataExpressionIR}
${func-latex: lift_dataExpressionIR}
${func-prose: lift_dataExpressionIR}

[discrete]
==== Member and index access expressions

// Added
${func-source: lift_errorAccessExpressionIR}
${func-latex: lift_errorAccessExpressionIR}
${func-prose: lift_errorAccessExpressionIR}

// Added
${func-source: lift_memberAccessBaseIR}
${func-latex: lift_memberAccessBaseIR}
${func-prose: lift_memberAccessBaseIR}

// Added
${func-source: lift_memberAccessExpressionIR}
${func-latex: lift_memberAccessExpressionIR}
${func-prose: lift_memberAccessExpressionIR}

// Added
${func-source: lift_indexAccessExpressionIR}
${func-latex: lift_indexAccessExpressionIR}
${func-prose: lift_indexAccessExpressionIR}

// Added
${func-source: lift_sliceAccessExpressionIR}
${func-latex: lift_sliceAccessExpressionIR}
${func-prose: lift_sliceAccessExpressionIR}

// Added
${func-source: lift_accessExpressionIR}
${func-latex: lift_accessExpressionIR}
${func-prose: lift_accessExpressionIR}

// Added
${func-source: lift_callExpressionIR}
${func-latex: lift_callExpressionIR}
${func-prose: lift_callExpressionIR}

// Added
${func-source: lift_parenthesizedExpressionIR}
${func-latex: lift_parenthesizedExpressionIR}
${func-prose: lift_parenthesizedExpressionIR}

// Added
${func-source: lift_expressionIR}
${func-latex: lift_expressionIR}
${func-prose: lift_expressionIR}

// Added
${func-source: lift_typedExpressionIR}
${func-latex: lift_typedExpressionIR}
${func-prose: lift_typedExpressionIR}

// Added
${func-source: lift_typedExpressionListIR}
${func-latex: lift_typedExpressionListIR}
${func-prose: lift_typedExpressionListIR}

[discrete]
==== Keyset expressions

// Added
${func-source: lift_simpleKeysetExpressionIR}
${func-latex: lift_simpleKeysetExpressionIR}
${func-prose: lift_simpleKeysetExpressionIR}

// Added
${func-source: lift_simpleKeysetExpressionListIR}
${func-latex: lift_simpleKeysetExpressionListIR}
${func-prose: lift_simpleKeysetExpressionListIR}

// Added
${func-source: lift_tupleKeysetExpressionIR}
${func-latex: lift_tupleKeysetExpressionIR}
${func-prose: lift_tupleKeysetExpressionIR}

// Added
${func-source: lift_keysetExpressionIR}
${func-latex: lift_keysetExpressionIR}
${func-prose: lift_keysetExpressionIR}

[discrete]
==== Type arguments

// Added
${func-source: lift_typeArgumentIR_as_realTypeArgument}
${func-latex: lift_typeArgumentIR_as_realTypeArgument}
${func-prose: lift_typeArgumentIR_as_realTypeArgument}

// Added
${func-source: lift_typeArgumentIR}
${func-latex: lift_typeArgumentIR}
${func-prose: lift_typeArgumentIR}

// Added
${func-source: lift_typeArgumentListIR}
${func-latex: lift_typeArgumentListIR}
${func-prose: lift_typeArgumentListIR}

// Added
${func-source: lift_typeArgumentListIR_as_realTypeArgumentList}
${func-latex: lift_typeArgumentListIR_as_realTypeArgumentList}
${func-prose: lift_typeArgumentListIR_as_realTypeArgumentList}

[discrete]
==== Arguments

// Added
${func-source: lift_argumentIR}
${func-latex: lift_argumentIR}
${func-prose: lift_argumentIR}

// Added
${func-source: lift_argumentListIR}
${func-latex: lift_argumentListIR}
${func-prose: lift_argumentListIR}

[discrete]
==== Statements

// Added
${func-source: lift_emptyStatementIR}
${func-latex: lift_emptyStatementIR}
${func-prose: lift_emptyStatementIR}

// Added
${func-source: lift_assignmentStatementIR}
${func-latex: lift_assignmentStatementIR}
${func-prose: lift_assignmentStatementIR}

// Added
${func-source: lift_callStatementIR}
${func-latex: lift_callStatementIR}
${func-prose: lift_callStatementIR}

// Added
${func-source: lift_directApplicationStatementIR}
${func-latex: lift_directApplicationStatementIR}
${func-prose: lift_directApplicationStatementIR}

// Added
${func-source: lift_returnStatementIR}
${func-latex: lift_returnStatementIR}
${func-prose: lift_returnStatementIR}

// Added
${func-source: lift_exitStatementIR}
${func-latex: lift_exitStatementIR}
${func-prose: lift_exitStatementIR}

// Added
${func-source: lift_blockElementStatementIR}
${func-latex: lift_blockElementStatementIR}
${func-prose: lift_blockElementStatementIR}

// Added
${func-source: lift_blockElementStatementListIR}
${func-latex: lift_blockElementStatementListIR}
${func-prose: lift_blockElementStatementListIR}

// Added
${func-source: lift_blockStatementIR}
${func-latex: lift_blockStatementIR}
${func-prose: lift_blockStatementIR}

// Added
${func-source: lift_conditionalStatementIR}
${func-latex: lift_conditionalStatementIR}
${func-prose: lift_conditionalStatementIR}

// Added
${func-source: lift_switchLabelIR}
${func-latex: lift_switchLabelIR}
${func-prose: lift_switchLabelIR}

// Added
${func-source: lift_switchCaseIR}
${func-latex: lift_switchCaseIR}
${func-prose: lift_switchCaseIR}

// Added
${func-source: lift_switchCaseListIR}
${func-latex: lift_switchCaseListIR}
${func-prose: lift_switchCaseListIR}

// Added
${func-source: lift_switchStatementIR}
${func-latex: lift_switchStatementIR}
${func-prose: lift_switchStatementIR}

// Added
${func-source: lift_breakStatementIR}
${func-latex: lift_breakStatementIR}
${func-prose: lift_breakStatementIR}

// Added
${func-source: lift_continueStatementIR}
${func-latex: lift_continueStatementIR}
${func-prose: lift_continueStatementIR}

// Added
${func-source: lift_statementIR}
${func-latex: lift_statementIR}
${func-prose: lift_statementIR}

[discrete]
==== L-values

// Added
${func-source: lift_typedLvalueIR}
${func-latex: lift_typedLvalueIR}
${func-prose: lift_typedLvalueIR}

// Added
${func-source: lift_callableTargetIR_as_expression}
${func-latex: lift_callableTargetIR_as_expression}
${func-prose: lift_callableTargetIR_as_expression}

// Added
${func-source: lift_callableTargetIR_as_lvalue}
${func-latex: lift_callableTargetIR_as_lvalue}
${func-prose: lift_callableTargetIR_as_lvalue}

[discrete]
==== Declarations

// Added
${func-source: lift_constantDeclarationIR}
${func-latex: lift_constantDeclarationIR}
${func-prose: lift_constantDeclarationIR}

// Added
${func-source: lift_variableDeclarationIR}
${func-latex: lift_variableDeclarationIR}
${func-prose: lift_variableDeclarationIR}

// Added
${func-source: lift_functionPrototypeIR}
${func-latex: lift_functionPrototypeIR}
${func-prose: lift_functionPrototypeIR}

// Added
${func-source: lift_functionDeclarationIR}
${func-latex: lift_functionDeclarationIR}
${func-prose: lift_functionDeclarationIR}

// Added
${func-source: lift_actionDeclarationIR}
${func-latex: lift_actionDeclarationIR}
${func-prose: lift_actionDeclarationIR}

// Added
${func-source: lift_objectDeclarationIR}
${func-latex: lift_objectDeclarationIR}
${func-prose: lift_objectDeclarationIR}

// Added
${func-source: lift_objectDeclarationListIR}
${func-latex: lift_objectDeclarationListIR}
${func-prose: lift_objectDeclarationListIR}

// Added
${func-source: lift_instantiationIR}
${func-latex: lift_instantiationIR}
${func-prose: lift_instantiationIR}

// Added
${func-source: lift_errorDeclarationIR}
${func-latex: lift_errorDeclarationIR}
${func-prose: lift_errorDeclarationIR}

// Added
${func-source: lift_matchKindDeclarationIR}
${func-latex: lift_matchKindDeclarationIR}
${func-prose: lift_matchKindDeclarationIR}

// Added
${func-source: lift_enumTypeDeclarationIR}
${func-latex: lift_enumTypeDeclarationIR}
${func-prose: lift_enumTypeDeclarationIR}

// Added
${func-source: lift_typeFieldIR}
${func-latex: lift_typeFieldIR}
${func-prose: lift_typeFieldIR}

// Added
${func-source: lift_typeFieldListIR}
${func-latex: lift_typeFieldListIR}
${func-prose: lift_typeFieldListIR}

// Added
${func-source: lift_structTypeDeclarationIR}
${func-latex: lift_structTypeDeclarationIR}
${func-prose: lift_structTypeDeclarationIR}

// Added
${func-source: lift_headerTypeDeclarationIR}
${func-latex: lift_headerTypeDeclarationIR}
${func-prose: lift_headerTypeDeclarationIR}

// Added
${func-source: lift_headerUnionTypeDeclarationIR}
${func-latex: lift_headerUnionTypeDeclarationIR}
${func-prose: lift_headerUnionTypeDeclarationIR}

// Added
${func-source: lift_derivedTypeDeclarationIR}
${func-latex: lift_derivedTypeDeclarationIR}
${func-prose: lift_derivedTypeDeclarationIR}

// Added
${func-source: lift_typedefIR}
${func-latex: lift_typedefIR}
${func-prose: lift_typedefIR}

// Added
${func-source: lift_typedefDeclarationIR}
${func-latex: lift_typedefDeclarationIR}
${func-prose: lift_typedefDeclarationIR}

// Added
${func-source: lift_externFunctionDeclarationIR}
${func-latex: lift_externFunctionDeclarationIR}
${func-prose: lift_externFunctionDeclarationIR}

[discrete]
==== Object, parser, control, and table declarations

// Added
${func-source: lift_externConstructorPrototypeIR}
${func-latex: lift_externConstructorPrototypeIR}
${func-prose: lift_externConstructorPrototypeIR}

// Added
${func-source: lift_externMethodPrototypeIR}
${func-latex: lift_externMethodPrototypeIR}
${func-prose: lift_externMethodPrototypeIR}

// Added
${func-source: lift_externObjectDeclarationIR}
${func-latex: lift_externObjectDeclarationIR}
${func-prose: lift_externObjectDeclarationIR}

// Added
${func-source: lift_externDeclarationIR}
${func-latex: lift_externDeclarationIR}
${func-prose: lift_externDeclarationIR}

// Added
${func-source: lift_selectCaseIR}
${func-latex: lift_selectCaseIR}
${func-prose: lift_selectCaseIR}

// Added
${func-source: lift_selectCaseListIR}
${func-latex: lift_selectCaseListIR}
${func-prose: lift_selectCaseListIR}

// Added
${func-source: lift_selectExpressionIR}
${func-latex: lift_selectExpressionIR}
${func-prose: lift_selectExpressionIR}

// Added
${func-source: lift_stateExpressionIR}
${func-latex: lift_stateExpressionIR}
${func-prose: lift_stateExpressionIR}

// Added
${func-source: lift_transitionStatementIR}
${func-latex: lift_transitionStatementIR}
${func-prose: lift_transitionStatementIR}

// Added
${func-source: lift_typeIR_as_valueSetType}
${func-latex: lift_typeIR_as_valueSetType}
${func-prose: lift_typeIR_as_valueSetType}

// Added
${func-source: lift_valueSetDeclarationIR}
${func-latex: lift_valueSetDeclarationIR}
${func-prose: lift_valueSetDeclarationIR}

// Added
${func-source: lift_parserTypeDeclarationIR}
${func-latex: lift_parserTypeDeclarationIR}
${func-prose: lift_parserTypeDeclarationIR}

// Added
${func-source: lift_parserBlockElementStatementIR}
${func-latex: lift_parserBlockElementStatementIR}
${func-prose: lift_parserBlockElementStatementIR}

// Added
${func-source: lift_parserBlockElementStatementListIR}
${func-latex: lift_parserBlockElementStatementListIR}
${func-prose: lift_parserBlockElementStatementListIR}

// Added
${func-source: lift_parserBlockStatementIR}
${func-latex: lift_parserBlockStatementIR}
${func-prose: lift_parserBlockStatementIR}

// Added
${func-source: lift_parserConditionalStatementIR}
${func-latex: lift_parserConditionalStatementIR}
${func-prose: lift_parserConditionalStatementIR}

// Added
${func-source: lift_parserStatementIR}
${func-latex: lift_parserStatementIR}
${func-prose: lift_parserStatementIR}

// Added
${func-source: lift_parserStateIR}
${func-latex: lift_parserStateIR}
${func-prose: lift_parserStateIR}

// Added
${func-source: lift_parserStateListIR}
${func-latex: lift_parserStateListIR}
${func-prose: lift_parserStateListIR}

// Added
${func-source: lift_parserLocalDeclarationIR}
${func-latex: lift_parserLocalDeclarationIR}
${func-prose: lift_parserLocalDeclarationIR}

// Added
${func-source: lift_parserLocalDeclarationListIR}
${func-latex: lift_parserLocalDeclarationListIR}
${func-prose: lift_parserLocalDeclarationListIR}

// Added
${func-source: lift_parserDeclarationIR}
${func-latex: lift_parserDeclarationIR}
${func-prose: lift_parserDeclarationIR}

// Added
${func-source: lift_constOptIR}
${func-latex: lift_constOptIR}
${func-prose: lift_constOptIR}

// Added
${func-source: lift_tableKeyIR}
${func-latex: lift_tableKeyIR}
${func-prose: lift_tableKeyIR}

// Added
${func-source: lift_tableKeyListIR}
${func-latex: lift_tableKeyListIR}
${func-prose: lift_tableKeyListIR}

// Added
${func-source: lift_tableActionReferenceIR}
${func-latex: lift_tableActionReferenceIR}
${func-prose: lift_tableActionReferenceIR}

// Added
${func-source: lift_tableActionReferenceIR_as_expression}
${func-latex: lift_tableActionReferenceIR_as_expression}
${func-prose: lift_tableActionReferenceIR_as_expression}

// Added
${func-source: lift_tableActionIR}
${func-latex: lift_tableActionIR}
${func-prose: lift_tableActionIR}

// Added
${func-source: lift_tableActionListIR}
${func-latex: lift_tableActionListIR}
${func-prose: lift_tableActionListIR}

// Added
${func-source: lift_tableEntryPriorityIR}
${func-latex: lift_tableEntryPriorityIR}
${func-prose: lift_tableEntryPriorityIR}

// Added
${func-source: lift_tableEntryIR}
${func-latex: lift_tableEntryIR}
${func-prose: lift_tableEntryIR}

// Added
${func-source: lift_tableEntryListIR}
${func-latex: lift_tableEntryListIR}
${func-prose: lift_tableEntryListIR}

// Added
${func-source: lift_tableCustomPropertyIR}
${func-latex: lift_tableCustomPropertyIR}
${func-prose: lift_tableCustomPropertyIR}

// Added
${func-source: lift_tableKeysPropertyIR}
${func-latex: lift_tableKeysPropertyIR}
${func-prose: lift_tableKeysPropertyIR}

// Added
${func-source: lift_tableActionsPropertyIR}
${func-latex: lift_tableActionsPropertyIR}
${func-prose: lift_tableActionsPropertyIR}

// Added
${func-source: lift_tableDefaultActionPropertyIR}
${func-latex: lift_tableDefaultActionPropertyIR}
${func-prose: lift_tableDefaultActionPropertyIR}

// Added
${func-source: lift_tableEntriesPropertyIR}
${func-latex: lift_tableEntriesPropertyIR}
${func-prose: lift_tableEntriesPropertyIR}

// Added
${func-source: lift_tablePropertyIR}
${func-latex: lift_tablePropertyIR}
${func-prose: lift_tablePropertyIR}

// Added
${func-source: lift_tablePropertyListIR}
${func-latex: lift_tablePropertyListIR}
${func-prose: lift_tablePropertyListIR}

// Added
${func-source: lift_tableDeclarationIR}
${func-latex: lift_tableDeclarationIR}
${func-prose: lift_tableDeclarationIR}

// Added
${func-source: lift_controlTypeDeclarationIR}
${func-latex: lift_controlTypeDeclarationIR}
${func-prose: lift_controlTypeDeclarationIR}

// Added
${func-source: lift_controlBodyIR}
${func-latex: lift_controlBodyIR}
${func-prose: lift_controlBodyIR}

// Added
${func-source: lift_controlLocalDeclarationIR}
${func-latex: lift_controlLocalDeclarationIR}
${func-prose: lift_controlLocalDeclarationIR}

// Added
${func-source: lift_controlLocalDeclarationListIR}
${func-latex: lift_controlLocalDeclarationListIR}
${func-prose: lift_controlLocalDeclarationListIR}

// Added
${func-source: lift_controlDeclarationIR}
${func-latex: lift_controlDeclarationIR}
${func-prose: lift_controlDeclarationIR}

// Added
${func-source: lift_packageTypeDeclarationIR}
${func-latex: lift_packageTypeDeclarationIR}
${func-prose: lift_packageTypeDeclarationIR}

// Added
${func-source: lift_typeDeclarationIR}
${func-latex: lift_typeDeclarationIR}
${func-prose: lift_typeDeclarationIR}

// Added
${func-source: lift_declarationIR}
${func-latex: lift_declarationIR}
${func-prose: lift_declarationIR}

[discrete]
==== P4 program

// Added
${func-source: lift_p4programIR}
${func-latex: lift_p4programIR}
${func-prose: lift_p4programIR}
