[#sec-cast-insertion]
=== Cast insertion

// Added
When typing a P4~16~ program to a P4~IR~ program, all implicit casts are made
explicit. This process is called _cast insertion_. A cast may be inserted
such that an expression matches the expected type, and it may also be
inserted to ensure that two expressions have the same type.

// Added
Since a cast may take several steps, as described in Section <<sec-cast-chain>>,
one cast is inserted per step of the chain.

// Added
${func-source: apply_cast}
${func-latex: apply_cast}
${func-prose: apply_cast}

==== Casts to match expected type

// Added
The below function inserts casts to match expected types.

${func-title-source: cast_unary}
${func-title-latex: cast_unary}
${func-title-prose: cast_unary}

${func-source: cast_unary}
${func-latex: cast_unary}
${func-prose: cast_unary}

==== Casts to ensure type equality

// Added
The below function inserts casts to ensure that two expressions have the same type.

// Added
${func-title-source: cast_binary}
${func-title-latex: cast_binary}
${func-title-prose: cast_binary}

// Added
${func-title-source: cast_binary}
${func-title-latex: cast_binary}
${func-title-prose: cast_binary}

${func-source: cast_binary}
${func-latex: cast_binary}
${func-prose: cast_binary}

==== Serializable enum reduction

// Added
Casting and operator typing may require reducing serializable enums to their
underlying types. A single expression is reduced with:

// Added
${func-source: reduce_serenum}
${func-latex: reduce_serenum}
${func-prose: reduce_serenum}

// Added
A single operand is reduced until a condition on its type holds with:

// Added
${func-source: reduce_serenum_unary}
${func-latex: reduce_serenum_unary}
${func-prose: reduce_serenum_unary}

// Added
A pair of operands is reduced until a condition on both types holds with:

// Added
${func-source: reduce_serenum_binary}
${func-latex: reduce_serenum_binary}
${func-prose: reduce_serenum_binary}
