[#sec-constructor]
=== Constructors

Objects are created from constructor invocations.

In order to support libraries of useful P4 components, both ``parser``s and
`control` blocks can be additionally parameterized through the use of
constructor parameters.

Consider the parser declaration syntax:

${syntax: constructorParameterListOpt
          parserDeclaration}

From this grammar fragment we infer that a `parser` declaration may have two
sets of parameters:

-	The runtime parser parameters (`parameterList`)
-	Optional parser constructor parameters (`optConstructorParameters`)

Constructor parameters must be directionless (i.e., they cannot be `in`, `out`,
or `inout`) and where the parser is instantiated, it must be possible to fully
evaluate the expressions supplied for these parameters at compilation time.

Consider the following example:

[source,p4]
----
parser GenericParser(packet_in b, out Packet_header p)
                    (bool udpSupport) {   // constructor parameters
    state start {
        b.extract(p.ethernet);
        transition select(p.ethernet.etherType) {
            16w0x0800: ipv4;
        }
    }
    state ipv4 {
        b.extract(p.ipv4);
        transition select(p.ipv4.protocol) {
           6: tcp;
           17: tryudp;
        }
    }
    state tryudp {
        transition select(udpSupport) {
            false: accept;
            true : udp;
        }
    }
    state udp {
         // body omitted
    }
}
----

When instantiating the `GenericParser` it is necessary to supply a value for
the `udpSupport` parameter, as in the following example:

[source,p4]
----
// topParser is a GenericParser where udpSupport = false
GenericParser(false) topParser;
----

Constructors may also be parameterized by type parameters. Internally,
constructor types and constructor type definitions are defined as follows:

${syntax: constructorTypeIR
          constructorTypeDefIR}

The runtime representation of constructors is defined as follows:

${syntax: constructorDef}

The types that can be constructed are defined as follows:

${funcprose: definable_constructor}
${funcprose: definable'_constructor}

[#sec-sem-ConstructorTypeDef_wf]
==== Well-formedness

${rulegroup: ConstructorTypeDef_wf}
${ruleprose: ConstructorTypeDef_wf}
