[#sec-controlDeclaration]
=== Control declaration

P4 parsers are responsible for extracting bits from a packet into headers.
These headers (and other metadata) can be manipulated and transformed within
`control` blocks. The body of a control block resembles a traditional
imperative program. Within the body of a control block, match-action units can
be invoked to perform data transformations. Match-action units are represented
in P4 by constructs called `tables`.

Syntactically, a `control` block is declared with a name, parameters, optional
type parameters, and a sequence of declarations of constants, variables,
``action``s, ``table``s, and other instantiations:

${syntax: controlLocalDeclaration
          controlBody
          controlDeclaration
          controlLocalDeclarationIR
          controlBodyIR
          controlDeclarationIR}

It is illegal to instantiate a `parser` within a `control` block. Unlike
control type declarations, control declarations may not be generic---e.g., the
following declaration is illegal:

P4 does not support exceptional control-flow within a `control` block. The only
statement which has a non-local effect on control flow is `exit`, which causes
execution of the enclosing control block to immediately terminate. That is,
there is no equivalent of the `verify` statement or the `reject` state from
parsers. Hence, all error handling must be performed explicitly by the
programmer.

[source,p4]
----
control C<H>(inout H data) { /* Body omitted */ }
----

[[sem-type-check-controlDeclaration]]
==== Type checking

${rulegroup: Decl_ok/controlDeclaration}
${ruleprose: Decl_ok/controlDeclaration}

[[sem-compile-time-eval-controlDeclaration]]
==== Compile-time evaluation

${rulegroup: Decl_inst/controlDeclarationIR}
${ruleprose: Decl_inst/controlDeclarationIR}
