=== Type equivalence

// Added
P4 has generic types, thus to reason about equivalence of types,
alpha-equivalence is used. Two types are alpha-equivalent if they are the
same up to renaming of type variables.

// Added
The following relation defines alpha-equivalence of types:

// Added
${relation-title-source: Type_alpha}
${relation-title-prose: Type_alpha}

// Added
The following relation defines alpha-equivalence of parameters:

// Added
${relation-title-source: ParameterType_alpha}
${relation-title-prose: ParameterType_alpha}

// Added
${rulegroup-source: ParameterType_alpha}
${rulegroup-prose: ParameterType_alpha}

==== Base types

// Added
${rulegroup-source: Type_alpha/baseTypeIR}
${rulegroup-prose: Type_alpha/baseTypeIR}

==== Named types

// Added
${rulegroup-source: Type_alpha/nameTypeIR}
${rulegroup-prose: Type_alpha/nameTypeIR}

==== Data types

===== List types

// Added
${rulegroup-source: Type_alpha/listTypeIR}
${rulegroup-prose: Type_alpha/listTypeIR}

===== Tuple types

// Added
${rulegroup-source: Type_alpha/tupleTypeIR}
${rulegroup-prose: Type_alpha/tupleTypeIR}

===== Header stack types

// Added
${rulegroup-source: Type_alpha/headerStackTypeIR}
${rulegroup-prose: Type_alpha/headerStackTypeIR}

===== Struct types

// Added
${rulegroup-source: Type_alpha/structTypeIR}
${rulegroup-prose: Type_alpha/structTypeIR}

===== Header types

// Added
${rulegroup-source: Type_alpha/headerTypeIR}
${rulegroup-prose: Type_alpha/headerTypeIR}

===== Header union types

// Added
${rulegroup-source: Type_alpha/headerUnionTypeIR}
${rulegroup-prose: Type_alpha/headerUnionTypeIR}

===== Enum types

// Added
${rulegroup-source: Type_alpha/enumTypeIR}
${rulegroup-prose: Type_alpha/enumTypeIR}

==== Object types

===== Extern object types

// Added
${rulegroup-source: Type_alpha/externObjectTypeIR}
${rulegroup-prose: Type_alpha/externObjectTypeIR}

// Added
Additional equivalence rules for extern methods are defined as follows:

// Added
${relation-title-source: ExternMethodTypeDef_alpha}
${relation-title-prose: ExternMethodTypeDef_alpha}

// Added
${rulegroup-source: ExternMethodTypeDef_alpha}
${rulegroup-prose: ExternMethodTypeDef_alpha}

// Added
${relation-title-source: ExternMethodType_alpha}
${relation-title-prose: ExternMethodType_alpha}

// Added
${rulegroup-source: ExternMethodType_alpha}
${rulegroup-prose: ExternMethodType_alpha}

===== Parser object types

// Added
${rulegroup-source: Type_alpha/parserObjectTypeIR}
${rulegroup-prose: Type_alpha/parserObjectTypeIR}

===== Control object types

// Added
${rulegroup-source: Type_alpha/controlObjectTypeIR}
${rulegroup-prose: Type_alpha/controlObjectTypeIR}

===== Package object types

// Added
${rulegroup-source: Type_alpha/packetObjectTypeIR}
${rulegroup-prose: Type_alpha/packetObjectTypeIR}

===== Table object types

// Added
${rulegroup-source: Type_alpha/tableObjectTypeIR}
${rulegroup-prose: Type_alpha/tableObjectTypeIR}

==== Alias types

===== `typedef` types

// Added
${rulegroup-source: Type_alpha/typedefTypeIR}
${rulegroup-prose: Type_alpha/typedefTypeIR}

===== `type` types

// Added
${rulegroup-source: Type_alpha/newTypeIR}
${rulegroup-prose: Type_alpha/newTypeIR}

==== Synthesized types

===== Default types

// Added
${rulegroup-source: Type_alpha/defaultTypeIR}
${rulegroup-prose: Type_alpha/defaultTypeIR}

===== Invalid header types

// Added
${rulegroup-source: Type_alpha/invalidHeaderTypeIR}
${rulegroup-prose: Type_alpha/invalidHeaderTypeIR}

===== Sequence types

// Added
${rulegroup-source: Type_alpha/sequenceTypeIR}
${rulegroup-prose: Type_alpha/sequenceTypeIR}

===== Record types

// Added
${rulegroup-source: Type_alpha/recordTypeIR}
${rulegroup-prose: Type_alpha/recordTypeIR}

===== Set types

// Added
${rulegroup-source: Type_alpha/setTypeIR}
${rulegroup-prose: Type_alpha/setTypeIR}

===== Table metadata types

// Added
${rulegroup-source: Type_alpha/tableMetadataTypeIR}
${rulegroup-prose: Type_alpha/tableMetadataTypeIR}
