[#sec-binary-operation]
=== Binary operations

Binary operations are evaluated with:

${func-source: bin_op}
${func-prose: bin_op}

==== Addition

${func-source: bin_plus}
${func-prose: bin_plus}

==== Saturated addition

${func-source: bin_satplus}
${func-prose: bin_satplus}

==== Subtraction

${func-source: bin_minus}
${func-prose: bin_minus}

==== Saturated subtraction

${func-source: bin_satminus}
${func-prose: bin_satminus}

==== Multiplication

${func-source: bin_mul}
${func-prose: bin_mul}

==== Division

${func-source: bin_div}
${func-prose: bin_div}

==== Modulus

${func-source: bin_mod}
${func-prose: bin_mod}

==== Shift left

${func-source: bin_shl}
${func-prose: bin_shl}

==== Shift right

${func-source: bin_shr}
${func-prose: bin_shr}

==== Equality and inequality

${func-source: bin_eq}
${func-prose: bin_eq}

${func-source: bin_ne}
${func-prose: bin_ne}

==== Comparisons

${func-source: bin_lt}
${func-prose: bin_lt}

${func-source: bin_le}
${func-prose: bin_le}

${func-source: bin_gt}
${func-prose: bin_gt}

${func-source: bin_ge}
${func-prose: bin_ge}

==== Bitwise

${func-source: bin_band}
${func-prose: bin_band}

${func-source: bin_bor}
${func-prose: bin_bor}

${func-source: bin_bxor}
${func-prose: bin_bxor}
