[#sec-literal-expression]
=== Literal expressions

${syntax: literalExpression
          literalExpressionIR}

[#sec-Boolean-literal-expressions]
==== Boolean literal expressions

${syntax: booleanLiteral}

[discrete]
===== Type checking

//${rulegroup-source: Expr_ok/literalExpression-boolean}
${rulegroup-prose: Expr_ok/literalExpression-boolean}

[discrete]
===== Local compile-time evaluation

//${rulegroup-source: Expr_eval_lctk/literalExpressionIR-boolean}
${rulegroup-prose: Expr_eval_lctk/literalExpressionIR-boolean}

[discrete]
===== Compile-time evaluation

//${rulegroup-source: Expr_inst/literalExpressionIR-boolean}
${rulegroup-prose: Expr_inst/literalExpressionIR-boolean}

[#sec-numeric-literal-expressions]
==== Numeric literal expressions

${syntax: integerLiteral}

The types of integer literals are as follows:

* An integer with no type prefix has type `int`.
* A non-negative integer prefixed with an integer width `W` and the
  character `w` has type `bit<W>`.
* An integer prefixed with an integer width `W` and the character `s`
  has type `int<W>`.

The table below shows several examples of integer literals and their
types. For additional examples of literals see <<sec-literals>>.

[.center,cols=">1,4",width=70%]
|===
| Literal | Interpretation

| `10`    | Type is `int`, value is 10

| `8w10`  | Type is `bit<8>`, value is 10

| `8s10`  | Type is `int<8>`, value is 10

| `2s3`   | Type is `int<2>`, value is -1 (last 2 bits), overflow warning

| `1w10`  | Type is `bit<1>`, value is 0 (last bit), overflow warning

| `1s1`   | Type is `int<1>`, value is -1, overflow warning
|===

[discrete]
===== Type checking

${rulegroup-source: Expr_ok/literalExpression-number}
${rulegroup-prose: Expr_ok/literalExpression-number}

[discrete]
===== Local compile-time evaluation

${rulegroup-source: Expr_eval_lctk/literalExpressionIR-number}
${rulegroup-prose: Expr_eval_lctk/literalExpressionIR-number}

[discrete]
===== Compile-time evaluation

${rulegroup-source: Expr_inst/literalExpressionIR-number}
${rulegroup-prose: Expr_inst/literalExpressionIR-number}

[#sec-string-literal-expressions]
==== String literal expressions

${syntax: stringLiteral}

[discrete]
===== Type checking

${rulegroup-source: Expr_ok/literalExpression-stringLiteral}
${rulegroup-prose: Expr_ok/literalExpression-stringLiteral}

[discrete]
===== Local compile-time evaluation

${rulegroup-source: Expr_eval_lctk/literalExpressionIR-stringLiteral}
${rulegroup-prose: Expr_eval_lctk/literalExpressionIR-stringLiteral}

[discrete]
===== Compile-time evaluation

${rulegroup-source: Expr_inst/literalExpressionIR-stringLiteral}
${rulegroup-prose: Expr_inst/literalExpressionIR-stringLiteral}
