[#sec-binaryExpression]
=== Binary expressions

${syntax: binaryExpression binop}

See <<sec-binary-operation>> for details on how each binary operator is
evaluated. Note that logical operators (&&, ||) use short-circuit evaluation.

==== Type checking

===== Plus, minus, and multiplication

${rulegroup-source: Expr_ok/binaryExpression-plusminusmult}
${rulegroup-prose: Expr_ok/binaryExpression-plusminusmult}

===== Saturating plus and minus

${rulegroup-source: Expr_ok/binaryExpression-satplusminus}
${rulegroup-prose: Expr_ok/binaryExpression-satplusminus}

===== Division and modulo

${rulegroup-source: Expr_ok/binaryExpression-divmod}
${rulegroup-prose: Expr_ok/binaryExpression-divmod}

===== Shift left and right

${rulegroup-source: Expr_ok/binaryExpression-shift}
${rulegroup-prose: Expr_ok/binaryExpression-shift}

===== Equality and inequality

${rulegroup-source: Expr_ok/binaryExpression-equality}
${rulegroup-prose: Expr_ok/binaryExpression-equality}

===== Comparison

${rulegroup-source: Expr_ok/binaryExpression-comparison}
${rulegroup-prose: Expr_ok/binaryExpression-comparison}

===== Bitwise and, xor, and or

${rulegroup-source: Expr_ok/binaryExpression-bitwise}
${rulegroup-prose: Expr_ok/binaryExpression-bitwise}

===== Concatenation

${rulegroup-source: Expr_ok/binaryExpression-concat}
${rulegroup-prose: Expr_ok/binaryExpression-concat}

===== Logical and, and or

${rulegroup-source: Expr_ok/binaryExpression-logical}
${rulegroup-prose: Expr_ok/binaryExpression-logical}

==== Local compile-time evaluation

${rulegroup-source: Expr_eval_lctk/binaryExpressionIR}
${rulegroup-prose: Expr_eval_lctk/binaryExpressionIR}

==== Compile-time evaluation

${rulegroup-source: Expr_inst/binaryExpressionIR}
${rulegroup-prose: Expr_inst/binaryExpressionIR}

==== Runtime evaluation

${rulegroup-source: Expr_eval/binaryExpressionIR}
${rulegroup-prose: Expr_eval/binaryExpressionIR}
