[#sec-binaryExpression]
=== Binary expressions

${syntax: binop
          binaryExpression
          binaryExpressionIR}

[#sec-binaryExpression-plusminusmult]
==== Plus, minus, and multiplication operators

[discrete]
===== Type checking

${rulegroup-source: Expr_ok/binaryExpression-plusminusmult}
${rulegroup-prose: Expr_ok/binaryExpression-plusminusmult}

[#sec-binaryExpression-satplusminus]
==== Saturating plus and minus operators

[discrete]
===== Type checking

${rulegroup-source: Expr_ok/binaryExpression-satplusminus}
${rulegroup-prose: Expr_ok/binaryExpression-satplusminus}

[#sec-binaryExpression-divmod]
==== Division and modulo operators

[discrete]
===== Type checking

${rulegroup-source: Expr_ok/binaryExpression-divmod}
${rulegroup-prose: Expr_ok/binaryExpression-divmod}

[#sec-binaryExpression-shift]
==== Shift left and right operators

[discrete]
===== Type checking

${rulegroup-source: Expr_ok/binaryExpression-shift}
${rulegroup-prose: Expr_ok/binaryExpression-shift}

[#sec-binaryExpression-equality]
==== Equality and inequality operators

[discrete]
===== Type checking

${rulegroup-source: Expr_ok/binaryExpression-equality}
${rulegroup-prose: Expr_ok/binaryExpression-equality}

[#sec-binaryExpression-comparison]
==== Comparison operators

[discrete]
===== Type checking

${rulegroup-source: Expr_ok/binaryExpression-comparison}
${rulegroup-prose: Expr_ok/binaryExpression-comparison}

[#sec-binaryExpression-bitwise]
==== Bitwise and, xor, and or operators

[discrete]
===== Type checking

${rulegroup-source: Expr_ok/binaryExpression-bitwise}
${rulegroup-prose: Expr_ok/binaryExpression-bitwise}

[#sec-binaryExpression-concat]
==== Concatenation operators

[discrete]
===== Type checking

${rulegroup-source: Expr_ok/binaryExpression-concat}
${rulegroup-prose: Expr_ok/binaryExpression-concat}

[#sec-binaryExpression-logical]
==== Logical and, and or operator

[discrete]
===== Type checking

${rulegroup-source: Expr_ok/binaryExpression-logical}
${rulegroup-prose: Expr_ok/binaryExpression-logical}

[discrete]
==== Local compile-time evaluation

${rulegroup-source: Expr_eval_lctk/binaryExpressionIR}
${rulegroup-prose: Expr_eval_lctk/binaryExpressionIR}

[discrete]
==== Compile-time evaluation

${rulegroup-source: Expr_inst/binaryExpressionIR}
${rulegroup-prose: Expr_inst/binaryExpressionIR}
