[#sec-call-expression]
=== Call expressions

${syntax: callableTarget
          constructorTarget
          callTarget
          callExpression
          callableTargetIR
          constructorTargetIR
          callExpressionIR}

[#sec-callExpression-callable]
==== Callable call expressions

[discrete]
===== Type checking

${rulegroup-source: Expr_ok/callExpression-callable}
${rulegroup-prose: Expr_ok/callExpression-callable}

[discrete]
===== Local compile-time evaluation

${rulegroup-source: Expr_eval_lctk/callExpressionIR-builtin-size}
${rulegroup-prose: Expr_eval_lctk/callExpressionIR-builtin-size}

[discrete]
===== Compile-time evaluation

${rulegroup-source: Expr_inst/callExpressionIR-builtin-size}
${rulegroup-prose: Expr_inst/callExpressionIR-builtin-size}

[#sec-constructor-call-expression]
==== Constructor call expressions

[discrete]
===== Type checking

${rulegroup-source: Expr_ok/callExpression-constructor}
${rulegroup-prose: Expr_ok/callExpression-constructor}

[discrete]
===== Compile-time evaluation

${rulegroup-source: Expr_ok/callExpression-constructor}
${rulegroup-prose: Expr_ok/callExpression-constructor}

==== Parenthesized calls

[discrete]
===== Local compile-time evaluation

${rulegroup-source: Expr_eval_lctk/callExpressionIR-parenthesized}
${rulegroup-prose: Expr_eval_lctk/callExpressionIR-parenthesized}

[discrete]
===== Compile-time evaluation

${rulegroup-source: Expr_inst/callExpressionIR-parenthesized}
${rulegroup-prose: Expr_inst/callExpressionIR-parenthesized}
