(lang dune 3.7)
(using menhir 2.0)
(using mdx 0.2)
(name p4spectec)

(generate_opam_files true)

(package
  (name p4spectec)
  (version 0.1.0)
  (synopsis "P4SpecTec: A language design framework for the P4 Programming Language")
  (description "A mechanized specification and execution framework for the P4 language.")
  (maintainers "99jaehyunlee@kaist.ac.kr")
  (authors "KAIST PLRG")
  (license "Apache-2.0")
  (homepage "https://github.com/kaist-plrg/p4-spectec")
  (source (github kaist-plrg/p4-spectec))
  (bug_reports "https://github.com/kaist-plrg/p4-spectec/issues")
  (depends
    (dune (>= "3.7"))
    menhir
    bignum
    core
    core_unix
    ppx_let
    ppx_deriving_yojson))
