;; Negative diagnostic tests grouped by pass

(executable
 (name test)
 (modules test)
 (libraries p4spectec unix))

(rule
 (alias speclang)
 (action
  (progn
   (ignore-outputs
    (diff parse.expected parse.actual))
   (ignore-outputs
    (diff elab.expected elab.actual)))))

(rule
 (target parse.actual)
 (deps
  test.exe
  (source_tree cases/parse))
 (action
  (with-stdout-to
   parse.actual
   (with-stderr-to
    parse.err
    (run ./test.exe parse cases/parse)))))

(rule
 (target elab.actual)
 (deps
  test.exe
  (source_tree cases/elab))
 (action
  (with-stdout-to
   elab.actual
   (with-stderr-to
    elab.err
    (run ./test.exe elab cases/elab)))))
