(executable
 (name tex_test)
 (modules tex_test)
 (libraries p4spectec))

(rule
 (target tex.actual)
 (action
  (with-stdout-to
   tex.actual
   (run ./tex_test.exe))))

(rule
 (aliases latex-tex latex runtest)
 (action
  (diff tex.expected tex.actual)))

(executable
 (name term_test)
 (modules term_test)
 (libraries p4spectec))

(rule
 (target term.actual)
 (action
  (with-stdout-to
   term.actual
   (run ./term_test.exe))))

(rule
 (aliases latex-term latex runtest)
 (action
  (diff term.expected term.actual)))
