(executable
 (name tex_test)
 (modules tex_test)
 (libraries p4spectec))

(rule
 (target tex.actual)
 (action
  (with-stdout-to
   tex.actual
   (run ./tex_test.exe))))

(rule
 (aliases latex-tex latex runtest)
 (action
  (diff tex.expected tex.actual)))

(executable
 (name term_test)
 (modules term_test)
 (libraries p4spectec))

(rule
 (target term.actual)
 (action
  (with-stdout-to
   term.actual
   (run ./term_test.exe))))

(rule
 (aliases latex-term latex runtest)
 (action
  (diff term.expected term.actual)))

(executable
 (name definition_test)
 (modules definition_test)
 (libraries p4spectec))

(rule
 (target definition.actual)
 (action
  (with-stdout-to
   definition.actual
   (run ./definition_test.exe))))

(rule
 (aliases latex-definition latex runtest)
 (action
  (diff definition.expected definition.actual)))

(executable
 (name smoke_test)
 (modules smoke_test)
 (libraries p4spectec))

(rule
 (target latex-smoke.tex)
 (action
  (with-stdout-to
   latex-smoke.tex
   (run ./smoke_test.exe))))

(rule
 (alias latex-smoke)
 (deps latex-smoke.tex)
 (action
  (run pdflatex -halt-on-error -interaction=nonstopmode latex-smoke.tex)))
