[#sec-type-declaration]
=== Type declaration

${syntax: derivedTypeDeclaration
          typedefDeclaration
          typeDeclaration
          derivedTypeDeclarationIR
          typedefDeclarationIR
          typeDeclarationIR}

[#sec-enum-type-declaration]
==== Enum type declaration

${syntax: enumTypeDeclaration
          enumTypeDeclarationIR}

[#sec-simple-enum-type-declaration]
===== Enum type declaration

[#sec-serializable-enum-type-declaration]
===== Serializable enum type declaration

[#sec-struct-type-declaration]
==== Struct type declaration

${syntax: typeField
          structTypeDeclaration
          typeFieldIR
          structTypeDeclarationIR}

[#sec-header-type-declaration]
==== Header type declaration

${syntax: typeField
          headerTypeDeclaration
          typeFieldIR
          headerTypeDeclarationIR}

[#sec-header-union-type-declaration]
==== Header union type declaration

${syntax: typeField
          headerUnionTypeDeclaration
          typeFieldIR
          headerUnionTypeDeclarationIR}

[#sec-typdef-type-declaration]
==== Typedef declaration

${syntax: typedefType}

[#sec-newtype-type-declaration]
==== New type declaration

[#sec-parser-type-declaration]
==== Parser type declaration

${syntax: parserTypeDeclaration
          parserTypeDeclarationIR}

[#sec-control-type-declaration]
==== Control type declaration

${syntax: controlTypeDeclaration
          controlTypeDeclarationIR}

[#sec-package-type-declaration]
==== Package type declaration

${syntax: packageTypeDeclaration
          packageTypeDeclarationIR}
