[package]
name = "p4spectec"
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"

[dependencies]
foldhash = "=0.1.5"
clap = { version = "4.6.6", features = ["derive"] }
hashbrown = { version = "=0.17.1", default-features = false }
imbl = { version = "7.0.1", default-features = false }
lalrpop-util = { version = "0.23.1", default-features = false }
num-bigint = { version = "0.4.6", features = ["serde"] }
num-traits = "0.2.19"
serde = { version = "1.0.210", features = ["derive", "rc"] }
serde_derive_state = "0.4.11"
serde_json = { version = "1.0.128", features = ["unbounded_depth"] }
serde_state = "0.4.9"
serde_stacker = "0.1.11"
stacker = "0.1.25"
strtoint = "0.1"
thiserror = "1.0.63"
codespan-reporting = "0.13.1"

[build-dependencies]
lalrpop = { version = "0.23.1", default-features = false }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
