[#sec-unaryExpression]
=== Unary expressions

${syntax: unop
          unaryExpression
          unaryExpressionIR}

[#sec-unaryExpression-lnot]
==== Negation operators

[[sem-type-check-unaryExpression-lnot]]
[discrete]
===== Type checking

${rulegroup-source: Expr_ok/unaryExpression-lnot}
${rulegroup-prose: Expr_ok/unaryExpression-lnot}

[#sec-unaryExpression-bnot]
==== Bitwise complement operators

[[sem-type-check-unaryExpression-bnot]]
[discrete]
===== Type checking

${rulegroup-source: Expr_ok/unaryExpression-bnot}
${rulegroup-prose: Expr_ok/unaryExpression-bnot}

[#sec-unaryExpression-uplusminus]
==== Plus and minus operators

[[sem-type-check-unaryExpression-uplusminus]]
[discrete]
===== Type checking

${rulegroup-source: Expr_ok/unaryExpression-uplusminus}
${rulegroup-prose: Expr_ok/unaryExpression-uplusminus}

[[sem-local-compile-time-eval-unaryExpression]]
[discrete]
==== Local compile-time evaluation

${rulegroup-source: Expr_eval_lctk/unaryExpressionIR}
${rulegroup-prose: Expr_eval_lctk/unaryExpressionIR}

[[sem-compile-time-eval-unaryExpression]]
[discrete]
==== Compile-time evaluation

${rulegroup-source: Expr_inst/unaryExpressionIR}
${rulegroup-prose: Expr_inst/unaryExpressionIR}
