[#sec-binaryExpression]
=== Binary expressions

${syntax: binop
          binaryExpression
          binaryExpressionIR}

[#sec-binaryExpression-plusminusmult]
==== Plus, minus, and multiplication operators

[[sem-type-check-binaryExpression-plusminusmult]]
===== Type checking

${rulegroup: Expr_ok/binaryExpression-plusminusmult}
${ruleprose: Expr_ok/binaryExpression-plusminusmult}

[#sec-binaryExpression-satplusminus]
==== Saturating plus and minus operators

[[sem-type-check-binaryExpression-satplusminus]]
===== Type checking

${rulegroup: Expr_ok/binaryExpression-satplusminus}
${ruleprose: Expr_ok/binaryExpression-satplusminus}

[#sec-binaryExpression-divmod]
==== Division and modulo operators

[[sem-type-check-binaryExpression-divmod]]
===== Type checking

${rulegroup: Expr_ok/binaryExpression-divmod}
${ruleprose: Expr_ok/binaryExpression-divmod}

[#sec-binaryExpression-shift]
==== Shift left and right operators

[[sem-type-check-binaryExpression-shift]]
===== Type checking

${rulegroup: Expr_ok/binaryExpression-shift}
${ruleprose: Expr_ok/binaryExpression-shift}

[#sec-binaryExpression-equality]
==== Equality and inequality operators

[[sem-type-check-binaryExpression-equality]]
===== Type checking

${rulegroup: Expr_ok/binaryExpression-equality}
${ruleprose: Expr_ok/binaryExpression-equality}

[#sec-binaryExpression-comparison]
==== Comparison operators

[[sem-type-check-binaryExpression-comparison]]
===== Type checking

${rulegroup: Expr_ok/binaryExpression-comparison}
${ruleprose: Expr_ok/binaryExpression-comparison}

[#sec-binaryExpression-bitwise]
==== Bitwise and, xor, and or operators

[[sem-type-check-binaryExpression-bitwise]]
===== Type checking

${rulegroup: Expr_ok/binaryExpression-bitwise}
${ruleprose: Expr_ok/binaryExpression-bitwise}

[#sec-binaryExpression-concat]
==== Concatenation operators

[[sem-type-check-binaryExpression-concat]]
===== Type checking

${rulegroup: Expr_ok/binaryExpression-concat}
${ruleprose: Expr_ok/binaryExpression-concat}

[#sec-binaryExpression-logical]
==== Logical and, and or operator

[[sem-type-check-binaryExpression-logical]]
===== Type checking

${rulegroup: Expr_ok/binaryExpression-logical}
${ruleprose: Expr_ok/binaryExpression-logical}

[[sem-local-compile-time-eval-binaryExpression]]
==== Local compile-time evaluation

${rulegroup: Eval_static/binaryExpressionIR}
${ruleprose: Eval_static/binaryExpressionIR}

[[sem-compile-time-eval-binaryExpression]]
==== Compile-time evaluation

${rulegroup: Expr_inst/binaryExpressionIR}
${ruleprose: Expr_inst/binaryExpressionIR}
