[#sec-dataExpression]
=== Data expressions

${syntax: dataElementExpression
          dataExpression
          dataExpressionIR}

[#sec-invalid-header-dataExpression]
==== Invalid header expressions

[discrete]
===== Type checking

${rulegroup-source: Expr_ok/dataExpression-invalid}
${rulegroup-prose: Expr_ok/dataExpression-invalid}

[discrete]
===== Local compile-time evaluation

${rulegroup-source: Expr_eval_lctk/dataExpressionIR-invalid}
${rulegroup-prose: Expr_eval_lctk/dataExpressionIR-invalid}

[discrete]
===== Compile-time evaluation

${rulegroup-source: Expr_inst/dataExpressionIR-invalid}
${rulegroup-prose: Expr_inst/dataExpressionIR-invalid}

[#sec-sequence-data-expression]
==== Sequence expressions

${syntax: sequenceElementExpression}

[discrete]
===== Type checking

${rulegroup-source: Expr_ok/dataExpression-sequence}
${rulegroup-prose: Expr_ok/dataExpression-sequence}

[discrete]
===== Local compile-time evaluation

${rulegroup-source: Expr_eval_lctk/dataExpressionIR-sequence}
${rulegroup-prose: Expr_eval_lctk/dataExpressionIR-sequence}

[discrete]
===== Compile-time evaluation

${rulegroup-source: Expr_inst/dataExpressionIR-sequence}
${rulegroup-prose: Expr_inst/dataExpressionIR-sequence}

[#sec-record-data-expression]
==== Record expressions

${syntax: recordElementExpression}

[discrete]
===== Type checking

${rulegroup-source: Expr_ok/dataExpression-record}
${rulegroup-prose: Expr_ok/dataExpression-record}

[discrete]
===== Local compile-time evaluation

${rulegroup-source: Expr_eval_lctk/dataExpressionIR-record}
${rulegroup-prose: Expr_eval_lctk/dataExpressionIR-record}

[discrete]
===== Compile-time evaluation

${rulegroup-source: Expr_inst/dataExpressionIR-record}
${rulegroup-prose: Expr_inst/dataExpressionIR-record}
