[#sec-dataExpression]
=== Data expressions

${syntax: dataElementExpression
          dataExpression
          dataExpressionIR}

[#sec-invalid-header-dataExpression]
==== Invalid header expressions

[[sem-type-check-dataExpression-invalid]]
===== Type checking

${rulegroup: Expr_ok/dataExpression-invalid}
${ruleprose: Expr_ok/dataExpression-invalid}

[[sem-local-compile-time-eval-dataExpressionIR-invalid]]
===== Local compile-time evaluation

${rulegroup: Expr_eval_lctk/dataExpressionIR-invalid}
${ruleprose: Expr_eval_lctk/dataExpressionIR-invalid}

[[sem-compile-time-eval-dataExpressionIR-invalid]]
===== Compile-time evaluation

${rulegroup: Expr_inst/dataExpressionIR-invalid}
${ruleprose: Expr_inst/dataExpressionIR-invalid}

[#sec-sequence-data-expression]
==== Sequence expressions

${syntax: sequenceElementExpression}

[[sem-type-check-dataExpression-sequence]]
===== Type checking

${rulegroup: Expr_ok/dataExpression-sequence}
${ruleprose: Expr_ok/dataExpression-sequence}

[[sem-local-compile-time-eval-dataExpressionIR-sequence]]
===== Local compile-time evaluation

${rulegroup: Expr_eval_lctk/dataExpressionIR-sequence}
${ruleprose: Expr_eval_lctk/dataExpressionIR-sequence}

[[sem-compile-time-eval-dataExpressionIR-sequence]]
===== Compile-time evaluation

${rulegroup: Expr_inst/dataExpressionIR-sequence}
${ruleprose: Expr_inst/dataExpressionIR-sequence}

[#sec-record-data-expression]
==== Record expressions

${syntax: recordElementExpression}

[[sem-type-check-dataExpression-record]]
===== Type checking

${rulegroup: Expr_ok/dataExpression-record}
${ruleprose: Expr_ok/dataExpression-record}

[[sem-local-compile-time-eval-dataExpressionIR-record]]
===== Local compile-time evaluation

${rulegroup: Expr_eval_lctk/dataExpressionIR-record}
${ruleprose: Expr_eval_lctk/dataExpressionIR-record}

[[sem-compile-time-eval-dataExpressionIR-record]]
===== Compile-time evaluation

${rulegroup: Expr_inst/dataExpressionIR-record}
${ruleprose: Expr_inst/dataExpressionIR-record}
