[#sec-accessExpression]
=== Access expressions

${syntax: accessExpression
          accessExpressionIR}

[#sec-errorAccessExpression]
==== Error access expressions

${syntax: errorAccessExpression
          errorAccessExpressionIR}

[[sem-type-check-errorAccessExpression]]
[discrete]
===== Type checking

${rulegroup: Expr_ok/errorAccessExpression}
${ruleprose: Expr_ok/errorAccessExpression}

[[sem-local-compile-time-eval-errorAccessExpression]]
[discrete]
===== Local compile-time evaluation

${rulegroup: Expr_eval_lctk/errorAccessExpressionIR}
${ruleprose: Expr_eval_lctk/errorAccessExpressionIR}

[[sem-compile-time-eval-errorAccessExpression]]
[discrete]
===== Compile-time evaluation

${rulegroup: Expr_inst/errorAccessExpressionIR}
${ruleprose: Expr_inst/errorAccessExpressionIR}

[#sec-memberAccessExpression]
==== Member access expressions

${syntax: memberAccessBase
          memberAccessExpression
          memberAccessBaseIR
          memberAccessExpressionIR}

[#sec-memberAccessExpression-type]
===== Type accesses

[[sem-type-check-memberAccessExpression-type]]
[discrete]
====== Type checking

${rulegroup: Expr_ok/memberAccessExpression-type}
${ruleprose: Expr_ok/memberAccessExpression-type}

[[sem-local-compile-time-eval-memberAccessExpression-type]]
[discrete]
====== Local compile-time evaluation

${rulegroup: Expr_eval_lctk/memberAccessExpressionIR-type}
${ruleprose: Expr_eval_lctk/memberAccessExpressionIR-type}

[[sem-compile-time-eval-memberAccessExpression-type]]
[discrete]
====== Compile-time evaluation

${rulegroup: Expr_inst/memberAccessExpressionIR-type}
${ruleprose: Expr_inst/memberAccessExpressionIR-type}

[#sec-memberAccessExpression-expression]
===== Field accesses

[[sem-expression-check-memberAccessExpression-expression]]
[discrete]
====== Type checking

${rulegroup: Expr_ok/memberAccessExpression-expression}
${ruleprose: Expr_ok/memberAccessExpression-expression}

[[sem-local-compile-time-eval-memberAccessExpression-expression]]
[discrete]
====== Local compile-time evaluation

${rulegroup: Expr_eval_lctk/memberAccessExpressionIR-expression-stack-size}
${ruleprose: Expr_eval_lctk/memberAccessExpressionIR-expression-stack-size}

[[sem-compile-time-eval-memberAccessExpression-expression]]
[discrete]
====== Compile-time evaluation

${rulegroup: Expr_inst/memberAccessExpressionIR-expression-stack-size}
${ruleprose: Expr_inst/memberAccessExpressionIR-expression-stack-size}

[#sec-indexAccessExpression]
==== Index access expressions

${syntax: indexAccessExpression
          indexAccessExpressionIR}

[[sem-type-check-indexAccessExpression]]
[discrete]
===== Type checking

${rulegroup: Expr_ok/indexAccessExpression}
${ruleprose: Expr_ok/indexAccessExpression}

[#sec-sliceAccessExpression]
==== Bitslice access expressions

${syntax: sliceAccessExpression
          sliceAccessExpressionIR}

[[sem-type-check-sliceAccessExpression]]
[discrete]
===== Type checking

${rulegroup: Expr_ok/sliceAccessExpression}
${ruleprose: Expr_ok/sliceAccessExpression}

[[sem-local-compile-time-eval-sliceAccessExpression]]
[discrete]
===== Local compile-time evaluation

${rulegroup: Expr_eval_lctk/sliceAccessExpressionIR}
${ruleprose: Expr_eval_lctk/sliceAccessExpressionIR}

[[sem-compile-time-eval-sliceAccessExpression]]
[discrete]
===== Compile-time evaluation

${rulegroup: Expr_inst/sliceAccessExpressionIR}
${ruleprose: Expr_inst/sliceAccessExpressionIR}
