[#sec-accessExpression]
=== Access expressions

${syntax: accessExpression
          accessExpressionIR}

[#sec-errorAccessExpression]
==== Error access expressions

${syntax: errorAccessExpression
          errorAccessExpressionIR}

[discrete]
===== Type checking

${rulegroup-source: Expr_ok/errorAccessExpression}
${rulegroup-prose: Expr_ok/errorAccessExpression}

[discrete]
===== Local compile-time evaluation

${rulegroup-source: Expr_eval_lctk/errorAccessExpressionIR}
${rulegroup-prose: Expr_eval_lctk/errorAccessExpressionIR}

[discrete]
===== Compile-time evaluation

${rulegroup-source: Expr_inst/errorAccessExpressionIR}
${rulegroup-prose: Expr_inst/errorAccessExpressionIR}

[#sec-memberAccessExpression]
==== Member access expressions

${syntax: memberAccessBase
          memberAccessExpression
          memberAccessBaseIR
          memberAccessExpressionIR}

[#sec-memberAccessExpression-type]
===== Type accesses

[discrete]
====== Type checking

${rulegroup-source: Expr_ok/memberAccessExpression-type}
${rulegroup-prose: Expr_ok/memberAccessExpression-type}

[discrete]
====== Local compile-time evaluation

${rulegroup-source: Expr_eval_lctk/memberAccessExpressionIR-type}
${rulegroup-prose: Expr_eval_lctk/memberAccessExpressionIR-type}

[discrete]
====== Compile-time evaluation

${rulegroup-source: Expr_inst/memberAccessExpressionIR-type}
${rulegroup-prose: Expr_inst/memberAccessExpressionIR-type}

[#sec-memberAccessExpression-expression]
===== Field accesses

[discrete]
====== Type checking

${rulegroup-source: Expr_ok/memberAccessExpression-expression}
${rulegroup-prose: Expr_ok/memberAccessExpression-expression}

[discrete]
====== Local compile-time evaluation

${rulegroup-source: Expr_eval_lctk/memberAccessExpressionIR-typedExpressionIR}
${rulegroup-prose: Expr_eval_lctk/memberAccessExpressionIR-typedExpressionIR}

[discrete]
====== Compile-time evaluation

${rulegroup-source: Expr_inst/memberAccessExpressionIR-typedExpressionIR}
${rulegroup-prose: Expr_inst/memberAccessExpressionIR-typedExpressionIR}

[#sec-indexAccessExpression]
==== Index access expressions

${syntax: indexAccessExpression
          indexAccessExpressionIR}

[discrete]
===== Type checking

${rulegroup-source: Expr_ok/indexAccessExpression}
${rulegroup-prose: Expr_ok/indexAccessExpression}

[#sec-sliceAccessExpression]
==== Bitslice access expressions

${syntax: sliceAccessExpression
          sliceAccessExpressionIR}

[discrete]
===== Type checking

${rulegroup-source: Expr_ok/sliceAccessExpression}
${rulegroup-prose: Expr_ok/sliceAccessExpression}

[discrete]
===== Local compile-time evaluation

${rulegroup-source: Expr_eval_lctk/sliceAccessExpressionIR}
${rulegroup-prose: Expr_eval_lctk/sliceAccessExpressionIR}

[discrete]
===== Compile-time evaluation

${rulegroup-source: Expr_inst/sliceAccessExpressionIR}
${rulegroup-prose: Expr_inst/sliceAccessExpressionIR}
