[#sec-callExpression]
=== Call expressions

${syntax: callableTarget
          constructorTarget
          callTarget
          callExpression
          callableTargetIR
          constructorTargetIR
          callExpressionIR}

[#sec-callExpression-callable]
==== Callable call expressions

[[sem-type-check-callExpression-callable]]
===== Type checking

${rulegroup: Expr_ok/callExpression-callable}
${ruleprose: Expr_ok/callExpression-callable}

[[sem-local-compile-time-eval-callExpressionIR-callable]]
===== Local compile-time evaluation

${rulegroup: Expr_eval_lctk/callExpressionIR-builtin-size}
${ruleprose: Expr_eval_lctk/callExpressionIR-builtin-size}

[[sem-compile-time-eval-callExpressionIR-callable]]
===== Compile-time evaluation

${rulegroup: Expr_inst/callExpressionIR-builtin-size}
${ruleprose: Expr_inst/callExpressionIR-builtin-size}

[#sec-callExpression-constructor]
==== Constructor call expressions

[[sem-type-check-callExpression-constructor]]
===== Type checking

${rulegroup: Expr_ok/callExpression-constructor}
${ruleprose: Expr_ok/callExpression-constructor}

[[sem-compile-time-eval-callExpressionIR-constructor]]
===== Compile-time evaluation

${rulegroup: Expr_ok/callExpression-constructor}
${ruleprose: Expr_ok/callExpression-constructor}

[[sem-compile-time-eval-callExpression-parenthesized]]
==== Parenthesized calls

[[sem-local-compile-time-eval-callExpressionIR-parenthesized]]
===== Local compile-time evaluation

${rulegroup: Expr_eval_lctk/callExpressionIR-parenthesized}
${ruleprose: Expr_eval_lctk/callExpressionIR-parenthesized}

[[sem-compile-time-eval-callExpressionIR-parenthesized]]
===== Compile-time evaluation

${rulegroup: Expr_inst/callExpressionIR-parenthesized}
${ruleprose: Expr_inst/callExpressionIR-parenthesized}
