[#sec-callExpression]
=== Call expressions

${syntax: callableTarget
          constructorTarget
          callTarget
          callExpression
          callableTargetIR
          constructorTargetIR
          callExpressionIR}

[#sec-callExpression-callable]
==== Callable call expressions

[[sem-type-check-callExpression-callable]]
[discrete]
===== Type checking

${rulegroup-source: Expr_ok/callExpression-callable}
${rulegroup-prose: Expr_ok/callExpression-callable}

[[sem-local-compile-time-eval-callExpressionIR-callable]]
[discrete]
===== Local compile-time evaluation

${rulegroup-source: Expr_eval_lctk/callExpressionIR-builtin-size}
${rulegroup-prose: Expr_eval_lctk/callExpressionIR-builtin-size}

[[sem-compile-time-eval-callExpressionIR-callable]]
[discrete]
===== Compile-time evaluation

${rulegroup-source: Expr_inst/callExpressionIR-builtin-size}
${rulegroup-prose: Expr_inst/callExpressionIR-builtin-size}

[#sec-constructor-call-expression]
==== Constructor call expressions

[[sem-type-check-callExpression-constructor]]
[discrete]
===== Type checking

${rulegroup-source: Expr_ok/callExpression-constructor}
${rulegroup-prose: Expr_ok/callExpression-constructor}

[[sem-compile-time-eval-callExpressionIR-constructor]]
[discrete]
===== Compile-time evaluation

${rulegroup-source: Expr_ok/callExpression-constructor}
${rulegroup-prose: Expr_ok/callExpression-constructor}

[[sem-compile-time-eval-callExpression-parenthesized]]
==== Parenthesized calls

[[sem-local-compile-time-eval-callExpressionIR-parenthesized]]
[discrete]
===== Local compile-time evaluation

${rulegroup-source: Expr_eval_lctk/callExpressionIR-parenthesized}
${rulegroup-prose: Expr_eval_lctk/callExpressionIR-parenthesized}

[[sem-compile-time-eval-callExpressionIR-parenthesized]]
[discrete]
===== Compile-time evaluation

${rulegroup-source: Expr_inst/callExpressionIR-parenthesized}
${rulegroup-prose: Expr_inst/callExpressionIR-parenthesized}
