(* Prelude for generated OCaml *)

let prelude =
  {|(* Generated by p4spectec ocaml — do not edit manually *)

[@@@warning "-8-11-26-27-30-32-33-39"]

open Domain
module Value = Runtime.Value
module Typ = Runtime.Type.Typ
module Run = Runtime.Dynamic_Runner.Signature
open Util.Source

exception Unmatch of string

let make_typ_var_ (s : string) (targs_ : Typ.t list) : Typ.t =
  Typ.Make.var {it = s; at = no_region; note = ()} targs_

let make_atom_ (s : string) : Atom.t phrase =
  {it = Atom.Atom s; at = no_region; note = ()}

let make_case_
    (mixop : Mixop.t)
    (payload : Value.t list)
    (typ : Typ.t) : Value.t =
  Value.Make.(mixop <|! payload <<|! typ)

|}
