(* Prelude for generated OCaml *)

let make_opt_splitN (n : int) : string =
  let xs = List.init n (fun i -> "x" ^ string_of_int i) in
  let tuple elems =
    match elems with [ x ] -> x | _ -> "(" ^ String.concat ", " elems ^ ")"
  in
  let somes = xs |> List.map (fun x -> "Some " ^ x) |> tuple in
  let nones = List.init n (fun _ -> "None") |> tuple in
  Format.asprintf "let split%d = function\n| Some %s -> %s\n| None -> %s" n
    (tuple xs) somes nones

let opt_prelude (ctx : Ctx.t) =
  let header = "module Option = struct\ninclude Option\n" in
  let opt_splitNs =
    ctx.preamble.opts |> List.map make_opt_splitN |> String.concat "\n"
  in
  let footer = "\nend" in
  header ^ opt_splitNs ^ footer

let make_list_splitN (n : int) : string =
  let xs = List.init n (fun i -> "x" ^ string_of_int i) in
  let accs = List.init n (fun i -> "acc" ^ string_of_int i) in
  let tuple elems =
    match elems with [ x ] -> x | _ -> "(" ^ String.concat ", " elems ^ ")"
  in
  if n = 1 then "let split1 xs = xs"
  else
    let elem_pat = tuple xs in
    let acc_pat = tuple accs in
    let cons = List.map2 (fun x acc -> x ^ " :: " ^ acc) xs accs |> tuple in
    let init = List.init n (fun _ -> "[]") |> tuple in
    Format.asprintf
      "let split%d xs =\n  List.fold_right (fun %s %s -> %s) xs %s" n elem_pat
      acc_pat cons init

let list_prelude (ctx : Ctx.t) =
  let header = "module List = struct\ninclude List\n" in
  let list_splitNs =
    ctx.preamble.lists |> List.map make_list_splitN |> String.concat "\n"
  in
  let footer = "\nend" in
  header ^ list_splitNs ^ footer

let prelude (ctx : Ctx.t) =
  let common =
    {|(* Generated by p4spectec ocaml — do not edit manually *)

[@@@warning "-8-11-26-27-30-32-33-39"]

open Domain
module Value = Runtime.Value
module Typ = Runtime.Type.Typ
module Run = Runtime.Dynamic_Runner.Signature
open Util.Source

exception Unmatch of string

let make_typ_var_ (s : string) (targs_ : Typ.t list) : Typ.t =
  Typ.Make.var {it = s; at = no_region; note = ()} targs_

let make_atom_ (s : string) : Atom.t phrase =
  {it = Atom.Atom s; at = no_region; note = ()}

let make_case_
    (mixop : Mixop.t)
    (payload : Value.t list)
    (typ : Typ.t) : Value.t =
  Value.Make.(mixop <|! payload <<|! typ)

|}
  in
  let opt_prelude = opt_prelude ctx in
  let list_prelude = list_prelude ctx in
  common ^ opt_prelude ^ "\n" ^ list_prelude
