[#sec-table-key]
==== Table keys

// 903
The `key` is a table property which specifies the data-plane values that
should be used to look up an entry. A key is a list of pairs of the form
`(e : m)`, where `e` is an expression that describes the data to be
matched in the table, and `m` is a `match_kind` that describes the algorithm
used to perform the lookup (see Section <<sec-match-kind>>).

// 904 - Modified
${syntax: tableKeyList tableKey}

// 905
For example, consider the following program fragment:

// 906
----
table Fwd {
    key = {
       ipv4header.dstAddress : ternary;
       ipv4header.version    : exact;
    }
    // more fields omitted
}
----

// 907
Here the key comprises two fields from the `ipv4header`
header: `dstAddress` and `version`. The `match_kind` elements
serve three purposes:

// 908
* They specify the algorithm used to match data-plane values against
  the entries in the table at runtime.
* They are used to synthesize the control-plane API that is used to
  populate the table.
* They are used by the compiler back-end to allocate resources for the
  implementation of the table.

// 909
The P4 core library contains three predefined `match_kind` identifiers:

// 910
[source,p4]
----
match_kind {
   exact,
   ternary,
   lpm
}
----

// 911
These identifiers correspond to the P4~14~ match kinds with the same names. The
semantics of these match kinds is actually not needed to describe the behavior
of the P4 abstract machine; how they are used influences only the control-plane
API and the implementation of the look-up table. From the point of view of the
P4 program, a look-up table is an abstract finite map that is given a key and
produces as a result either an action or a "miss" indication, as described in
<<sec-match-action-table-invocation>>.

// 912
The expected meaning of these values is as follows:

// 913
* an `exact` match kind on a key field means that the value of the field in the
  table specifies exactly the value the lookup key field must have in order to
  match. This is applicable for all legal key fields whose types support
  equality comparisons.
* a `ternary` match kind on a key field means that the field in the table
  specifies a set of values for the key field using a value and a mask. The
  meaning of the `(value, mask)` pair is similar to the P4 mask expressions, as
  described in <<sec-mask-set>>: a key field `k` matches the table entry when
  `k & mask == value & mask`.
* a `lpm` (longest prefix match) match kind on a key field is a specific type of
  `ternary` match where the mask is required to have a form in binary that is a
  contiguous set of 1 bits followed by a contiguous set of 0 bits. Masks with
  more 1 bits have automatically higher priorities. A mask with all bits 0 is
  legal.

// 914
Some table entries, in particular the ones with at least one `ternary` field,
also require a priority value. A priority is a numeric value which is used to
break ties when a particular key belongs to multiple sets. When table entries
are specified in the P4 program the priorities are generated by the compiler;
when entries are specified by the control-plane, the priority may need to be
explicitly specified. Entries with higher priority are matched first. This
specification does not mandate whether "higher" priorities are represented by
higher or lower numeric values; this choice is left to the target
implementation.

// 915
An example specifying entries for a table is given in <<sec-table-entries>>.

// 916
If a table has no `key` property, or if the value of its `key` property is the
empty tuple, i.e. `key = {}`, then it contains no look-up table, just a default
action--i.e., the associated lookup table is always the empty map.

// 917
Each key element can have an optional `@name` annotation which is used to
synthesize the control-plane-visible name for the key field.

// 918
Note some implementations might only support a limited number of keys or a
limited combinations of match_kind for the keys. The implementation should
reject those cases with an error message in this case.

===== Type checking

// Added
A table key property is type checked as follows:

// Added
${rulegroup-latex: TableProperty_ok/key}
${rulegroup-prose: TableProperty_ok/key}

// Added
After type checking, a table key property is represented in P4~IR~ as:

// Added
${syntax: tableKeysPropertyIR tableKeyListIR tableKeyIR}

// Added
Table keys are type checked with the following relation:

// Added
${relation-title-latex: TableKeys_ok}
${relation-title-prose: TableKeys_ok}

// Added
${rulegroup-latex: TableKeys_ok}
${rulegroup-prose: TableKeys_ok}

// Added
The relation invokes the following relation for each key:

// Added
${relation-title-latex: TableKey_ok}
${relation-title-prose: TableKey_ok}

// Added
${rulegroup-latex: TableKey_ok}
${rulegroup-prose: TableKey_ok}

===== Compile-time evaluation

// Added
${rulegroup-latex: TableProperty_inst/tableKeysPropertyIR}
${rulegroup-prose: TableProperty_inst/tableKeysPropertyIR}

===== Runtime evaluation

// Added
A table key is evaluated at runtime as follows:

// Added
${relation-title-latex: TableKey_eval}
${relation-title-prose: TableKey_eval}

// Added
The result of evaluating a table key is:

// Added
${syntax: tableKeyResult tableKeyValue exitResult}

// Added
${rulegroup-latex: TableKey_eval}
${rulegroup-prose: TableKey_eval}

// Added
A list of table keys is evaluated at runtime as follows:

// Added
${relation-title-latex: TableKeys_eval}
${relation-title-prose: TableKeys_eval}

// Added
The result of evaluating table keys is:

// Added
${syntax: tableKeysResult}

// Added
${rulegroup-latex: TableKeys_eval}
${rulegroup-prose: TableKeys_eval}
