[#sec-term]
== Terms, definitions, and symbols

Throughout this document, the following terms will be used:

* *Architecture*: A set of P4-programmable components and the data
  plane interfaces between them.
* *Control plane*: A class of algorithms and the corresponding input
  and output data that are concerned with the provisioning and
  configuration of the data plane.
* *Data plane*: A class of algorithms that describe transformations
  on packets by packet-processing systems.
* *Metadata*: Intermediate data generated during execution of a P4
  program.
* *Packet*: A network packet is a formatted unit of data carried by
  a packet-switched network.
* *Packet header*: Formatted data at the beginning of a packet. A
  given packet may contain a sequence of packet headers representing
  different network protocols.
* *Packet payload*: Packet data that follows the packet headers.
* *Packet-processing system*: A data-processing system designed
 for processing network packets. In general, packet-processing
  systems implement control plane and data plane algorithms.
* *Target*: A packet-processing system capable of executing a P4
  program.

All terms defined explicitly in this document should not be understood
to refer implicitly to similar terms defined elsewhere. Conversely, any terms not
defined explicitly in this document should be interpreted according to
generally recognizable sources---e.g., IETF RFCs.
