(* Stub Dispatch for the [spec_parts] library — copied into [compiled/] by
   `make restore-stub`. Every entry point fails, telling the user to generate
   the real interpreter. Overwritten by `make gen-ocaml`. *)

[@@@warning "-8-11-26-27-30-32-33-39"]

open Util.Source
open Ctx

let eval_func (_name : string) (_typs : Typ.t list) (_args : Value.t list) :
    Run.func_result =
  Fail (no_region, "ML interpreter: run `make gen-ocaml` to generate it")

let eval_rel (_name : string) (_args : Value.t list) : Run.rel_result =
  Fail (no_region, "ML interpreter: run `make gen-ocaml` to generate it")

let eval_program (_relname : string) (_includes : string list) (_path : string)
    : Run.program_result =
  Fail
    (`Runtime
       (no_region, "ML interpreter: run `make gen-ocaml` to generate it"))

(* Typed mixop bridges (C3) — re-exported by the real Dispatch from the generated
   parts. Stubbed here so the [spec_parts] surface stays stable when the stub is
   in place (`make build`). *)

let make_case_typed (_mixop : string) (_args : Obj.t list) (_typ : string) :
    Obj.t =
  failwith "ML interpreter: run `make gen-ocaml` to generate it"

let case_of_typed (_x : Obj.t) (_typ : string) : Obj.t Domain.Mixfix.t =
  failwith "ML interpreter: run `make gen-ocaml` to generate it"

(* Re-export of the generated [marshal_value] (C5d) — the one real marshal
   [V_typed.to_string] needs to print a [value]. Stubbed here for the [build]
   surface. *)

let marshal_value (_x : Obj.t) : Value.t =
  failwith "ML interpreter: run `make gen-ocaml` to generate it"

(* Typename-indexed cold state-persist bridge (C5) — stubbed for the [build]
   surface; the real dispatch is generated by `make gen-ocaml`. *)

let marshal_typed (_typ : string) (_x : Obj.t) : Value.t =
  failwith "ML interpreter: run `make gen-ocaml` to generate it"

let unmarshal_typed (_typ : string) (_v : Value.t) : Obj.t =
  failwith "ML interpreter: run `make gen-ocaml` to generate it"
