[#sec-syntax-and-semantics]
=== Syntax and semantics

==== Grammar

// Section 6.1.1 in the P4-16 Language Specification
The complete grammar of P4~16~ is given in <<sec-grammar>>, using
Yacc/Bison grammar description language. This text is based on the same
grammar. We adopt several standard conventions when we provide excerpts from
the grammar:

* `UPPERCASE` symbols denote terminals in the grammar.
* Excerpts from the grammar are given in BNF notation as follows:

${syntax: p4program}

==== Semantics and the P4 abstract machines

// Section 6.1.2 in the P4-16 Language Specification (modified)
We describe the semantics of P4 in terms of abstract machines executing
traditional imperative code.

P4 compilers are free to reorganize the code they generate in any way as long
as the externally visible behaviors of the P4 programs are preserved as
described by this specification where externally visible behavior is defined
as:

* The input/output behavior of all P4 blocks, and
* The state maintained by extern blocks.

// Added
Throughout this specification, the P4 semantics is described using a combination of:

* P4 code snippets
* Pseudo-code snippets
* Prose algorithms and formal inference rules

===== Pseudo-code snippets

// Section 6.1.1 in the P4-16 Language Specification
Pseudo-code (mostly used for describing the semantics of various P4 constructs)
are shown with fixed-size fonts as in the following example:

[source,p4pseudo]
----
ParserModel.verify(bool condition, error err) {
    if (condition == false) {
        ParserModel.parserError = err;
        goto reject;
    }
}
----

===== Prose algorithms

The semantics of P4 constructs are also described using prose algorithms.
For example, below is the signature of an algorithm used to describe
type checking of P4 expressions.

${relation-title-prose: Expr_ok}

Detailed discussion of what `cursor`, `typingContext`, and `typedExpressionIR`
mean is given in <<sec-type-checking>>. For now, it suffices to know that
`Expr_ok` takes a `cursor`, a `typingContext`, and a `typedExpressionIR` as
inputs and results in a `typedExpressionIR`.

An algorithm is defined in terms of case-analysis, where each case corresponds
to a variant of a P4 construct. For example, the following algorithm defines
how to type check boolean literal expressions.

${rulegroup-prose: Expr_ok/literalExpression-boolean}

And the following algorithm defines type checking of integer literal expressions.

${rulegroup-prose: Expr_ok/literalExpression-number}

And so on for other variants of P4 expressions. These prose algorithms are
presented throughout this specification.

[[option_get]]
====== Prose algorithm shorthands

To make the prose algorithms concise, we often use the shorthand *!*.
Some algorithms result in an optional result to indicate possible failure. The
following example algorithm computes modulo of two natural numbers
(including zero).

${func-prose: modulo}

Because the divisor may be zero, the result is optional. Now consider the case
when the algorithm is called.

${func-prose: modulo_42}

Here, *!* indicates unwrapping of the optional result. This shortened form is
equivalent to first getting the optional result, checking that it is not
`None`, and then unwrapping it.

===== Formal inference rules

Alongside prose algorithms, we also present formal inference rules. In fact,
the prose algorithms are _automatically generated_ from the formal inference
rules. Although the prose algorithms are enough to understand the P4 semantics,
the formal inference rules are included to aid comprehension.

For example, the following formal inference rule defines type checking of
boolean literal expressions.

${rulegroup-source: Expr_ok/literalExpression-boolean}

It is defined using mathematical notations such as turnstile (`|-`). The lines
leading with `--` are called premises.

NOTE: Add more explanation of the formal inference rules here.
