[#sec-syntax-and-semantics]
=== Syntax and semantics

==== Grammar

// Section 6.1.1 in the P4-16 Language Specification
The complete grammar of P4~16~ is given in <<sec-grammar>>, using
Yacc/Bison grammar description language. This text is based on the same
grammar. We adopt several standard conventions when we provide excerpts from
the grammar:

* `UPPERCASE` symbols denote terminals in the grammar.
* Excerpts from the grammar are given in BNF notation as follows:

${syntax: p4program}

// Section 6.1.1 in the P4-16 Language Specification
Pseudo-code (mostly used for describing the semantics of various P4 constructs)
are shown with fixed-size fonts as in the following example:

[source,p4pseudo]
----
ParserModel.verify(bool condition, error err) {
    if (condition == false) {
        ParserModel.parserError = err;
        goto reject;
    }
}
----

==== Semantics and the P4 abstract machines

// Section 6.1.2 in the P4-16 Language Specification (modified)
We describe the semantics of P4 in terms of abstract machines executing
traditional imperative code.

P4 compilers are free to reorganize the code they generate in any way as long
as the externally visible behaviors of the P4 programs are preserved as
described by this specification where externally visible behavior is defined
as:

* The input/output behavior of all P4 blocks, and
* The state maintained by extern blocks.

NOTE: Add explanation on the prose generated by P4-SpecTec.
