[#sec-call-expression]
=== Call expressions

// Added
Call expressions are used to invoke callables or constructors.

// Added
${syntax: callExpression
          callTarget
          callableTarget
          constructorTarget}

// Added
Details of how calls are resolved and evaluated are described in <<sec-call>>.

==== Type checking

// Added
After type checking, call expressions are represented as:

// Added
${syntax: callExpressionIR callableTargetIR constructorTargetIR}

[discrete]
===== Calling a callable

// Added
${rulegroup-latex: Expr_ok/callExpression-callable}
${rulegroup-prose: Expr_ok/callExpression-callable}

// Added
Whether a call is compile-time known, and whether it is a `static_assert` call,
are determined from the callable type with:

// Added
${func-source: is_static_callableTypeIR}
${func-prose: is_static_callableTypeIR}

// Added
${func-source: is_static_assert_callableTypeIR}
${func-prose: is_static_assert_callableTypeIR}

[discrete]
===== Calling a constructor

// Added
${rulegroup-latex: Expr_ok/callExpression-constructor}
${rulegroup-prose: Expr_ok/callExpression-constructor}

==== Local compile-time evaluation

// Added
Certain call expressions can be evaluated during type checking:

// Added
${rulegroup-latex: Expr_eval_lctk/callExpressionIR}
${rulegroup-prose: Expr_eval_lctk/callExpressionIR}

==== Compile-time evaluation

// Added
Call expressions may also be evaluated at compile time when instantiation phase
takes place. A constructor call evaluates to an instance of the constructed
type, while a callable call evaluates to the result of the call.

[discrete]
===== Calling a callable

// Added
${rulegroup-latex: Expr_inst/callExpressionIR-callable}
${rulegroup-prose: Expr_inst/callExpressionIR-callable}

[discrete]
===== Calling a constructor

// Added
${rulegroup-latex: Expr_inst/callExpressionIR-constructor}
${rulegroup-prose: Expr_inst/callExpressionIR-constructor}

[discrete]
===== Parenthesized call

// Added
${rulegroup-latex: Expr_inst/callExpressionIR-parenthesized}
${rulegroup-prose: Expr_inst/callExpressionIR-parenthesized}

==== Runtime evaluation

// Added
${rulegroup-latex: Expr_eval/callExpressionIR}
${rulegroup-prose: Expr_eval/callExpressionIR}
