[#sec-keyset-expression]
=== Keyset expressions

// Added
Keyset expressions are used to represent a set of values to be matched in
switch statements (<<sec-switch-statement>>) and parser select expressions
(<<sec-select-expression>>).

// Added
The following relation defines how keysets are evaluated:

// Added
${relation-title-source: Eval_keyset}
${relation-title-prose: Eval_keyset}

// Added
The result of evaluating a keyset expression is:

// Added
${syntax: keysetExpressionResult}

// Added
The relation works as follows:

// Added
${rulegroup-source: Eval_keyset}
${rulegroup-prose: Eval_keyset}

// Added
It decomposes the `keysetExpressionIR` into ``simpleKeysetExpressionIR``s,
evaluates each of those, and then combines the results into a single
`keysetExpressionResult`.

// Added
The ``simpleKeysetExpressionIR``s are evaluated as follows:

// Added
${relation-title-source: Eval_keysets_simple}
${relation-title-prose: Eval_keysets_simple}

// Added
${rulegroup-source: Eval_keysets_simple}
${rulegroup-prose: Eval_keysets_simple}

// Added
A `simpleKeysetExpressionIR` is evaluated as follows:

// Added
${relation-title-source: Eval_keyset_simple}
${relation-title-prose: Eval_keyset_simple}
${rulegroup-dispatch-prose: Eval_keyset_simple}

// Added
The result of evaluating a `simpleKeysetExpressionIR` is:

// Added
${syntax: simpleKeysetExpressionResult}

[discrete]
====== Expression keys

// Added
${rulegroup-source: Eval_keyset_simple/typedExpressionIR}
${rulegroup-prose: Eval_keyset_simple/typedExpressionIR}

[discrete]
====== Mask keys

${rulegroup-source: Eval_keyset_simple/mask}
${rulegroup-prose: Eval_keyset_simple/mask}

[discrete]
====== Range keys

${rulegroup-source: Eval_keyset_simple/range}
${rulegroup-prose: Eval_keyset_simple/range}

[discrete]
====== Default and don't care keys

${rulegroup-source: Eval_keyset_simple/default-any}
${rulegroup-prose: Eval_keyset_simple/default-any}
