[#sec-extern-object-declaration]
=== Extern object declarations

// Added
An extern object declaration introduces an extern object.

// Added
${syntax: externObjectDeclaration
          externConstructorOrMethodPrototype
          externConstructorOrMethodPrototypeList}

// Added
See <<sec-extern-object>> for how extern objects are internally represented. An
extern object declaration includes its constructors and methods, to be
explained in the following sections.

[#sec-extern-method-declaration]
==== Extern methods

// Added
Extern objects can have methods, which are declared using the following syntax:

// Added
${syntax: externMethodPrototype}

// Added
Whether an extern prototype is a constructor or a method prototype is tested
with:

// Added
${func-source: is_externConstructorPrototype}
${func-prose: is_externConstructorPrototype}

// Added
${func-source: is_externMethodPrototype}
${func-prose: is_externMethodPrototype}

// Added
An extern object body mixes constructor and method prototypes; they are
separated with:

// Added
${func-source: split_externConstructorOrMethodPrototypeList}
${func-prose: split_externConstructorOrMethodPrototypeList}

// Added
See <<sec-extern-method>> for details on how extern methods are represented
internally.

===== Type checking

// Added
Extern methods are type checked using the following relation:

// Added
${relation-title-latex: ExternMethod_ok}
${relation-title-prose: ExternMethod_ok}

// Added
After type checking, in P4~IR~, an extern method declaration is represented as:

// Added
${syntax: externMethodPrototypeIR}

// Added
These are produced by:

// Added
${rulegroup-latex: ExternMethod_ok}
${rulegroup-prose: ExternMethod_ok}

===== Compile-time evaluation

// Added
Extern method declarations are loaded into the context at compile-time by:

// Added
${relation-title-latex: ExternMethod_inst}
${relation-title-prose: ExternMethod_inst}

// Added
${rulegroup-latex: ExternMethod_inst}
${rulegroup-prose: ExternMethod_inst}

// Added
A list of extern method declarations is loaded into the context by:

// Added
${relation-title-latex: ExternMethods_inst}
${relation-title-prose: ExternMethods_inst}

// Added
${rulegroup-latex: ExternMethods_inst}
${rulegroup-prose: ExternMethods_inst}

[#sec-extern-constructor-declaration]
==== Extern constructors

// Added
Extern objects may have constructors, which are declared using the following syntax:

// Added
${syntax: externConstructorPrototype}

===== Type checking

// Added
Extern constructors are type checked using the following relation:

// Added
${relation-title-latex: ExternConstructor_ok}
${relation-title-prose: ExternConstructor_ok}

// Added
After type checking, in P4~IR~, an extern constructor declaration is represented as:

// Added
${syntax: externConstructorPrototypeIR}

// Added
These are produced by:

// Added
${rulegroup-latex: ExternConstructor_ok}
${rulegroup-prose: ExternConstructor_ok}

==== Type checking

// Added
After type checking, an extern object declaration is represented in P4~IR~
as:

${syntax: externObjectDeclarationIR
          externConstructorPrototypeIR
          externMethodPrototypeIR}

// Added
${rulegroup-latex: Decl_ok/externObjectDeclaration}
${rulegroup-prose: Decl_ok/externObjectDeclaration}

// Added
The constructor type definition of a constructor prototype is produced by:

// Added
${func-source: constructorTypeDef_of_externConstructorPrototypeIR}
${func-prose: constructorTypeDef_of_externConstructorPrototypeIR}

==== Compile-time evaluation

// Added
At comile-time, extern object declarations are loaded into the context by:

// Added
${rulegroup-latex: Decl_inst/externObjectDeclarationIR}
${rulegroup-prose: Decl_inst/externObjectDeclarationIR}

// Added
The constructor of a constructor prototype is produced by:

// Added
${func-source: constructor_of_externConstructorPrototypeIR}
${func-prose: constructor_of_externConstructorPrototypeIR}
