[#sec-callable-definitions]
=== Callable definitions (callable constructors)

// Added
Similar to how type declarations introduce type definitions (see
<<sec-type-definitions>>), callable declarations introduce callable
definitions. These are constructors for callable types, that are parameterized
by type parameters (if any).

${syntax: actionTypeDefIR
          functionTypeDefIR
          methodTypeDefIR
          callableTypeDefIR}

When specialized with concrete type arguments, callable type definitions yield callable types:

${syntax: actionTypeIR
          functionTypeIR
          methodTypeIR
          callableTypeIR}

For example, a function declaration introduces a function type definition:

[source,p4]
----
T identity<T>(in T t) { return t; }
----

`identity` is a generic function type definition that falls into:

${syntax: definedFunctionTypeDefIR}

Notice that `definedFunctionTypeDefIR` does _not_ include the function body.
Because callable type definitions are used during type checking, the body of
the callable is not part of the type definition. After specialization with
proper type argument(s), it yields a function type:

${syntax: definedFunctionTypeIR}

[discrete]
==== Well-formedness

// Added
${relation: CallableTypeDef_wf}

${rulegroup: CallableTypeDef_wf}
${ruleprose: CallableTypeDef_wf}
