[#sec-def-functionTypeIR]
[#sec-def-functionDef]
=== Functions

The internal representation of functions and function types is as follows:

${syntax: functionTypeIR
          functionDef}

[#sec-def-functionPrototype]
[#sec-def-functionDeclaration]
[#sec-def-definedFunctionTypeIR]
[#sec-def-definedFunctionDef]
==== User-defined functions

Functions can only be declared at the top level and all parameters must have a direction.
P4 functions are modeled after functions as found in most other programming languages,
but the language does not permit recursive functions.

${syntax: functionPrototype
          functionDeclaration}

Here is an example of a function that returns the maximum of two 32-bit values:

[source,p4]
----
bit<32> max(in bit<32> left, in bit<32> right) {
   return (left > right) ? left : right;
}
----

A function returns a value using the `return` statement.  A function with a
return type of `void` can simply use the `return` statement with no arguments.
A function with a non-void return type must return a value of the suitable type
on all possible execution paths.

User-defined functions are introduced by `function` declarations. Its typing
rule is explained in <<sec-sem-Decl_ok-functionDeclaration>>. Internally,
defined function types are represented as follows:

${syntax: definedFunctionTypeIR}

Also, the runtime representation of a defined function is as follows:

${syntax: definedFunctionDef}

===== Type nesting

${funcprose: nestable_definedFunction}
${funcprose: nestable'_definedFunction}

[#sec-sem-CallableType_wf-definedFunctionTypeIR]
===== Well-formedness

${rulegroup: CallableType_wf/definedFunctionTypeIR}
${ruleprose: CallableType_wf/definedFunctionTypeIR}

[#sec-def-externDeclaration]
[#sec-def-externFunctionTypeIR]
[#sec-def-externFunctionDef]
==== Extern functions

An extern function declaration describes the name and type signature of the
function, but not its implementation.

${syntax: externDeclaration}

Extern functions are introduced by `extern` declarations. Its typing rule is
explained in <<sec-sem-Decl_ok-externFunctionDeclaration>>. Internally,
extern function types are represented as follows:

${syntax: externFunctionTypeIR}

Also, the runtime representation of an extern function is as follows:

${syntax: externFunctionDef}

===== Type nesting

${funcprose: nestable_externFunction}
${funcprose: nestable'_externFunction}

[#sec-sem-CallableType_wf-externFunctionTypeIR]
===== Well-formedness

${rulegroup: CallableType_wf/externFunctionTypeIR}
${ruleprose: CallableType_wf/externFunctionTypeIR}
