[#sec-def-methodTypeIR]
[#sec-def-method]
=== Methods 

The internal representation of methods and method types is as follows:

${syntax: methodTypeIR
          methodDef}

[#sec-def-externMethodTypeIR]
[#sec-def-externMethodDef]
==== Extern methods

Internally, extern methods are represented as follows:

${syntax: externMethodTypeIR
          externMethodDef}

Typical extern object methods are built-in, and are implemented by the target
architecture. P4 programmers can only call such methods.

Some types of extern objects may provide methods that can be implemented by the
P4 programmers.  Such methods are described with the `abstract` keyword prior
to the method definition.  Here is an example:

[source,p4]
----
extern Balancer {
    Balancer();
    // get the number of active flows
    bit<32> getFlowCount();
    // return port index used for load-balancing
    // @param address: IPv4 source address of flow
    abstract bit<4> on_new_flow(in bit<32> address);
}
----

When such an object is instantiated the user has to supply an implementation
of all the `abstract` methods (see <<sec-instantiating-abstract-methods>>).

====== Type nesting

${funcprose: nestable_externMethod}
${funcprose: nestable'_externMethod}

[#sec-sem-CallableType_wf-externMethodTypeIR]
====== Well-formedness

${rulegroup: CallableType_wf/externMethodTypeIR}
${ruleprose: CallableType_wf/externMethodTypeIR}

[#sec-def-parserApplyMethodTypeIR]
[#sec-def-parserApplyMethodDef]
==== Parser apply methods

P4 allows parsers to invoke the services of other parsers, similar to
subroutines. To invoke the services of another parser, the sub-parser must be
first instantiated; the services of an instance are invoked by calling it using
its `apply` method.

The following example shows a sub-parser invocation:

[source,p4]
----
parser callee(packet_in packet, out IPv4 ipv4) { /* body omitted */ }
parser caller(packet_in packet, out Headers h) {
     callee() subparser;  // instance of callee
     state subroutine {
          subparser.apply(packet, h.ipv4);  // invoke sub-parser
          transition accept;  // accept if sub-parser ends in accept state
     }
}
----

A parser apply method is introduced by a ``parser`` declaration. Its typing
rule is explained in <<sec-sem-Decl_ok-parserDeclaration>>. A parser apply
method is represented internally as follows:

${syntax: parserApplyMethodTypeIR
          parserApplyMethodDef}

===== Type nesting

${funcprose: nestable_parserApplyMethod}
${funcprose: nestable'_parserApplyMethod}

[#sec-sem-CallableType_wf-parserApplyMethodTypeIR]
===== Well-formedness

${rulegroup: CallableType_wf/parserApplyMethodTypeIR}
${ruleprose: CallableType_wf/parserApplyMethodTypeIR}

[#sec-def-controlApplyMethodTypeIR]
[#sec-def-controlApplyMethodDef]
==== Control apply methods

P4 allows controls to invoke the services of other controls, similar
to subroutines. To invoke the services of another control, it must be
first instantiated; the services of an instance are invoked by calling
it using its `apply` method.

The following example shows a control invocation:

[source,p4]
----
control Callee(inout IPv4 ipv4) { /* body omitted */ }
control Caller(inout Headers h) {
     Callee() instance;  // instance of callee
     apply {
          instance.apply(h.ipv4);  // invoke control
     }
}
----

A control apply method is introduced by a ``control`` declaration. Its typing
rule is explained in <<sec-sem-Decl_ok-controlDelaration>>. Control apply
methods are represented internally as follows:

${syntax: controlApplyMethodTypeIR
          controlApplyMethodDef}

===== Type nesting

${funcprose: nestable_controlApplyMethod}
${funcprose: nestable'_controlApplyMethod}

[#sec-sem-CallableType_wf-controlApplyMethodTypeIR]
===== Well-formedness

${rulegroup: CallableType_wf/controlApplyMethodTypeIR}
${ruleprose: CallableType_wf/controlApplyMethodTypeIR}

[#sec-def-tableApplyMethodTypeIR]
[#sec-def-tableApplyMethodDef]
==== Table apply methods

A `table` can be invoked by calling its `apply` method. Calling an apply method
on a table instance returns a synthesized table metadata structure, explained in
<<sec-def-tableMetadataTypeIR>>.

A table apply method is introduced by a ``table`` declaration. Its typing
rule is explained in <<sec-sem-ControlLocalDecl_ok-tableDeclaration>>. The
internal representation of a table apply method is as follows:

${syntax: tableApplyMethodTypeIR
          tableApplyMethodDef}

[#sec-sem-CallableType_wf-tableApplyMethodTypeIR]
===== Well-formedness

${rulegroup: CallableType_wf/tableApplyMethodTypeIR}
${ruleprose: CallableType_wf/tableApplyMethodTypeIR}
