[#sec-callStatement]
=== Call statements

${syntax: callStatement
          callStatementIR}

[discrete]
[[sem-type-check-callStatement]]
===== Type checking

${rulegroup: Stmt_ok/callStatement}
${ruleprose: Stmt_ok/callStatement}

[discrete]
[[sem-compile-time-eval-callStatement]]
===== Compile-time evaluation

${rulegroup: Stmt_inst/callStatementIR}
${ruleprose: Stmt_inst/callStatementIR}

[#sec-callStatement-lvalue]
==== L-values

${syntax: lvalue}

[discrete]
[[sem-type-check-callStatement-lvalue]]
===== Type checking

${relation: RoutineTarget_ok}
${relation: RoutineTarget_lvalue_ok}

${rulegroup: RoutineTarget_lvalue_ok}
${ruleprose: RoutineTarget_lvalue_ok}

[discrete]
[[sem-type-check-callStatement-lvalue-referenceExpression]]
====== References

${rulegroup: RoutineTarget_ok/referenceExpression}
${ruleprose: RoutineTarget_ok/referenceExpression}

[discrete]
[[sem-type-check-callStatement-lvalue-member]]
====== Member accesses

${rulegroup: RoutineTarget_ok/memberAccessExpression}
${ruleprose: RoutineTarget_ok/memberAccessExpression}

[discrete]
[[sem-type-check-callStatement-lvalue-parenthesized]]
====== Parenthesized l-values

${rulegroup: RoutineTarget_ok/parenthesizedExpression}
${ruleprose: RoutineTarget_ok/parenthesizedExpression}
