[#sec-blockStatement]
=== Block statements

${syntax: blockElementStatement
          blockStatement
          blockElementStatementIR
          blockStatementIR}

A block statement is denoted by curly braces. It contains a sequence
of statements and declarations, which are executed sequentially. The
declarations (e.g., variables and constants) within a block statement
are only visible within the block.

[discrete]
[[sem-type-check-blockElementStmt]]
===== Type checking

${relation: BlockElementStmt_ok}

${rulegroup: Stmt_ok/blockStatement}
${ruleprose: Stmt_ok/blockStatement}

[discrete]
[[sem-compile-time-eval-blockElementStmt]]
===== Compile-time evaluation

${relation: BlockElementStmt_inst}

${rulegroup: Stmt_inst/blockStatementIR}
${ruleprose: Stmt_inst/blockStatementIR}

[#sec-blockElementStatement-constantDeclaration]
==== Constant declaration statements

${syntax: constantDeclaration
          constantDeclarationIR}

[discrete]
[[sem-type-check-blockElementStatement-constantDeclaration]]
===== Type checking

${rulegroup: BlockElementStmt_ok/constantDeclaration}
${ruleprose: BlockElementStmt_ok/constantDeclaration}

[discrete]
[[sem-compile-time-eval-blockElementStatement-constantDeclaration]]
===== Compile-time evaluation

${rulegroup: BlockElementStmt_inst/constantDeclarationIR}
${ruleprose: BlockElementStmt_inst/constantDeclarationIR}

[#sec-variable-declaration-block-element]
==== Variable declaration statements

${syntax: variableDeclaration
          variableDeclarationIR}

[discrete]
[[sem-type-check-blockElementStatement-variableDeclaration]]
===== Type checking

${rulegroup: BlockElementStmt_ok/variableDeclaration}
${ruleprose: BlockElementStmt_ok/variableDeclaration}

[discrete]
[[sem-compile-time-eval-blockElementStatement-variableDeclaration]]
===== Compile-time evaluation

${rulegroup: BlockElementStmt_inst/variableDeclarationIR}
${ruleprose: BlockElementStmt_inst/variableDeclarationIR}

[#sec-statement-block-element]
==== Block element statements

[discrete]
[[sem-type-check-blockElementStatement-statement]]
===== Type checking

${rulegroup: BlockElementStmt_ok/statement}
${ruleprose: BlockElementStmt_ok/statement}

[discrete]
[[sem-compile-time-eval-blockElementStatement-statement]]
===== Compile-time evaluation

${rulegroup: BlockElementStmt_inst/statementIR}
${ruleprose: BlockElementStmt_inst/statementIR}
