[#sec-extern-declaration]
=== Extern declaration

An extern function declaration describes the name and type signature of the
function, but not its implementation.

${syntax: externDeclaration
          externDeclarationIR}

For an example of an `extern` function declaration, see <<sec-function-type>>.

[#sec-externFunctionDeclaration]
==== Extern function declaration

${syntax: externFunctionDeclaration
          externFunctionDeclarationIR}

[[sem-type-check-externFunctionDeclaration]]
===== Type checking

${rulegroup: Decl_ok/externFunctionDeclaration}
${ruleprose: Decl_ok/externFunctionDeclaration}

[[sem-compile-time-eval-externFunctionDeclaration]]
===== Compile-time evaluation

${rulegroup: Decl_inst/externFunctionDeclarationIR}
${ruleprose: Decl_inst/externFunctionDeclarationIR}

[#sec-externObjectDeclaration]
==== Extern object declaration

An extern object declaration declares an object and all methods that can be
invoked to perform computations and to alter the state of the object. Extern
object declarations can also optionally declare constructor methods; these must
have the same name as the enclosing `extern` type, no type parameters, and no
return type.  Extern declarations may only appear as allowed by the
architecture model and may be specific to a target.

${syntax: methodPrototype
          externObjectDeclaration
          methodPrototypeIR
          externObjectDeclarationIR}

For example, the P4 core library introduces two extern objects `packet_in` and
`packet_out` used for manipulating packets (see <<sec-packet-data-extraction>>
and <<sec-deparse>>). Here is an example showing how the methods of these
objects can be invoked on a packet:

[source,p4]
----
extern packet_out {
    void emit<T>(in T hdr);
}
control d(packet_out b, in Hdr h) {
    apply {
        b.emit(h.ipv4);       // write ipv4 header into output packet
    }                         // by calling emit method
}
----

[[sem-type-check-externObjectDeclaration]]
===== Type checking

${rulegroup: Decl_ok/externObjectDeclaration}
${ruleprose: Decl_ok/externObjectDeclaration}

[[sem-compile-time-eval-externObjectDeclaration]]
===== Compile-time evaluation

${rulegroup: Decl_inst/externObjectDeclarationIR}
${ruleprose: Decl_inst/externObjectDeclarationIR}
