[#sec-extern-declaration]
=== Extern declaration

An extern function declaration describes the name and type signature of the
function, but not its implementation.

${syntax: externDeclaration
          externDeclarationIR}

For an example of an `extern` function declaration, see <<sec-function-type>>.

[#sec-externFunctionDeclaration]
==== Extern function declaration

${syntax: externFunctionDeclaration
          externFunctionDeclarationIR}

[[sem-type-check-externFunctionDeclaration]]
===== Type checking

${rulegroup: Decl_ok/externFunctionDeclaration}
${ruleprose: Decl_ok/externFunctionDeclaration}

[[sem-compile-time-eval-externFunctionDeclaration]]
===== Compile-time evaluation

${rulegroup: Decl_inst/externFunctionDeclarationIR}
${ruleprose: Decl_inst/externFunctionDeclarationIR}

[#sec-externObjectDeclaration]
==== Extern object declaration

[[sem-type-check-externObjectDeclaration]]
===== Type checking

${rulegroup: Decl_ok/externObjectDeclaration}
${ruleprose: Decl_ok/externObjectDeclaration}

[[sem-compile-time-eval-externObjectDeclaration]]
===== Compile-time evaluation

${rulegroup: Decl_inst/externObjectDeclarationIR}
${ruleprose: Decl_inst/externObjectDeclarationIR}
