[#sec-typeDeclaration]
=== Type declaration

${syntax: derivedTypeDeclaration
          typedefDeclaration
          typeDeclaration
          derivedTypeDeclarationIR
          typedefDeclarationIR
          typeDeclarationIR}

[#sec-enumTypeDeclaration]
==== Enum type declaration

An enumeration type is defined using the following syntax:

${syntax: enumTypeDeclaration
          enumTypeDeclarationIR}

[#sec-enumTypeDeclaration-non-serializable]
===== Enum type declaration without an underlying type

[#sec-sem-Decl_ok-enumTypeDeclaration-non-serializable]
====== Type checking

${rulegroup: Decl_ok/enumTypeDeclaration-non-serializable}
${ruleprose: Decl_ok/enumTypeDeclaration-non-serializable}

[#sec-sem-Decl_inst-enumTypeDeclarationIR-non-serializable]
====== Compile-time evaluation

${rulegroup: Decl_inst/enumTypeDeclarationIR-non-serializable}
${ruleprose: Decl_inst/enumTypeDeclarationIR-non-serializable}

[#sec-enumTypeDeclaration-serializable]
===== Enum type declaration with an underlying type

[#sec-sem-Decl_ok-enumTypeDeclaration-serializable]
====== Type checking

${rulegroup: Enum_serializable_field_ok}
${ruleprose: Enum_serializable_field_ok}

${rulegroup: Decl_ok/enumTypeDeclaration-serializable}
${ruleprose: Decl_ok/enumTypeDeclaration-serializable}

[#sec-sem-Decl_inst-enumTypeDeclarationIR-serializable]
====== Compile-time evaluation

${rulegroup: Decl_inst/enumTypeDeclarationIR-serializable}
${ruleprose: Decl_inst/enumTypeDeclarationIR-serializable}

[#sec-struct-type-declaration]
==== Struct type declaration

[#sec-sem-Decl_ok-structTypeDeclaration]
===== Type checking

${rulegroup: Decl_ok/structTypeDeclaration}
${ruleprose: Decl_ok/structTypeDeclaration}

[#sec-sem-Decl_inst-structTypeDeclarationIR]
===== Compile-time evaluation

${rulegroup: Decl_inst/structTypeDeclarationIR}
${ruleprose: Decl_inst/structTypeDeclarationIR}

[#sec-headerTypeDeclaration]
==== Header type declaration

[#sec-sem-Decl_ok-headerTypeDeclaration]
===== Type checking

${rulegroup: Decl_ok/headerTypeDeclaration}
${ruleprose: Decl_ok/headerTypeDeclaration}

[#sec-sem-Decl_inst-headerTypeDeclarationIR]
===== Compile-time evaluation

${rulegroup: Decl_inst/headerTypeDeclarationIR}
${ruleprose: Decl_inst/headerTypeDeclarationIR}

[#sec-headerUnionTypeDeclaration]
==== Header union type declaration

[#sec-sem-Decl_ok-headerUnionTypeDeclaration]
===== Type checking

${rulegroup: Decl_ok/headerUnionTypeDeclaration}
${ruleprose: Decl_ok/headerUnionTypeDeclaration}

[#sec-sem-Decl_inst-headerUnionTypeDeclarationIR]
===== Compile-time evaluation

${rulegroup: Decl_inst/headerUnionTypeDeclarationIR}
${ruleprose: Decl_inst/headerUnionTypeDeclarationIR}

[#sec-typdefTypeDeclaration]
==== Typedef declaration

${syntax: typedef
          typedefDeclaration
          typedefIR
          typedefDeclarationIR}

===== `typedef` declaration

[#sec-sem-Decl_ok-typedefDeclaration-typedef]
====== Type checking

${rulegroup: Decl_ok/typedefDeclaration-typedef}
${ruleprose: Decl_ok/typedefDeclaration-typedef}

[#sec-sem-Decl_inst-typedefDeclarationIR-typedef]
====== Compile-time evaluation

${rulegroup: Decl_inst/typedefDeclarationIR-typedef}
${ruleprose: Decl_inst/typedefDeclarationIR-typedef}

===== New type declaration

[#sec-sem-Decl_ok-typedefDeclaration-newtype]
====== Type checking

${rulegroup: Decl_ok/typedefDeclaration-newtype}
${ruleprose: Decl_ok/typedefDeclaration-newtype}

[#sec-sem-Decl_inst-typedefDeclarationIR-newtype]
====== Compile-time evaluation

${rulegroup: Decl_inst/typedefDeclarationIR-newtype}
${ruleprose: Decl_inst/typedefDeclarationIR-newtype}

[#sec-parserTypeDeclaration]
==== Parser type declaration

[#sec-sem-Decl_ok-parserTypeDeclaration]
===== Type checking

${rulegroup: Decl_ok/parserTypeDeclaration}
${ruleprose: Decl_ok/parserTypeDeclaration}

[$sec-sem-Decl_inst-parserTypeDeclarationIR]
===== Compile-time evaluation

${rulegroup: Decl_inst/parserTypeDeclarationIR}
${ruleprose: Decl_inst/parserTypeDeclarationIR}

[#sec-controlTypeDeclaration]
==== Control type declaration

[#sec-sem-Decl_ok-controlTypeDeclaration]
===== Type checking

${rulegroup: Decl_ok/controlTypeDeclaration}
${ruleprose: Decl_ok/controlTypeDeclaration}

[#sec-sem-Decl_inst-controlTypeDeclarationIR]
===== Compile-time evaluation

${rulegroup: Decl_inst/controlTypeDeclarationIR}
${ruleprose: Decl_inst/controlTypeDeclarationIR}

[#sec-packageTypeDeclaration]
==== Package type declaration

[#sec-sem-Decl_ok-packageTypeDeclaration]
===== Type checking

${rulegroup: Decl_ok/packageTypeDeclaration}
${ruleprose: Decl_ok/packageTypeDeclaration}

[#sec-sem-Decl_inst-packageTypeDeclarationIR]
===== Compile-time evaluation

${rulegroup: Decl_inst/packageTypeDeclarationIR}
${ruleprose: Decl_inst/packageTypeDeclarationIR}
