[#sec-typeDeclaration]
=== Type declaration

${syntax: derivedTypeDeclaration
          typedefDeclaration
          typeDeclaration
          derivedTypeDeclarationIR
          typedefDeclarationIR
          typeDeclarationIR}

[#sec-enumTypeDeclaration]
==== Enum type declaration

An enumeration type is defined using the following syntax:

${syntax: enumTypeDeclaration
          enumTypeDeclarationIR}

[#sec-enumTypeDeclaration-non-serializable]
===== Enum type declaration without an underlying type

[[sem-type-check-enumTypeDeclaration-non-serializable]]
====== Type checking

${rulegroup: Decl_ok/enumTypeDeclaration-non-serializable}
${ruleprose: Decl_ok/enumTypeDeclaration-non-serializable}

[[sem-compile-time-enumTypeDeclaration-non-serializable]]
====== Compile-time evaluation

${rulegroup: Decl_inst/enumTypeDeclarationIR-non-serializable}
${ruleprose: Decl_inst/enumTypeDeclarationIR-non-serializable}

[#sec-enumTypeDeclaration-serializable]
===== Enum type declaration with an underlying type

[[sem-type-check-enumTypeDeclaration-serializable]]
====== Type checking

${rulegroup: Enum_serializable_field_ok}
${ruleprose: Enum_serializable_field_ok}

${rulegroup: Decl_ok/enumTypeDeclaration-serializable}
${ruleprose: Decl_ok/enumTypeDeclaration-serializable}

[[sem-compile-time-enumTypeDeclaration-serializable]]
====== Compile-time evaluation

${rulegroup: Decl_inst/enumTypeDeclarationIR-serializable}
${ruleprose: Decl_inst/enumTypeDeclarationIR-serializable}

[#sec-struct-type-declaration]
==== Struct type declaration

[[sem-type-check-structTypeDeclaration]]
===== Type checking

${rulegroup: Decl_ok/structTypeDeclaration}
${ruleprose: Decl_ok/structTypeDeclaration}

[[sem-compile-time-eval-structTypeDeclaration]]
===== Compile-time evaluation

${rulegroup: Decl_inst/structTypeDeclarationIR}
${ruleprose: Decl_inst/structTypeDeclarationIR}

[#sec-headerTypeDeclaration]
==== Header type declaration

[[sem-type-check-headerTypeDeclaration]]
===== Type checking

${rulegroup: Decl_ok/headerTypeDeclaration}
${ruleprose: Decl_ok/headerTypeDeclaration}

[[sem-compile-time-eval-headerTypeDeclaration]]
===== Compile-time evaluation

${rulegroup: Decl_inst/headerTypeDeclarationIR}
${ruleprose: Decl_inst/headerTypeDeclarationIR}

[#sec-headerUnionTypeDeclaration]
==== Header union type declaration

[[sem-type-check-headerUnionTypeDeclaration]]
===== Type checking

${rulegroup: Decl_ok/headerUnionTypeDeclaration}
${ruleprose: Decl_ok/headerUnionTypeDeclaration}

[[sem-compile-time-eval-headerUnionTypeDeclaration]]
===== Compile-time evaluation

${rulegroup: Decl_inst/headerUnionTypeDeclarationIR}
${ruleprose: Decl_inst/headerUnionTypeDeclarationIR}

[#sec-typdefTypeDeclaration]
==== Typedef declaration

${syntax: typedef
          typedefDeclaration
          typedefIR
          typedefDeclarationIR}

===== `typedef` declaration

[[sem-type-check-typedefDeclaration-typedef]]
====== Type checking

${rulegroup: Decl_ok/typedefDeclaration-typedef}
${ruleprose: Decl_ok/typedefDeclaration-typedef}

[[sem-compile-time-eval-typedefDeclaration-typedef]]
====== Compile-time evaluation

${rulegroup: Decl_inst/typedefDeclarationIR-typedef}
${ruleprose: Decl_inst/typedefDeclarationIR-typedef}

===== New type declaration

[[sem-type-check-typedefDeclaration-newtype]]
====== Type checking

${rulegroup: Decl_ok/typedefDeclaration-newtype}
${ruleprose: Decl_ok/typedefDeclaration-newtype}

[[sem-compile-time-eval-typedefDeclaration-newtype]]
====== Compile-time evaluation

${rulegroup: Decl_inst/typedefDeclarationIR-newtype}
${ruleprose: Decl_inst/typedefDeclarationIR-newtype}

[#sec-parser-type-declaration]
==== Parser type declaration

[[sem-type-check-parserTypeDeclaration]]
===== Type checking

${rulegroup: Decl_ok/parserTypeDeclaration}
${ruleprose: Decl_ok/parserTypeDeclaration}

[[sem-compile-time-eval-parserTypeDeclaration]]
===== Compile-time evaluation

${rulegroup: Decl_inst/parserTypeDeclarationIR}
${ruleprose: Decl_inst/parserTypeDeclarationIR}

[#sec-controlTypeDeclaration]
==== Control type declaration

[[sem-type-check-controlTypeDeclaration]]
===== Type checking

${rulegroup: Decl_ok/controlTypeDeclaration}
${ruleprose: Decl_ok/controlTypeDeclaration}

[[sem-compile-time-eval-controlTypeDeclaration]]
===== Compile-time evaluation

${rulegroup: Decl_inst/controlTypeDeclarationIR}
${ruleprose: Decl_inst/controlTypeDeclarationIR}

[#sec-packageTypeDeclaration]
==== Package type declaration

[[sem-type-check-packageTypeDeclaration]]
===== Type checking

${rulegroup: Decl_ok/packageTypeDeclaration}
${ruleprose: Decl_ok/packageTypeDeclaration}

[[sem-compile-time-eval-packageTypeDeclaration]]
===== Compile-time evaluation

${rulegroup: Decl_inst/packageTypeDeclarationIR}
${ruleprose: Decl_inst/packageTypeDeclarationIR}
