[#sec-block-statement]
=== Block statements

// 711
A block statement is denoted by curly braces. It contains a sequence of
statements and declarations, which are executed sequentially. The declarations
(e.g., variables and constants) within a block statement are only visible
within the block.

// 712 - Modified
${syntax: blockStatement blockElementStatementList blockElementStatement}

==== Type checking

// Added
After type checking, block statements are represented in P4~IR~ as:

// Added
${syntax: blockStatementIR blockElementStatementListIR blockElementStatementIR}

// Added
${rulegroup-latex: Stmt_ok/blockStatement}
${rulegroup-prose: Stmt_ok/blockStatement}

// Added
A block is type checked by the relation:

// Added
${relation-title-latex: Block_ok}
${relation-title-prose: Block_ok}

// Added
${rulegroup-latex: Block_ok}
${rulegroup-prose: Block_ok}

// Added
A statement or declaration within a block statement is type checked by the
relation:

// Added
${relation-title-latex: BlockElementStmt_ok}
${relation-title-prose: BlockElementStmt_ok}

// Added
${rulegroup-latex: BlockElementStmt_ok}
${rulegroup-prose: BlockElementStmt_ok}

// Added
A list of block elements is type checked by the relation:

// Added
${relation-title-latex: BlockElementStmtList_ok}
${relation-title-prose: BlockElementStmtList_ok}

// Added
${rulegroup-latex: BlockElementStmtList_ok}
${rulegroup-prose: BlockElementStmtList_ok}

// Added
${relation-title-latex: BlockElementStmts_ok}
${relation-title-prose: BlockElementStmts_ok}

// Added
${rulegroup-latex: BlockElementStmts_ok}
${rulegroup-prose: BlockElementStmts_ok}

==== Compile-time evaluation

// Added
${rulegroup-latex: Stmt_inst/blockStatementIR}
${rulegroup-prose: Stmt_inst/blockStatementIR}

// Added
A block is compile-time evaluated by the relation:

// Added
${relation-title-latex: Block_inst}
${relation-title-prose: Block_inst}

// Added
${rulegroup-latex: Block_inst}
${rulegroup-prose: Block_inst}

// Added
A block element is compile-time evaluated by the relation:

// Added
${relation-title-latex: BlockElementStmt_inst}
${relation-title-prose: BlockElementStmt_inst}

// Added
${rulegroup-latex: BlockElementStmt_inst}
${rulegroup-prose: BlockElementStmt_inst}

// Added
A list of block elements is compile-time evaluated by the relation:

// Added
${relation-title-latex: BlockElementStmtList_inst}
${relation-title-prose: BlockElementStmtList_inst}

// Added
${rulegroup-latex: BlockElementStmtList_inst}
${rulegroup-prose: BlockElementStmtList_inst}

==== Runtime evaluation

// Added
${rulegroup-latex: Stmt_eval/blockStatementIR}
${rulegroup-prose: Stmt_eval/blockStatementIR}

// Added
A block is runtime evaluated by the relation:

// Added
${relation-title-latex: Block_eval}
${relation-title-prose: Block_eval}

// Added
${rulegroup-latex: Block_eval}
${rulegroup-prose: Block_eval}

// Added
A block element is runtime evaluated by the relation:

// Added
${relation-title-latex: BlockElementStmt_eval}
${relation-title-prose: BlockElementStmt_eval}

// Added
${rulegroup-latex: BlockElementStmt_eval}
${rulegroup-prose: BlockElementStmt_eval}

// Added
A list of block elements is runtime evaluated by the relation:

// Added
${relation-title-latex: BlockElementStmtList_eval}
${relation-title-prose: BlockElementStmtList_eval}

// Added
${rulegroup-latex: BlockElementStmtList_eval}
${rulegroup-prose: BlockElementStmtList_eval}
