[#sec-switch-statement]
=== Switch statements

// 727
The `switch` statement can only be used within `control` blocks, `action`
bodies, or function bodies.

// 728 - Modified
${syntax: switchStatement
          switchCaseList
          switchCase
          switchLabel}

// 729
The `expressionNonBrace` is the same as `expression` as defined in
<<sec-expression>>, except it does not include any cases that can begin with a
left brace `{` character, to avoid syntactic ambiguity with a block statement.

// Added
`expressionNonBrace` and `expression` can be converted to each other by:

// Added
${func-source: expressionNonBrace_as_expression}
${func-prose: expressionNonBrace_as_expression}

// Added
${func-source: expression_as_expressionNonBrace}
${func-prose: expression_as_expressionNonBrace}

// 730
There are two kinds of `switch` expressions allowed, described separately in
the following two subsections.

==== Notes common to all switch statements

// 738
It is a compile-time error if two labels of a `switch` statement equal each
other. The switch label values need not include all possible values of the
switch expression. It is optional to have a `switch` case with the `default`
label, but if one is present, it must be the last one in the `switch`
statement.

// Added
The requirement that any `default` label appear last is checked with:

// Added
${func-source: check_switchLabelIR_default}
${func-prose: check_switchLabelIR_default}

// 739
If a switch label is not followed by a block statement, it falls through to the
next label. However, if a block statement is present, it does not fall through.
Note that this is different from C-style `switch` statements, where a `break`
is needed to prevent fall-through. If the last switch label is not followed by
a block statement, the behavior is the same as if the last switch label were
followed by an empty block statement `{ }`.

// Added
The label of a switch case, and whether a case is non-fall-through (that is, has
a block statement), are obtained with:

// Added
${func-source: switchLabelIR_of_switchCaseIR}
${func-prose: switchLabelIR_of_switchCaseIR}

// Added
${func-source: is_non_fallthrough_switchCaseIR}
${func-prose: is_non_fallthrough_switchCaseIR}

// 740
When a `switch` statement is executed, first the switch expression is
evaluated, and any side effects from evaluating this expression are visible to
any `switch` case that is executed. Among switch labels that are not `default`,
at most one of them can equal the value of the switch expression. If one is
equal, that switch case is executed.

// 741
If no labels are equal to the `switch` expression, then:

// 742
* if there is a `default` label, the case with the `default` label is
  executed.
* if there is no `default` label, then no switch case is executed, and
  execution continues after the end of the `switch` statement, with no side
  effects (except any that were caused by evaluating the `switch` expression).

// 743
See "Implementing generalized P4_16 switch statements" for possible techniques
that one might use to implement generalized switch
statements.footnote:GeneralizedSwitchStatements[<https://github.com/p4lang/p4-spec/blob/master/p4-16/spec/docs/implementing-generalized-switch-statements.md>]

[#sec-switch-statement-table]
==== Switch statement on match-action table result

// 731
This type of `switch` statement can only be used within control `apply` blocks.
For this variant of `switch` statement, the expression must be of the form
`t.apply().action_run`, where `t` is the name of a table (see
<<sec-match-action-table-invocation>>). All switch labels must be names of
actions of the table `t`, or `default`.

// 732
[source,p4]
----
switch (t.apply().action_run) {
   action1:                         // fall-through to action2:
   action2: { /* body omitted */ }
   action3: { /* body omitted */ }  // no fall-through from action2 to action3 labels
   default: { /* body omitted */ }
}
----

// 733
Note that the `default` label of the `switch` statement is used to match on the
kind of action executed, no matter whether there was a table hit or miss. The
`default` label does not indicate that the table missed and the
`default_action` was executed.

===== Type checking

// Added
${relation-title-source: Switch_table_ok}
${relation-title-prose: Switch_table_ok}

// Added
${rulegroup-source: Switch_table_ok}
${rulegroup-prose: Switch_table_ok}

// Added
Switch cases are type checked with the relation:

// Added
${relation-title-source: SwitchCaseList_table_ok}
${relation-title-prose: SwitchCaseList_table_ok}

// Added
${rulegroup-source: SwitchCaseList_table_ok}
${rulegroup-prose: SwitchCaseList_table_ok}

// Added
${relation-title-source: SwitchCases_table_ok}
${relation-title-prose: SwitchCases_table_ok}

// Added
${rulegroup-source: SwitchCases_table_ok}
${rulegroup-prose: SwitchCases_table_ok}

// Added
A switch case is type checked with:

// Added
${relation-title-source: SwitchCase_table_ok}
${relation-title-prose: SwitchCase_table_ok}

// Added
${rulegroup-source: SwitchCase_table_ok}
${rulegroup-prose: SwitchCase_table_ok}

// Added
A switch label is type checked with:

// Added
${relation-title-source: SwitchLabel_table_ok}
${relation-title-prose: SwitchLabel_table_ok}

// Added
${rulegroup-source: SwitchLabel_table_ok}
${rulegroup-prose: SwitchLabel_table_ok}

===== Runtime evaluation

// Added
${relation-title-source: Switch_table_eval}
${relation-title-prose: Switch_table_eval}

// Added
${rulegroup-source: Switch_table_eval}
${rulegroup-prose: Switch_table_eval}

// Added
Switch cases are runtime evaluated with the relation:

// Added
${relation-title-source: SwitchCases_table_eval}
${relation-title-prose: SwitchCases_table_eval}

// Added
${rulegroup-source: SwitchCases_table_eval}
${rulegroup-prose: SwitchCases_table_eval}

// Added
A table switch label is matched against the executed action with:

// Added
${func-source: match_switchLabelIR_table}
${func-prose: match_switchLabelIR_table}

[#sec-switch-statement-general]
==== Switch statement on numeric or enumerated type

// 734
For this variant of `switch` statement, the expression must evaluate to a
result with one of these types:

// 735
* `bit<W>`
* `int<W>`
* `enum`, either with or without an underlying representation specified
* `error`

// 736
All switch labels must be expressions with compile-time known values, and must
have a type that can be implicitly cast to the type of the `switch` expression
(see <<sec-implicit-casts>>). Switch labels must not begin with a left brace
character `{`, to avoid ambiguity with a block statement.

// 737
[source,p4]
----
// Assume the expression hdr.ethernet.etherType has type bit<16>.
switch (hdr.ethernet.etherType) {
   0x86dd: { /* body omitted */ }
   0x0800: // fall-through to the next body
   0x0802: { /* body omitted */ }
   0xcafe: { /* body omitted */ }
   default: { /* body omitted */ }
}
----

===== Type checking

// Added
${relation-title-source: Switch_general_ok}
${relation-title-prose: Switch_general_ok}

// Added
${rulegroup-source: Switch_general_ok}
${rulegroup-prose: Switch_general_ok}

// Added
Switch cases are type checked with the relation:

// Added
${relation-title-source: SwitchCaseList_general_ok}
${relation-title-prose: SwitchCaseList_general_ok}

// Added
${rulegroup-source: SwitchCaseList_general_ok}
${rulegroup-prose: SwitchCaseList_general_ok}

// Added
${relation-title-source: SwitchCases_general_ok}
${relation-title-prose: SwitchCases_general_ok}

// Added
${rulegroup-source: SwitchCases_general_ok}
${rulegroup-prose: SwitchCases_general_ok}

// Added
A switch case is type checked with:

// Added
${relation-title-source: SwitchCase_general_ok}
${relation-title-prose: SwitchCase_general_ok}

// Added
${rulegroup-source: SwitchCase_general_ok}
${rulegroup-prose: SwitchCase_general_ok}

// Added
A switch label is type checked with:

// Added
${relation-title-source: SwitchLabel_general_ok}
${relation-title-prose: SwitchLabel_general_ok}

// Added
${rulegroup-source: SwitchLabel_general_ok}
${rulegroup-prose: SwitchLabel_general_ok}

===== Runtime evaluation

// Added
${relation-title-source: Switch_general_eval}
${relation-title-prose: Switch_general_eval}

// Added
${rulegroup-source: Switch_general_eval}
${rulegroup-prose: Switch_general_eval}

// Added
Switch cases are runtime evaluated with the relation:

// Added
${relation-title-source: SwitchCases_general_eval}
${relation-title-prose: SwitchCases_general_eval}

// Added
${rulegroup-source: SwitchCases_general_eval}
${rulegroup-prose: SwitchCases_general_eval}

// Added
A switch label is runtime evaluated with:

// Added
${relation-title-source: SwitchLabel_general_eval}
${relation-title-prose: SwitchLabel_general_eval}

// Added
${rulegroup-source: SwitchLabel_general_eval}
${rulegroup-prose: SwitchLabel_general_eval}

// Added
A general switch label is matched against the switch value with:

// Added
${func-source: match_switchLabelIR_general}
${func-prose: match_switchLabelIR_general}

==== Type checking

// Added
${rulegroup-source: Stmt_ok/switchStatement}
${rulegroup-prose: Stmt_ok/switchStatement}

==== Compile-time evaluation

// Added
${rulegroup-source: Stmt_inst/switchStatementIR}
${rulegroup-prose: Stmt_inst/switchStatementIR}

// Added
The compile-time evaluation of switch cases is defined with the relation:

// Added
${relation-title-source: SwitchCases_inst}
${relation-title-prose: SwitchCases_inst}

// Added
${rulegroup-source: SwitchCases_inst}
${rulegroup-prose: SwitchCases_inst}

// Added
A switch case is compile-time evaluated with:

// Added
${relation-title-source: SwitchCase_inst}
${relation-title-prose: SwitchCase_inst}

// Added
${rulegroup-source: SwitchCase_inst}
${rulegroup-prose: SwitchCase_inst}

==== Runtime evaluation

// Added
${rulegroup-source: Stmt_eval/switchStatementIR}
${rulegroup-prose: Stmt_eval/switchStatementIR}
