[#sec-statement]
== Statements

// Added
The syntax of statements is defined as follows:

// Added
${syntax: statement}

=== Semantics of statements

==== Type checking

// Added
${relation-title-source: Stmt_ok}
${relation-title-prose: Stmt_ok}
${rulegroup-dispatch-prose: Stmt_ok}

// Added
After type checking, statements are represented in P4~IR~ as follows:

// Added
${syntax: statementIR}

// Added
Within the typing context, in order to statically determine the control flow of
a P4 program (e.g., whether a function body always returns), the following
indicator for abstract control flow is used:

// Added
${syntax: flow}

// Added
When two control-flow branches merge, their flows are joined:

// Added
${func-source: join_flow}
${func-prose: join_flow}

// Added
The control flow of two branches of the typing context is joined, and the
control flow recorded in the context is updated, with:

// Added
${func-source: join_control_t}
${func-prose: join_control_t}

// Added
${func-source: set_control_t}
${func-prose: set_control_t}

// Added
As a marker of whether a statement is nested inside a loop, the following
indicator is used:

// Added
${syntax: loop}

// Added
Entering a loop and updating the loop marker of the context are handled with:

// Added
${func-source: enter_loop_t}
${func-prose: enter_loop_t}

// Added
${func-source: set_loop_t}
${func-prose: set_loop_t}

==== Compile-time evaluation

// Added
${relation-title-source: Stmt_inst}
${relation-title-prose: Stmt_inst}
${rulegroup-dispatch-prose: Stmt_inst}

// Added
Instantiations nested within statements are processed according to the above
relation.

==== Runtime evaluation

// Added
${relation-title-source: Stmt_eval}
${relation-title-prose: Stmt_eval}
${rulegroup-dispatch-prose: Stmt_eval}

// Added
The result of evaluating a statement is represented as follows:

// Added
${syntax: statementResult
          continueEmptyResult}

// Added
The following is the result of evaluating a call statement:

// Added
${syntax: callResult
          abortResult
          returnResult
          exitResult
          rejectTransitionResult}

// Added
The following is the result of evaluating a for statement:

// Added
${syntax: forResult
          forBreakResult
          forContinueResult}

// Added
The subsequent sections describe each kind of statement in detail.

include::01-empty-statement.adoc[]
include::02-assignment-statement.adoc[]
include::03-call-statement.adoc[]
include::04-direct-application-statement.adoc[]
include::05-return-statement.adoc[]
include::06-exit-statement.adoc[]
include::07-block-statement.adoc[]
include::08-conditional-statement.adoc[]
include::09-for-statement.adoc[]
include::10-break-statement.adoc[]
include::11-continue-statement.adoc[]
include::12-switch-statement.adoc[]
