[#sec-scoping]
=== Scoping

${syntax: cursor}

Scopes are used to organize P4 programs into nested namespaces. There are three
kinds of scopes in P4, from outermost to innermost: the top-level scope (global
namespace), the scope within a `parser` or `control` declaration (block
namespace), and the scope within a block statement (local namespace).

Cursors are used to represent scopes while defining the semantic rules of P4.

[#sec-scoping-dot-prefixed-name]
==== Dot prefixed names

${syntax: prefixedNonTypeName
          prefixedTypeName}

Identifiers prefixed with a dot are always resolved in the top-level namespace.

[source,p4]
----
const bit<32> x = 2;
control c() {
   int<32> x = 0;
   apply {
       x = x + (int<32>).x;  // x is the int<32> local variable,
                             // .x is the top-level bit<32> variable
   }
}
----

References to resolve an identifier are attempted inside-out, starting
with the current scope and proceeding to all lexically enclosing
scopes. The compiler may provide a warning if multiple resolutions are
possible for the same name (name shadowing).

[source,p4]
----
const bit<4> x = 1;
control p() {
    const bit<8> x = 8;    // x declaration shadows global x
    const bit<4> y = .x;   // reference to top-level x
    const bit<8> z = x;    // reference to p's local x
    apply {}
}
----

[#sec-scoping-name-visibility]
==== Name visibility

Identifiers defined in the top-level namespace are globally
visible. Declarations within a `parser` or `control` are
private and cannot be referred to from outside of the enclosing `parser`
or `control`.
