[appendix]
[#sec-grammar-ir]
== P4~IR~ grammar

// Added
This is the grammar of P4~IR~, which is produced after type checking a P4~16~
program. It is largely the same as the P4~16~ grammar, but with additional
information, such as type annotations for expressions.

// Added
${syntax:
  prefixedNameIR
  nameListIR
  voidTypeIR
  boolTypeIR
  errorTypeIR
  matchKindTypeIR
  stringTypeIR
  intTypeIR
  fixedIntTypeIR
  fixedBitTypeIR
  varBitTypeIR
  integerTypeIR
  baseTypeIR
  nameTypeIR
  typedefTypeIR
  newTypeIR
  aliasTypeIR
  listTypeIR
  tupleTypeIR
  headerStackTypeIR
  fieldTypeIR
  structTypeIR
  headerTypeIR
  headerUnionTypeIR
  valueFieldIR
  simpleEnumTypeIR
  serializableEnumTypeIR
  enumTypeIR
  dataTypeIR
  externMethodTypeDefEnv
  externObjectTypeIR
  parserObjectTypeIR
  controlObjectTypeIR
  packageObjectTypeIR
  tableObjectTypeIR
  objectTypeIR
  defaultTypeIR
  invalidHeaderTypeIR
  sequenceTypeIR
  recordTypeIR
  setTypeIR
  tableMetadataEnumTypeIR
  tableMetadataStructTypeIR
  tableMetadataTypeIR
  synthesizedTypeIR
  typeIR
  typeParameterIR
  typeParameterListIR
  parameterIR
  parameterListIR
  constructorParameterIR
  constructorParameterListIR
  namedExpressionIR
  namedExpressionListIR
  literalExpressionIR
  referenceExpressionIR
  defaultExpressionIR
  unaryExpressionIR
  binaryExpressionIR
  ternaryExpressionIR
  castExpressionIR
  dataExpressionIR
  errorAccessExpressionIR
  memberAccessExpressionIR
  indexAccessExpressionIR
  sliceAccessExpressionIR
  accessExpressionIR
  callableTargetIR
  constructorTargetIR
  callExpressionIR
  parenthesizedExpressionIR
  expressionIR
  expressionNoteIR
  typedExpressionIR
  typedExpressionListIR
  memberAccessBaseIR
  simpleKeysetExpressionIR
  simpleKeysetExpressionListIR
  tupleKeysetExpressionIR
  keysetExpressionIR
  typeArgumentIR
  typeArgumentListIR
  argumentIR
  argumentListIR
  lvalueIR
  emptyStatementIR
  assignmentStatementIR
  callStatementIR
  directApplicationStatementIR
  returnStatementIR
  exitStatementIR
  blockStatementIR
  conditionalStatementIR
  forUpdateStatementIR
  forUpdateStatementListIR
  forInitStatementIR
  forInitStatementListIR
  forCollectionExpressionIR
  forStatementIR
  switchLabelIR
  switchCaseIR
  switchCaseListIR
  switchStatementIR
  breakStatementIR
  continueStatementIR
  statementIR
  constantInitializerIR
  constantDeclarationIR
  initializerOptIR
  variableDeclarationIR
  blockElementStatementIR
  blockElementStatementListIR
  functionPrototypeIR
  functionDeclarationIR
  actionDeclarationIR
  objectInitializerIR
  instantiationIR
  objectDeclarationIR
  objectDeclarationListIR
  errorDeclarationIR
  matchKindDeclarationIR
  enumTypeDeclarationIR
  typeFieldIR
  typeFieldListIR
  structTypeDeclarationIR
  headerTypeDeclarationIR
  headerUnionTypeDeclarationIR
  derivedTypeDeclarationIR
  typedefIR
  typedefDeclarationIR
  externFunctionDeclarationIR
  externConstructorPrototypeIR
  externMethodPrototypeIR
  externObjectDeclarationIR
  externDeclarationIR
  selectCaseIR
  selectCaseListIR
  selectExpressionIR
  stateExpressionIR
  transitionStatementIR
  valueSetDeclarationIR
  parserTypeDeclarationIR
  parserBlockStatementIR
  parserConditionalStatementIR
  parserStatementIR
  parserStateIR
  parserStateListIR
  parserLocalDeclarationIR
  parserLocalDeclarationListIR
  parserDeclarationIR
  constIR
  constOptIR
  tableKeyIR
  tableKeyListIR
  controlPlaneNameIR
  tableActionReferenceIR
  tableActionIR
  tableActionListIR
  tableEntryPriorityIR
  tableEntryIR
  tableEntryListIR
  tablePropertyIR
  tablePropertyListIR
  tableDeclarationIR
  controlTypeDeclarationIR
  controlBodyIR
  controlLocalDeclarationIR
  controlLocalDeclarationListIR
  controlDeclarationIR
  packageTypeDeclarationIR
  typeDeclarationIR
  declarationIR
  p4programIR}
