(executable
 (name store_test)
 (modules store_test)
 (libraries p4spectec))

(executable
 (name splice_test)
 (modules splice_test)
 (libraries p4spectec))

(executable
 (name anchor_test)
 (modules anchor_test)
 (libraries p4spectec))

(executable
 (name document_test)
 (modules document_test)
 (libraries p4spectec))

(executable
 (name adoc_anchor_test)
 (modules adoc_anchor_test)
 (libraries p4spectec backend_adoc))

(rule
 (targets store.actual store_err.actual)
 (action
  (with-stdout-to
   store.actual
   (with-stderr-to
    store_err.actual
    (run ./store_test.exe)))))

(rule
 (aliases splice-latex runtest)
 (deps store.actual store_err.actual)
 (action
  (progn
   (diff store.expected store.actual)
   (diff store_err.expected store_err.actual))))

(rule
 (targets splice.actual splice_err.actual)
 (action
  (with-stdout-to
   splice.actual
   (with-stderr-to
    splice_err.actual
    (run ./splice_test.exe)))))

(rule
 (aliases splice-latex runtest)
 (deps splice.actual splice_err.actual)
 (action
  (progn
   (diff splice.expected splice.actual)
   (diff splice_err.expected splice_err.actual))))

(rule
 (targets anchor.actual anchor_err.actual)
 (action
  (with-stdout-to
   anchor.actual
   (with-stderr-to
    anchor_err.actual
    (run ./anchor_test.exe)))))

(rule
 (aliases splice-latex runtest)
 (deps anchor.actual anchor_err.actual)
 (action
  (progn
   (diff anchor.expected anchor.actual)
   (diff anchor_err.expected anchor_err.actual))))

(rule
 (target document.actual)
 (deps
  (source_tree ../../../docs/p4/sections-skeleton)
  ../../../docs/p4/P4-16-spec-new.adoc
  ../../../docs/p4/docinfo.html)
 (action
  (with-stdout-to
   document.actual
   (run ./document_test.exe ../../../docs/p4))))

(rule
 (target adoc_anchor.actual)
 (action
  (with-stdout-to
   adoc_anchor.actual
   (run ./adoc_anchor_test.exe))))

(rule
 (aliases splice-latex runtest)
 (deps adoc_anchor.actual)
 (action
  (diff adoc_anchor.expected adoc_anchor.actual)))

(rule
 (aliases splice-latex runtest)
 (deps document.actual)
 (action
  (diff document.expected document.actual)))
